### ISSUE TITLE
Aerofighter's Assault: wrong textures on planes

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#863] opened 2016-02-10 00:55 UTC
![sans titre](https://cloud.githubusercontent.com/assets/8987490/12935849/5bcbdef4-cf99-11e5-982f-b78cfe35948f.jpg)

**Comment by AmbientMalice** [comment] 2016-02-10 01:11
Isn't this a duplicate of https://github.com/gonetz/GLideN64/issues/628?

**Comment by gonetz** [comment] 2016-02-10 04:50
Yes, duplicate.

**Closed** 2016-02-10 06:10 UTC
Labels: bug, duplicate
