### ISSUE TITLE
Mario 64 broken hud

### ISSUE THREAD

**Issue by xiartic** [gonetz/GLideN64#2520] opened 2021-06-20 07:51 UTC
The hud in Super Mario 64 seems to have problems with the latest nightly "213c10d6". It happens with default settings. Changing the Internal resolution from "Same as output resolution" to "Original N64 resolution" or "Multiple of N64 resolution" fixes it but it's always broken on "Same as output resolution" which is the default. 

![GLideN64_SUPER_MARIO_64_000](https://user-images.githubusercontent.com/78692485/122666346-56c57900-d1b5-11eb-8fdd-31c605e23366.png)

**Comment by IronYoshi64** [comment] 2021-06-20 12:52
Does this happen on the GLideN64 build that comes with Project64 Dev? I asking because I had the same issues before I think, the WTL version was the issue, which that is the version that comes with Project64 builds from nightly page.

**Comment by xiartic** [comment] 2021-06-20 13:49
It happens in the version that's included in Project64 Public & Dev as well as in the latest WTL and QT versions of GLideN64. 

OoT's debug menu has similar problems as the HUD here.

**Comment by IronYoshi64** [comment] 2021-06-20 14:06
Yeah. I kind of posted an issue somewhat similar to this a few days ago. https://github.com/gonetz/GLideN64/issues/2517

This is a bad regression in several titles in rev. 213c10d6. Due to this issue in latest GLideN64 Dev, I am using an older version of GLideN64 dev. Rev 189afd39. https://ci.appveyor.com/project/gonetz/gliden64/builds/39476231/artifacts

But hopefully this can be fixed sometime soon, until then, I recommend you use that version above, the QT version.

**Comment by standard-two-simplex** [comment] 2021-06-22 15:35
@xiartic @IronYoshi64 Please test the build here https://github.com/gonetz/GLideN64/pull/2521. Should be the same as in 1d90610782343ad965c4cfdc2ffc1a8dc39256bc with "same as output resolution", so please report any difference before this gets merged to master.

**Comment by xiartic** [comment] 2021-06-23 17:55
Mario 64's hud is fine now, great! Ocarina of Time Debug Rom's text appears a bit messed up on "Same as output resolution" and even more with "Multiple of N64 resolution" still. I'm not sure if this should be another issue or not.

![GLideN64_THE_LEGEND_OF_ZELDA_000](https://user-images.githubusercontent.com/78692485/123145279-56530980-d465-11eb-8122-8d489d5c41dc.png)

![GLideN64_THE_LEGEND_OF_ZELDA_001](https://user-images.githubusercontent.com/78692485/123145294-59e69080-d465-11eb-9a62-3c3bf8171382.png)

**Comment by xiartic** [comment] 2021-06-23 19:51
@standard-two-simplex Everything works there. No issues with the HUD anymore.

**Comment by IronYoshi64** [comment] 2021-06-23 23:08
yeah I tried it last night and it seems to be all good now.
Although on a different note, I notice some slight pixel misalignment on the left side of the Hearts in Zelda OoT using that build:
![2021-06-23 18-05-51](https://user-images.githubusercontent.com/57850880/123178863-c3f33b80-d44d-11eb-8ed7-b200ef58ecf3.png)
Turning off the "Enable native-res bounds for texture coordinates" option in QT version for that, completely fixes it though.

**Comment by standard-two-simplex** [comment] 2021-06-24 10:12
> Hearts in Zelda OoT 

The game renders them in a weird way: they have a 0.5 texel offset and the texture is bigger than the screen rectangle. Without texture bounds, GLideN64 goes below this 0.5 and draws the heart correctly, because there is a texture to fetch from. With texture bounds, fetching below this 0.5 threshold is prohibited, so the first pixel is not as transparent as it should be. It is a sideeffect of the setting, I don't think there is much that can be done other than disabling it.

**Closed** 2021-07-23 14:28 UTC
