### ISSUE TITLE
Culling issue in Mystical Ninja 64?

### ISSUE THREAD

**Issue by ghost** [gonetz/GLideN64#523] opened 2015-05-09 23:23 UTC
I noticed a very strange issue in Mystical Ninja 64 with the 1.1 release. Now ,don't get me wrong, I am very much appreciative of the work that has and continues going into it, and admittedly, I feel really bad for bombarding those involved with such trivialities. 

]http://i.imgur.com/pG68XXy.png
![image](https://cloud.githubusercontent.com/assets/2043328/7552421/2ec116fc-f670-11e4-812d-39291e2b9329.png)

Is there a setting I may have missed with depth or framebuffer settings perhaps? I'm extremely glad the texture corruption is gone, like, super happy, but something ain't right here, and wondering if it's my end that's at fault. Thanks :3

**Comment by Mushman** [comment] 2015-05-10 05:01
Do you have ``Emulate N64 depth compare`` enabled? It can sometimes cause [effects to break](https://cloud.githubusercontent.com/assets/6550546/6891861/4ab20996-d70a-11e4-9bde-1c60e4cb0273.png) and [geometry problems](https://cloud.githubusercontent.com/assets/6550546/6891886/6c3b5a2c-d70a-11e4-9449-ce3d73b34a3b.png). If the problem persists with the setting off, then it's probably an issue in the plugin.

**Comment by therandomizer85** [comment] 2015-05-10 05:08
Sorry about the duplicate issue, internet must have flipped out when I posted it. Damn, I feel like an idiot, it worked, but the only reason I didn't have it on as there was a warning explicitly stating that it was experimental, so naturally I stayed clear of it as I was afraid it would cause the universe to collapse. Man, do I feel embarrassed :(

**Comment by Mushman** [comment] 2015-05-10 05:33
So enabling that setting fixed the problem? If so, I'll add it to the default game configuration so that no-one else encounters this issue.

**Comment by therandomizer85** [comment] 2015-05-10 05:35
But doesn't enabling an experimental option (as the little tool tip that pops up says) have any inherent risks? Should I test more games to see if they don't act weird beforehand?

**Comment by Mushman** [comment] 2015-05-10 05:41
The setting will only be enabled in this game. Many games use specific settings which are not enabled in other games. You can see them in ``GLideN64.custom.ini``. If it fixes the problem in the game you tested, it won't break any other games.

**Comment by AmbientMalice** [comment] 2015-05-10 05:44
I can't reproduce this issue. What is your GPU? Also, N64 Depth Compare makes this game render some stuff incorrectly.

**Comment by therandomizer85** [comment] 2015-05-10 05:47
MSI nVidia GTX 660 2 GB. PJ64 2.2.0.2, once I enabled it, it went away. See? I told you that I wasted your guys' time like a loser, if I encounter another "glitch" I might as well not report it since it's just a triviality :(

**Comment by Mushman** [comment] 2015-05-10 05:49
Hm. I'll test it myself now. If the same setting causes opposite behaviour for two different users, then that's really weird.

**Comment by therandomizer85** [comment] 2015-05-10 05:50
No kidding, but I didn't make that picture up, it happened before I enabled it, and if neither of you can reproduce the issue, I completely throw my arms up in the air and will never report any trivialities again. I mean, what would be the point if no one else can reproduce the errors. Damn it all :/

**Comment by Mushman** [comment] 2015-05-10 05:53
Hey now, don't worry yourself too much. It's just a thread on the tracker. I haven't even tested it yet. I'm sure anyone else experiencing an issue like this, even though it's small, would want it fixed.

**Comment by therandomizer85** [comment] 2015-05-10 05:54
Sorry, I just hate it when I report something and no one else can seem to reproduce an issue on their end, I seem to have a curse with it or something. If  need be, I'll record with nVidia Shadowplay before and after. I just tend to be hard on myself, that's all. Sorry about that. I hope others can reproduce it ;)

**Comment by AmbientMalice** [comment] 2015-05-10 06:12
>If the same setting causes opposite behaviour for two different users, then that's really weird.

In my case, N64 Depth causes decals that are really close to surfaces to render behind instead.

**Comment by Mushman** [comment] 2015-05-10 06:19
I tested using the (U) version with Public Release 1.1 ``012b5e3`` 8 May build on a NVidia Geforce GTX 970 using Project64 2.2 and did not experience it. I believe you encountered the issue and that when you enabled N64 Depth Compare it was fixed, but I don't know why this happened for you. It may have been a weird one-off bug and it appeared fixed when the emulator was restarted, or it could be a result of a legitimate configuration combination that wasn't accounted for.

Were you also testing the (U) version with Public Release 1.1 of the plugin? Could you try testing on Mupen64Plus and seeing if it happens there too? Does it still happen with N64 Depth Compare off in a new instance of Project64, reaching that part without loading save states?

**Comment by therandomizer85** [comment] 2015-05-10 06:35
Yes, I tested those, sorry for the delayed response, will try on Mupen64 2.5 and report back.  Another thing I'll try is recording the desktop with Shadowplay with it off, load the ROM, turn it back on, then load the ROM again. ROM is NTSC-U for the record.

**Comment by Mushman** [comment] 2015-05-10 06:44
Maybe Geforce Experience is interfering somehow? I don't know. Something that might be worthwhile to keep in mind.

**Comment by therandomizer85** [comment] 2015-05-10 06:44
Yup, tested Mupen84, 1.1 version of the plugin, NTSC version of the ROM with the depth option both on and off, can't reproduce it on the emulator. So now I'm gonna test it on PJ64 again. Mupen64 is clean.

**Comment by gonetz** [comment] 2015-05-25 06:20
@therandomizer85 - please update or close.

**Comment by purplemarshmallow** [comment] 2015-05-27 15:35
@gonetz I can reproduce it
there are depth problems if you resize the window in mupen64plus
looks exactly like the screenshot @therandomizer85 posted
looks like it's the same issue as #558

**Comment by therandomizer85** [comment] 2015-05-27 16:42
@purplemarshmallow The issue can be resolved by enabling N64 depth compare

**Comment by purplemarshmallow** [comment] 2015-05-27 17:23
if I enable N64 depth compare and then resize the window in mupen64plus I get this:
looks even worse
![1](https://cloud.githubusercontent.com/assets/7283660/7842789/c9df9fbc-04a5-11e5-93ce-d072339b2012.jpg)

**Comment by therandomizer85** [comment] 2015-05-27 17:56
Seriously? Damn. Well, it works fine on my end :/

**Comment by purplemarshmallow** [comment] 2015-05-27 18:27
@therandomizer85 
I only have this problem if I resize the window in mupen64plus
do you know any other ways to reproduce it?
and are you sure enabling N64 depth compare fixes it for you?

**Comment by therandomizer85** [comment] 2015-05-27 18:52
I don't use Mupen64, I use PJ64 2.2.0.3 - on there yes, I'm sure it fixes it. Not sure about Mupen64. Dammit all to hell :(

**Comment by purplemarshmallow** [comment] 2015-08-23 08:11
fixed

**Comment by therandomizer85** [comment] 2015-08-23 19:39
Awesome, are those builds on EmuCR the latest builds with these fixes?

**Comment by purplemarshmallow** [comment] 2015-08-23 21:14
I'm not so sure about EmuCR builds, I think they have have these fixes but they are also broken in some way

**Comment by therandomizer85** [comment] 2015-08-23 22:21
Well, are there compiled builds that aren't broken?

**Comment by purplemarshmallow** [comment] 2015-08-24 07:39
New builds are sometimes uploaded here, for example #674

https://drive.google.com/file/d/0B0YqMPjGo3B2Um9YOFd3UGV0SzQ/view?usp=sharing

Please close if you can't reproduce this problem anymore with this build

**Comment by AmbientMalice** [comment] 2015-11-23 05:10
@ghost Can this issue be closed?

**Comment by purplemarshmallow** [comment] 2015-11-23 10:38
ghost means the user got deleted. I fixed this bug. @gonetz can you close?

**Comment by gonetz** [comment] 2015-11-23 10:58
Please provide number of revision, which fixes that issue and I'll close it.

**Comment by purplemarshmallow** [comment] 2015-11-23 11:09
https://github.com/gonetz/GLideN64/commit/01ffde2aa91f0f33e5bdb5dd8cb5998d7698ab1e

**Comment by gonetz** [comment] 2015-11-23 11:14
Thanks

**Closed by gonetz** 2015-11-23 11:14 UTC
