### ISSUE TITLE
Rat Attack missing projection in HLE

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1953] opened 2018-12-07 16:36 UTC
![gliden64_rat_attack_001](https://user-images.githubusercontent.com/8987490/49660310-8ae94c00-fa46-11e8-9852-32ada4659ccf.png)

Works in LLE.

**Comment by gonetz** [comment] 2018-12-28 05:49
Duplicate of #600

**Closed by gonetz** 2018-12-28 05:49 UTC
