### ISSUE TITLE
Option to disable bilinear filtering

### ISSUE THREAD

**Issue by Alien-Grey** [gonetz/GLideN64#1691] opened 2017-12-20 10:40 UTC
Is it possible to add an option to disable bilinear filtering?
The image looks too blur on a small high resolution screen.

**Comment by gonetz** [comment] 2017-12-21 06:03
It is possible.
I will not touch texture filtering until new Public Release.
After that texture filtering options can be discussed.

**Comment by oddMLan** [comment] 2019-11-05 19:57
#2088 is a duplicate of this, but has more detailed information and the intent is clearer. I suggest closing this ticket.

**Comment by gonetz** [comment] 2019-11-06 06:31
Ok, closed in favor of #2088

**Closed by gonetz** 2019-11-06 06:31 UTC
