### ISSUE TITLE
Rat Attack in PJ64 not working when HLE and GLideN64 is used. 

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1975] opened 2018-12-28 05:10 UTC
Rat Attack will give errors in HLE mode when using GLideN64, but works fine with AL+

**Comment by theboy181** [comment] 2018-12-28 05:18
Update : Turn off FB and game will boot.

**Comment by gonetz** [comment] 2018-12-28 05:48
Duplicate of #600

**Closed by gonetz** 2018-12-28 05:48 UTC
