### ISSUE TITLE
Transparency issues in Paper Mario 64.

### ISSUE THREAD

**Issue by Nathidraws** [gonetz/GLideN64#2293] opened 2020-06-14 15:38 UTC
Some buildings are semi transparent sometimes.

**Comment by standard-two-simplex** [comment] 2020-06-14 15:57
@Nathidraws  Please post a picture and if possible a savestate.
Also, it might be useful to know which graphics card the device you're using has.

**Comment by Nathidraws** [comment] 2020-06-14 16:20
For some odd reason it's not happening anymore, but it was in Toad Town, and some of the buildings walls were semi transparent.

I'm not sure what fixed it. All I did was delete the ini file and test out older versions of GlideN64.

Heres a savestate.
[Paper Mario.zip](https://github.com/gonetz/GLideN64/files/4776822/Paper.Mario.zip)

**Comment by standard-two-simplex** [comment] 2020-06-14 17:14
I can't reproduce it either. It might have been a shader storage issue, shaders have changed but shader version number haven't.
If you come across the issue again, please report back. If you can't reproduce the issue after some hours of gameplay, you may close the issue.
@gonetz If it's ok, raise the shader version please.

**Comment by gonetz** [comment] 2020-06-15 02:56
> If it's ok, raise the shader version please.

Done: d23457022c6

**Closed by gonetz** 2020-06-15 02:56 UTC
Labels: Waiting for response
