### ISSUE TITLE
[Feature Request] Shaders

### ISSUE THREAD

**Issue by daninthemix** [gonetz/GLideN64#1808] opened 2018-05-07 15:42 UTC
Would love it if GlideN64 would allow us to select shaders to apply on top of the finished image - for example any of the many CRT shaders available, or anything in glslp format.

**Comment by gonetz** [comment] 2018-05-08 12:17
Duplication of #1697

**Comment by oddMLan** [comment] 2019-11-05 20:13
Duplicate of a duplicate 😐
Duplicate of #732

**Closed** 2019-11-06 06:51 UTC
Labels: duplicate
