### ISSUE TITLE
Supe Smash Brothers SSB hitbox cheatcode not working correctly

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#830] opened 2016-01-03 01:43 UTC
When you enable the cheat code that enables hitboxes using GLideN64 the hitbox for weapons is displayed incorrectly.

Using AL, or Rice Video it works as expected.

I can upload a screenshot if needed, but I think its self explanatory. 

Fixing this issue may fix various issues elsewhere, like the misaligned textures in Kirby Dream Land floor while using HLE (works LLE)

**Comment by theboy181** [comment] 2016-01-03 01:53
![capture3](https://cloud.githubusercontent.com/assets/9299743/12076960/a4e10cb0-b179-11e5-9fc9-58b6ee2ae031.PNG)
![capture1](https://cloud.githubusercontent.com/assets/9299743/12076961/a503829a-b179-11e5-8ad7-4698d432ad4c.PNG)

**Comment by theboy181** [comment] 2016-01-03 01:55
Like to add that the filtered tree looks horrible on GLideN64. Why does it make thinks look blocky?

**Comment by gonetz** [comment] 2016-05-17 10:47
I need a savestate.

**Comment by olivieryuyu** [comment] 2016-05-23 22:35
the hitbox should be red with with color around.

Here a ss of Angrylion plugin and it is the same with GlideN64.

![dsfd](https://cloud.githubusercontent.com/assets/8987490/15486619/67b18304-2147-11e6-972e-de73e0eba916.jpg)

**Comment by olivieryuyu** [comment] 2016-05-23 22:38
btw to get hitboxes: cheat codes is 810F2C04 2400

**Comment by LegendOfDragoon** [comment] 2016-05-23 22:51
The problem is red hitbox. Here's the code for red hitbox 810F33BC 2400 . You have to use both codes.

**Comment by gonetz** [comment] 2016-08-28 10:20
Is it still actual or we can close it?

**Comment by LegendOfDragoon** [comment] 2016-08-28 19:35
Fixed. you can close.

**Closed** 2016-08-29 06:05 UTC
Labels: bug
