### ISSUE TITLE
Indiana Jones/Battle of Naboo microcode Implementation

### ISSUE THREAD

**Issue by Frank-74** [gonetz/GLideN64#1259] opened 2016-11-25 23:18 UTC
Any chance of work being done to HLE this game?

I've made a fixed branch of Project64 that has an RDB option hack for Indiana Jones and Battle for Naboo here: https://github.com/Frank-74/project64/tree/ForceFpuLoc

This build has fixes for savestates as well, so both old and new types work, compressed or uncompressed.
Compiled build with VS2008 SP1 here: https://dl.dropboxusercontent.com/u/9498358/n64/Project64FixFpuLoc.zip

GLideN64 just hangs with a black screen, whereas Glide64 responds with:
Error: Unsupported uCode!
crc: d5c4dc96.

Jabo 1.7 just crashes the emulator, but 1.6.1 gives this:
Unable to detect microcode settings
Microcode ID: $8A4F88F1.

LLE is fine, but it's slow.

**Comment by gonetz** [comment] 2016-11-26 03:03
Only if somebody will decode that microcode.

**Comment by Papermanzero** [comment] 2016-11-27 16:41
Same applies fro the factor 5 games like rogue squadron.

**Comment by olivieryuyu** [comment] 2016-12-24 15:11
games seems to have nearly the same ucode, i am even surprised that it does not work with Lemmy plugin a bit actually. Just got a very quick look, can be wrong here.

**Comment by Frank-74** [comment] 2016-12-26 13:49
Maybe microcode for, Battle for Naboo, Rogue Squadron, Indiana Jones will be quite similar if not the same.
Indiana Jones is quite a good adventure when you get into it.  Even with the odd bugs.

**Comment by gonetz** [comment] 2016-12-26 14:43
I looked at Rogue Squadron implementation in Lemmy plugin. Very specific and unique thingy.

**Comment by olivieryuyu** [comment] 2016-12-26 15:21
Yes I cannot find point of comparison with other ucode. 

However between Rogue Squadron, Battle of Naboo and Indiana Jones, it is nearly the same ucode.

**Comment by olivieryuyu** [comment] 2017-03-04 08:50
Taking a deeper look into the Naboo ucode. Difference are bigger than I thought. Same style of coding, certainly same underlying concept but Naboo seems to be a huge optimization of Rogue Squadron.

**Comment by olivieryuyu** [comment] 2017-08-08 06:50
Seeing Indiana Jones, I understand why it is needed to have a correct FPU emulation on the N64 CPU side as I would think that the matrix is calculated by the CPU, not the RSP.

**Comment by AmbientMalice** [comment] 2017-09-21 12:07
Rogue Squadron still seems buggy in HLE.

![rogue_squadron-000](https://user-images.githubusercontent.com/10704701/30694830-3087e0e8-9f19-11e7-872e-bd12d0553de1.png)
![rogue_squadron-001](https://user-images.githubusercontent.com/10704701/30694829-3067f3f0-9f19-11e7-9c3f-691075151560.png)

**Comment by olivieryuyu** [comment] 2017-09-21 12:17
@AmbientMalice 

pleas open a separate ticket for this one

thx

**Comment by olivieryuyu** [comment] 2017-09-29 20:49
@Frank-74 
Can you rename this ticket Indiana Jones/Battle of Naboo microcode Implementation please?

For your information, I started some prelimilary work on those games. They are significant different than SWRG but Indy and Battle of Naboo are quite the same (some differences exists).

For the time being, I am hopeful it can be done with a lot of efforts.

**Comment by StenApp** [comment] 2017-10-04 20:09
I'd like to help here, but except for the n64 Manuals (http://ultra64.ca/resouorces/documentation/) 
i have no infos what to do.
How can i dump ucode? Nemu doesn't help here...

**Comment by olivieryuyu** [comment] 2017-11-29 17:10
This ucode is really complex. For those interested, there is an old article about the game here:

http://www.ign.com/articles/2000/11/10/bringing-indy-to-n64

A good part of the ucode was rewritten but it was not totally "rewritten from scratch".

Few features in this ucode are very unique. Interesting but challenging.

**Comment by StenApp** [comment] 2017-11-30 22:05
I dumped some ucode from battle for naboo/indy and compared it with rogue squadron.
One part was the same for all, and one is the same like in BfN and Indy.
[RSP code indy.txt](https://github.com/gonetz/GLideN64/files/1519631/RSP.code.indy.txt)
[RSP code indy2.txt](https://github.com/gonetz/GLideN64/files/1519632/RSP.code.indy2.txt)
[RSP codebfn2.txt](https://github.com/gonetz/GLideN64/files/1519633/RSP.codebfn2.txt)
[RSP codebfn11.txt](https://github.com/gonetz/GLideN64/files/1519634/RSP.codebfn11.txt)

**Comment by StenApp** [comment] 2017-12-05 11:28
@olivieryuyu  Can you provide any useful information on how i can help with decoding?
How to start out?

**Comment by olivieryuyu** [comment] 2017-12-05 11:45
@StenApp 

I already deciphered a big portion of the microcode.

Thanks for help though!

**Comment by StenApp** [comment] 2017-12-05 21:21
@olivieryuyu sounds great, thank you. Can you give a short status? Blog entry maybe?

**Comment by olivieryuyu** [comment] 2017-12-05 21:36
Update will be shared where possible. Stay tuned.

**Comment by weinerschnitzel** [comment] 2017-12-05 23:14
@olivieryuyu, i would love to read a bit more about your adventures with reverse engineering. I understand as far as dumping the microcode and translating MIPS assembly to x86 or C, but im sure you've learned some tricks to identify certain patterns. Would be cool to see a video or guide that tells someone what they need to get the job done

**Comment by olivieryuyu** [comment] 2017-12-21 23:55
a really crazy ucode...

Do you believe that the menu are simple sprites (texture rectangles)???

![omg](https://user-images.githubusercontent.com/8987490/34279702-bfe48c74-e6b2-11e7-9de1-2677b9011d92.jpg)

Nope!!! They are triangles!!!!!!

**Comment by AmbientMalice** [comment] 2017-12-22 00:13
I assume that was in order to achieve the "flipping page" transitions without resorting to framebuffer tricks.
![indiana_jones-011](https://user-images.githubusercontent.com/10704701/34280026-90ff79f2-e700-11e7-9cd7-35ef58f528e6.png)

**Comment by gonetz** [comment] 2018-01-06 02:54
We started new crowdfunding campaign for Indi and Naboo on Idiegogo:

https://igg.me/at/indihle

Visit it to see what is already done and what is planned to be done when the campaign will reach the goal. Any kind of support is welcome.

**Comment by StenApp** [comment] 2018-01-06 13:03
Supported of course! Like to see "unknown ucode" message vanished.

**Comment by StenApp** [comment] 2018-01-26 20:10
How about to post a reddit entry?
I'm to new there so my post got deleted.

**Comment by olivieryuyu** [comment] 2018-02-01 19:11
I have no reddit. 

The campaing does not seem to be successful, that is a bit unfortunate...

It is a hard work to do the reverse engineering and the microcode of Factor 5 are really huge and complex compared to the others.

For instance Indiana Jones/Battle of Naboo is double the size of F3DEX2, which was the biggest Nintendo microcode.

**Comment by oddMLan** [comment] 2018-02-01 19:38
@StenApp

It probably got deleted because there's already one for the campaign: https://www.reddit.com/r/emulation/comments/7ogzuc/gliden64_indiana_jones_and_the_infernal_machine/?utm_source=amp&utm_medium=comment_header

**Comment by StenApp** [comment] 2018-02-02 21:05
@oddMLan  I think it was my first post on reddit, I would have needed to post or comment things before.

@olivieryuyu I'm not sure why so less people support your decoding, It's sad because Factor5 games are the last games to get native. I'd like to see in the end of decoding how you did that in form of technical blog or documentation. None the less: respect for your work.

**Comment by weinerschnitzel** [comment] 2018-02-03 07:02
I am sure there are others that will donate more before the campaign is over. And the campaign is very modest, it will be filled.

Although, yes, i do think this should drive more attention.

**Comment by tony971** [comment] 2018-02-03 11:31
It might be useful to make sure that people realize that the dev is not Gonetz, who has a running patreon for GLideN64.

**Comment by olivieryuyu** [comment] 2018-02-03 13:53
It is a campaing of both Sergey and me.

After Indy, there is still many things in HLE to do:

Batte of Naboo specific commands
HVQ microcode
Fog issue in Zelda OOT
S2DEX issues in various games
Dark Rift issues

Of course this campain would be the last one for supporting reverse engineering in GlideN64. But seeing the little attention it brings, it is a bit demotivating :(

**Comment by weinerschnitzel** [comment] 2018-02-03 15:02
@olivieryuyu what is your input for the 64DD games? Certainly those will need some work, too. Campaign is funded so get it done please. No more mulling! :)

**Comment by StenApp** [comment] 2018-02-03 16:08
mhhh one spend anonymously the rest to fill the 600 Dollar, it's the second time one did.

**Comment by olivieryuyu** [comment] 2018-02-04 09:09
@weinerschnitzel. Thanks. 64DD uses standard ucodes, I already checked out.

@StenApp : at the end of my HLE adventures (many months), I will do a small introduction on how I do the reverse engineering. Yet the first step is to understand MIPS (https://chortle.ccsu.edu/AssemblyTutorial/index.html)

**Comment by StenApp** [comment] 2018-02-04 11:02
@olivieryuyu 
When I look at my dumps of Indy and BFN I see what you mean with double the size as SDEX2 code.
One started with `0x000	J	0x064` and one with ` 0x000	ORI	V1, R0, 0x0000`.

**Comment by olivieryuyu** [comment] 2018-02-04 11:17
Your dumps are only partial ones, they do not cover the entire ucode. It is due to the usage of overlays as the code does not fit entirely in the IMEM. I will explain this in the introduction when my adventures are over.

**Comment by olivieryuyu** [comment] 2018-02-04 17:24
Small remarks: one of the command uses a specific COP0 register to simulate a random value for the particule systems.

No RSP emulates this, so LLE implementation does not behave exactly as it should.

In HLE it is possible to circumvent this issue and therefore being more close to result on a real N64.

So for once HLE is better than LLE :)

**Comment by theboy181** [comment] 2018-02-04 18:02
I’m simply amazed at how much knowledge and abilities you have gained in only a couple of years. Appreciate your hard work @olivieryuyu

**Comment by StenApp** [comment] 2018-02-25 17:24
last call for supporting of the Indiegogo campaign:

https://igg.me/at/indihle

**Comment by olivieryuyu** [comment] 2018-03-03 15:36
![1](https://user-images.githubusercontent.com/8987490/36936080-a850c934-1f00-11e8-898d-a73f5acb4f77.jpg)
![2](https://user-images.githubusercontent.com/8987490/36936081-a876eb46-1f00-11e8-883c-4c04aea34593.jpg)
![3](https://user-images.githubusercontent.com/8987490/36936082-a89b586e-1f00-11e8-965f-6f54ae2b6834.jpg)

Few screenshots of the particle effects system in the HLE version.

Bug reports are now welcome for Indiana Jones from backers.

**Comment by olivieryuyu** [comment] 2018-03-06 19:15
two bugs so far:

- snow in level 4 depth issue
- crash at the waterfall in level 1

**Comment by StenApp** [comment] 2018-03-06 20:15
Impressive work

**Comment by olivieryuyu** [comment] 2018-03-06 22:18
it works with PJ64 and Mupenplus indeed.

The other emus may boot the game but they will have various graphic bugs.

**Comment by olivieryuyu** [comment] 2018-03-10 07:33
MFC0 V0, DP clock counter

DP clock counter is not emulated any RSP plugin I would think.

**Comment by LegendOfDragoon** [comment] 2018-03-10 07:40
Thanks! I figured it was the clock counter :smile: . So far, I've only seen that get used in Pokemon Stadium 2 GB Tower iirc. Of course my microcode collection is nowhere near complete though.

I guess I'll have to try dumping more of indiana jone's code, so I can see what it does with that number.

**Comment by olivieryuyu** [comment] 2018-03-10 09:43
crash at the waterfall in level 1 fixed.

Need now to focus on the terrain generation for Battle of Naboo. It will be a long long road...

**Comment by olivieryuyu** [comment] 2018-03-17 14:41
Working on Battle of Naboo. It is clear that the technic used for ground generation is a heighmap. From colors Y is generated with X and Z provided by the CPU.

Still amazed what Factor could do with microcode.

**Comment by StenApp** [comment] 2018-03-18 22:41
@olivieryuyu 
Is it similar to Rogue Squadron's terrain generation system?

**Comment by olivieryuyu** [comment] 2018-03-19 06:54
No really.

**Comment by olivieryuyu** [comment] 2018-05-06 10:31
few screenshots of the HLE version of Battle of Naboo

Ground generation works nearly flawlessly

![ss2](https://user-images.githubusercontent.com/8987490/39672355-2a104b02-5129-11e8-9a1b-467c033d8f4e.jpg)

Particles system: 

![ss1](https://user-images.githubusercontent.com/8987490/39672358-369eb818-5129-11e8-91fa-8e5de36de5e0.jpg)

Space fights

![ss3](https://user-images.githubusercontent.com/8987490/39672368-5061d3e8-5129-11e8-9a9d-142c0a9aab82.jpg)

**Comment by gonetz** [comment] 2018-05-16 15:28
https://www.indiegogo.com/projects/indiana-j-infernal-machine-high-level-emulation/x/8367908#/updates/all

https://youtu.be/Yp0fzmcAdWg

**Comment by fzurita** [comment] 2018-05-16 15:40
Nice, when will source code be updated with the fixes?

**Comment by StenApp** [comment] 2018-05-16 21:14
@gonetz @olivieryuyu  impressive work you two!

**Comment by weinerschnitzel** [comment] 2018-05-17 00:14
Well done @olivieryuyu and @goner. I hope you and as much fun the adventure as I did following!

**Comment by gonetz** [comment] 2018-05-17 07:11
It is close now. I need to polish the code: remove debug stuff (circa 4K lines atm), add optimizations etc.
Then it will be pushed to feature branch and after public beta testing will go to master.

**Comment by theboy181** [comment] 2018-05-17 15:14
Exciting times a head!!

**Comment by schubertguilherme** [comment] 2018-05-17 17:58
@gonetz
Congratulations on the work of Indiana Jones and Star Wars Batlle For Noob although I became aware of the campaign late, I wanted to help with the donation but had already closed the deadline. I am anxious. Congratulations. and hugs.

**Comment by theboy181** [comment] 2018-05-17 18:52
I’m excited and I was certain it would happen even if I didn’t donate this time.

**Comment by StenApp** [comment] 2018-05-19 16:36
I'd like to test the alpha, but my system isn't working right.
Flickers always:

![800x600](https://user-images.githubusercontent.com/32524257/40270763-472ac130-5b93-11e8-8dd3-c17c0e9de58a.png)
![smaller](https://user-images.githubusercontent.com/32524257/40270764-4745d13c-5b93-11e8-9a26-bc6ff8f78599.png)
Since I compiled mupen64plus-gui on macOS/MacBook Pro I'm unsure how to nail this down.

**Comment by loganmc10** [comment] 2018-05-19 16:39
I don't think mupen64plus-gui works properly on Mac

**Comment by StenApp** [comment] 2018-05-19 16:40
@loganmc10 
okay but how can I check which component isn't working right?

**Comment by loganmc10** [comment] 2018-05-19 16:47
It's the GUI itself, you filed a bug for this a while ago: https://github.com/m64p/mupen64plus-gui/issues/33

**Comment by gonetz** [comment] 2018-05-26 11:40
The task completed:
https://gliden64.blogspot.ru/2018/05/hle-implementation-of-microcodes-for.html

Source code pushed to feature branch:
https://github.com/gonetz/GLideN64/tree/indi_naboo

Windows beta builds:
https://drive.google.com/file/d/1rQCMNWo684HFHLLGWBBVvuiW6dlUOJYt/view?usp=sharing

Notice for developers: The microcodes use advanced particles system. Particles rendered with texrect command. GlideN64 implementation of texrect is not fast. Thus, I implemented optimized version of textured rectangles, specially for particles. It can be up to hundred times faster than original. Unfortunately, that optimization involves bunch of hacks. The way particles system works makes hack-less optimization impossible. The commit with this optimization is "Indi Particle Optimization hack.". Desktop test builds do not include that optimization: the code works fast enough without it. I'd like you to test the code with and without that optimization on mobile devices. If there will be no difference, the hack will not go to master. You may test the 3rd level of Indiana and 3rd level of Naboo - they use lots of particles.

**Comment by fzurita** [comment] 2018-05-26 12:03
Do you happen to have a save state for Mupen64plus?

**Comment by AmbientMalice** [comment] 2018-05-26 12:29
I won't be able to test for a day or so, but I'm curious whether PJ64 will crash at the end of each level with GLideN64 the same way it does with LLE plugins like Angrylion's. Fortunately, the game should work perfectly on mupen64plus, though.

**Comment by AmbientMalice** [comment] 2018-05-26 12:33
@loganmc10 m64p is probably hardcoded to use LLE for Indy/Naboo, IIRC, so you should probably rectify that.

**Comment by loganmc10** [comment] 2018-05-26 14:27
Alright I've updated m64p, it should attempt to run these games in HLE by default now

**Comment by olivieryuyu** [comment] 2018-05-26 14:29
And here we go, the code is finally released to the world :)

As written by Sergei on his blog, it was a long and hard road It was long days and nights of deciphering a difficult code ... But the result is here!!! :D

The ucode is based actually on F3DEX for some parts but changed so drastically that not so much remains from the original ucode.

A side note: the RSP of the N64 is a powerhorse actually: 62mhz MIPS coprocessor with a vectors unit. You could clearly do a lot of math with it and this is what the Factor 5 devs did, enhancing the possibility of effects of the N64 (lighting, particles, etc).

The ucode attempts also to mitigate the RDP fillrate limitations by segmeting the memory in a specific way and running "sub-displaylist" only when some graphics will be drawn on the screen.

I am not surprised about the comment in one of the interviews of the Factor devs that it was hard to fight against fill rate limitation. It is cleary the bottleneck of the N64 and this is why the Zstorp ucode is actually the correct and most likely solution for having a high level of polygons and high resolution on the N64.

Also there is something to add: **ALL** games are now playable in HLE. 

Ultra64 introduced the concept of HLE and it was critized that HLE could never be as compatible as LLE.

Well if HLE won't be totally accurate of course, it proves to be still a valid concept of emulation. Plenty of people prefer playing in HLE.

 Battle of naboo cheat: LEC&FIVE
Indiana Jones cheatt: FORGEOFF

It give access to all levels :)

If someone courageous could go through both games and try to find bugs, that would be cool.

**Comment by theboy181** [comment] 2018-05-26 15:13
Indy 60 fps 

81058F76 0001
80058F71 0001
80058F6F 0001

Needs testing.. Have fun. .

**Comment by theboy181** [comment] 2018-05-26 15:17
Hey guys,

been hanging on to these since the announcement of HLE GLideN64 - I opted out of the donations, so I was unable to fully test these two codes. Please let me know if there are any issues. 

Indiana Jones and the Infernal Machine (U)
60 FPS Hack

81058F76 0001
80058F71 0001
80058F6F 0001

Note: OC = 2. Needs more testing now that HLE is possible
Star Wars Episode I - Battle for Naboo (U)
60 FPS Hack

81080296 0001

Note: OC = 2. Needs more testing now that HLE is possible.

**Comment by theboy181** [comment] 2018-05-26 15:34
Noticed during some of the cut-scenes that the water texture overlaps in places where it shouldn't.

![image](https://user-images.githubusercontent.com/9299743/40577772-94e64f76-60bf-11e8-9090-e11056adccc4.png)

**Comment by AmbientMalice** [comment] 2018-05-26 23:44
Found a bug. In the opening sequence of the third mission, Indy's jacket is bugged.

Angrylion's:
![indiana_jones-018](https://user-images.githubusercontent.com/10704701/40581074-7ac147bc-6192-11e8-9a2d-23e35170b441.png)

GLideN64 HLE:
![indiana_jones-017](https://user-images.githubusercontent.com/10704701/40581073-7a83cac2-6192-11e8-9bd9-eef990d167cf.png)

**Comment by fzurita** [comment] 2018-05-28 05:18
@gonetz I tested in Android. The particle hack adds about 10-20% performance improvement on level 3 of battle for naboo. In my Snapdragon 835 device, the game goes from 27-35fps to 35-43fps on level 3. I think the hack is worth while since it makes the game run full speed on my device.

**Comment by gonetz** [comment] 2018-05-29 13:37
Bug fixed. New beta build:
https://drive.google.com/file/d/1kG1_lD4dXIYO0F5zlBHRY6x7aRuWC3y4/view?usp=sharing

**Comment by AmbientMalice** [comment] 2018-05-29 14:15
Happy to report that the life raft has also been fixed. I assumed they were probably the same issue, so I didn't report before:

Beta1:
![indiana_jones-025](https://user-images.githubusercontent.com/10704701/40664545-84048236-639e-11e8-986e-54309930fb54.png)

Beta2:
![indiana_jones-026](https://user-images.githubusercontent.com/10704701/40664567-907e1bb2-639e-11e8-93a2-9536c0291d5c.png)

**Comment by gonetz** [comment] 2018-05-29 14:40
Cool! The bug was in very basic functionality. It could cause much more troubles.

**Comment by gonetz** [comment] 2018-05-29 14:43
BTW, this build includes particles optimization hack. If you will find a regression with particles, please report.

**Comment by nterry** [comment] 2018-05-29 22:29
@gonetz You mention on one of the articles linked here that theres a useful spreadsheet from @olivieryuyu Where can I get that spreadsheet? Also, I am in the midst of experimenting with real hardware and I'd love to play around with this. Where can I get the source for just the ucode that I can run through the nintendo ucode compiler?

**Comment by gonetz** [comment] 2018-05-30 02:17
Better to ask @olivieryuyu about it. I may publish only my part of the  work.

**Comment by nterry** [comment] 2018-05-30 17:01
@gonetz Tell you what, if you and @olivieryuyu  release your work, i'll Paypal 200 dollars for you to split. It must be in a form I can compile ("out of the box") for the n64 (hardware) using the sdk and id need a LOT of comments explaining things. Plus Id want a skeleton spec file prepared with the correct parameters for the microcode. If anyone wants to contribute more, I can set up a gofundme, but my 200 stands.

Id even be willing to upfront some (up to half) of it as a goodwill gesture (we can negotiate). That is how badly I want this ucode.

To qualify, it must also be under an OSS license other than the GPL (or LGPL). Apache and MIT are both fine and preferred.

If you wish to move forward, send me an email at nicholas@nicholasterry.com and we can talk further.

**Comment by LegendOfDragoon** [comment] 2018-05-30 17:17
>It must be in a form I can compile ("out of the box") for the n64 (hardware) using the sdk and id need a LOT of comments explaining things.

RSP microcode was written in pure assembly. It's not compiled. You could just dump the microcode, if you really want it. Comments could be useful though.

**Comment by olivieryuyu** [comment] 2018-05-30 18:30
Hi Nicholas,

I don't think what you are asking is even possible (not without a lot of work at least).

If you are really interested to do that, I guess your best chance would be indeed to dump the ucode and check the microcode implementation of Sergei.

Olivieryuyu

**Comment by StenApp** [comment] 2018-05-30 21:07
Some idealistically things are non-buyable...

**Comment by schubertguilherme** [comment] 2018-05-31 16:09
Hi, why build beta (Indiana Jones and Star Wars) not working with Project 64 2.3.2? Start with Black Screen. Here Star Wars Rogue Squadron playable normal with Project 64 2.3.2 and RSP Mupen64Plus.

**Comment by theboy181** [comment] 2018-05-31 16:22
Perhaps pj64 forces lle for that game. Check in advanced settings

**Comment by gonetz** [comment] 2018-06-01 03:17
I have weird graphics issues with Project64 2.3.X, both in HLE and LLE, regardless of graphics plugin.
Project64 2.4.X works fine.

**Comment by oddMLan** [comment] 2018-06-01 04:18
The reason it works 2.4 I think it has something to do with the DK64 Bone Fix, which affects other games. An accuracy improvement. Something to do with float point magic. The fix was also ported to mupen64plus, so it should work well there too, as long as it is a recent version.

**Comment by GamingTVYT** [comment] 2018-06-03 08:43
Hello everyone, I'm testing the version (GLideN64_indi_naboo_beta3) and I found the first Bug on the screen (Battle for Naboo). Amazing how the emulation of this game is going well, all the other screens are flowing well, great personal work.
![mupen64plus-gui 03-06-2018 05-29-06 avi_snapshot_00 09_ 2018 06 03_05](https://user-images.githubusercontent.com/30762805/40884817-150e57d4-66f1-11e8-8bc0-7ff3200af07c.png)

**Comment by olivieryuyu** [comment] 2018-06-03 11:29
do u have a savestate pls?

**Comment by GamingTVYT** [comment] 2018-06-03 12:18
olivieryuyu , Extract the Save state from the folder, I had to zip because the site did not accept the file format without zip.

[StarWars BFN.zip](https://github.com/gonetz/GLideN64/files/2065928/StarWars.BFN.zip)

**Comment by Diduz** [comment] 2018-06-04 08:49
Hello, I'm fairly new to the Nintendo 64 emulation scene. I backed the project on Indiegogo because I'm a big Indy fan and I wanted to preserve this interesting alternative version of Infernal Machine, The game runs and plays great on the latest version of Mupen64Plus and the last GlideN64 beta, but I am encountering an annoying graphical "issue". I guess the problem is related to my mipmapping setting. I don't know how to explain this and I had some difficulties in catching the issue in a screenshot. Textures on far walls change following a weird lateral/diagonal movement: in other words, the engine doesn't simply swap the different quality textures, there's strange a progressive "curtain effect" when the texture quality changes, I noticed that disabling the LOD emulation stops the "issue", but in that case I have the feeling the graphic quality drops a little. I'm sorry I couldn't be more precise: probably that strange mipmapping behaviour is ok with the game and I'm just not used to that. :-P
BTW, great work on this seemingly impossible emulation! Thanks again. :-)

**Comment by gonetz** [comment] 2018-06-04 14:09
@Diduz 
I think I know what you are talking about. First time I thought that it is a bug in our ucode implementation. However, LLE mode works the same. Moreover, I have real N64 and I see the same problem when I run Indy with it. It is less noticeable due to low resolution but it still there.
BTW, thanks for your support on Indiegogo!

**Comment by gonetz** [comment] 2018-06-04 17:26
Fixed the bug reported by amingTVYT :
https://github.com/gonetz/GLideN64/issues/1259#issuecomment-394146828

New beta build:
https://drive.google.com/file/d/10eURmfdD9NeJtXa_H0a824eC_78irooP/view?usp=sharing

**Comment by GamingTVYT** [comment] 2018-06-04 19:53
The bug in the scenario is fixed. Thanks. But now white particles appear when I shoot or I'm destroying something.
![mupen64plus-gui 04-06-2018 16-38-24 avi_snapshot_00 48_ 2018 06 04_16 41](https://user-images.githubusercontent.com/30762805/40938287-d54f6afc-6817-11e8-8c15-0266a7e77d6e.png)

**Comment by Diduz** [comment] 2018-06-04 22:33
@gonetz Sergey, I've created a video which shows what I was trying to explain. Look at the strange behaviour of mipmapping on walls! https://drive.google.com/file/d/1s9_9sLY4dFxEaZY8YJiulvZ8iqGlrTSt/view?usp=sharing

**Comment by gonetz** [comment] 2018-06-05 04:19
@Diduz Please give me savesvate from this place.

**Comment by gonetz** [comment] 2018-06-05 14:57
@GamingTVYT Yes, I made a mistake in previous fix. Corrected. New beta build:
https://drive.google.com/file/d/1wS2R2GG-Rwa02sUnHcK3v0SHyqfSE1iq/view?usp=sharing

**Comment by Diduz** [comment] 2018-06-05 19:46
@gonetz Okay, here's the savestate. ;-)
[Indiana Jones and the Infernal Machine (U) [!].zip](https://github.com/gonetz/GLideN64/files/2073744/Indiana.Jones.and.the.Infernal.Machine.U.zip)

**Comment by gonetz** [comment] 2018-06-06 03:47
Thanks! Yes, mip-mapping works incorrect there. It is an issue, but it is not HLE issue.

**Comment by Diduz** [comment] 2018-06-06 07:04
@gonetz Do you think there will be a way to fix that? :-)

**Comment by gonetz** [comment] 2018-06-06 08:36
I definitely will look at it, but I can't promise that it will be fixed. N64 mip-mapping is very hard to support on PC hardware.

**Comment by olivieryuyu** [comment] 2018-06-06 08:43
Ok then i guess it should be a new ticket for this issue.

**Comment by gonetz** [comment] 2018-06-06 09:44
Done: #1833

**Comment by GamingTVYT** [comment] 2018-06-06 14:06
Hello everyone, I found another glitch in (Star Wars BFN) now in the screen selection menu, I recorded a video showing the glitch. https://www.youtube.com/watch?v=fFKR-Im8cNo
SaveState if you want to check. 
[Star Wars Episode I - Battle for Naboo (U) [!].zip](https://github.com/gonetz/GLideN64/files/2076582/Star.Wars.Episode.I.-.Battle.for.Naboo.U.zip)

**Comment by fzurita** [comment] 2018-06-06 14:08
It's a cute issue. Set counter facto/Count per op to 1 fix the menus.

**Comment by GamingTVYT** [comment] 2018-06-06 14:14
@fzurita Corrected, thank you. 👍

**Comment by gonetz** [comment] 2018-06-06 15:31
@Diduz Could you give me savestate for Indiana from the same place but for Project64?

**Comment by Diduz** [comment] 2018-06-06 19:55
@gonetz I'm afraid I'm not able to get the game working under Project64. I get a black screen with the NTSC version. The unreleased PAL version starts, but it gets garbled after some screens. I'm using Project64 2.3.2.202.

**Comment by oddMLan** [comment] 2018-06-06 20:50
@Diduz

Indy/Naboo do not work under PJ64 2.3.x. Use Project 64 2.4.x.

You can get nightly builds at pj64-emu.com or emucr.

**Comment by olivieryuyu** [comment] 2018-06-06 21:32
here the savestate

[Indiana Jones and the Infernal Machine (E) (Unreleased).pj.zip](https://github.com/gonetz/GLideN64/files/2078227/Indiana.Jones.and.the.Infernal.Machine.E.Unreleased.pj.zip)

It seems incorrect in both LLE and HLE.

**Comment by gonetz** [comment] 2018-06-07 03:19
@olivieryuyu Thanks!

**Comment by gonetz** [comment] 2018-06-07 16:04
I fixed the issue mip-mapping. I noticed, that Project64 still have issues with this game: there are problems with shading, both in HLE and LLE. mupen64plus works just fine.

New beta build:
https://drive.google.com/file/d/10FoCieiX68XCij5Uw1pOx9J_P4Tbf91u/view?usp=sharing

**Comment by Diduz** [comment] 2018-06-07 20:11
@gonetz Works like a charm! :-) Indy seems perfect to me now. Thanks for all your work!

**Comment by nterry** [comment] 2018-06-07 22:29
> If you are really interested to do that, I guess your best chance would be indeed to dump the ucode and check the microcode implementation of Sergei

@olivieryuyu  Also, where can i find this Sergei and/or his ucode implementation?

**Comment by AmbientMalice** [comment] 2018-06-07 23:14
@nterry here are the commits for the HLE code https://github.com/gonetz/GLideN64/commits/indi_naboo

**Comment by gonetz** [comment] 2018-06-08 03:45
@nterry I have no skills in microcode decoding and can't help you.
As I know, the main tool olivieryuyu used is Project64 built-in debugger. Open Settings, select Advanced, check Enable debugger. You will get Debugger menu with plenty of tools. Debugger allows you to debug/dump both CPU and RSP commands.
I don't know, are there any instructions how to work with these tools. May be olivieryuyu will write some manual for ucode reverse engineering, but it will not be soon.

**Comment by olivieryuyu** [comment] 2018-06-08 07:20
@nterry 

I am afraid that using a microcode would be much more complex than deciphering it (I intend in the future to provide a short tutorial in this respect).

You would need to dump properly the ucode (both Nemu and PJ64 are unable to do it without bugs), then you would need to compile it with the N64 SDK (I would guess, I am not sure, that it does support the RSP asm, which is not at all standard) to get potentially a library usable for compiling a homebrew rom with this ucode. Of course  you would need to change the gbi.h to support the related commands (see and understand **in depth** Sergey implementation in this respect, it is not needed to decipher the ucode as such). Also as written by the devs, the OS of N64 had been modified, most likely to manage differently the segmentation of the memory and potentially to use COP1 for some operations (as the MP matrix calculated on the CPU side).

As you may understand, this is far from being a trivial exercise to do.

**Comment by LegendOfDragoon** [comment] 2018-06-08 08:13
>You would need to dump properly the ucode (both Nemu and PJ64 are unable to do it without bugs)

What is your method of dumping?

**Comment by olivieryuyu** [comment] 2018-06-08 10:36
You will need to go through the code and catch all overlays with PJ64. Then compare them with Nemu ucode extraction to get the full ucode dump. Then correct incorrect address (mostly offset) of some asm commands.

Gillou has potentially a way to do at once but I dunno how he does that.

**Comment by StenApp** [comment] 2018-06-08 10:55
@Gillou68310  Can you help us here? Do you have a hint how to get the ucode of a n64 game?
I capture a state with the debugger of nemu or pj64. In an earlier comment you see my dumps:
https://github.com/gonetz/GLideN64/issues/1259#issuecomment-348336023

**Comment by Jj0YzL5nvJ** [comment] 2018-06-08 12:07
> You will need to go through the code and catch all overlays with PJ64. Then compare them with Nemu ucode extraction to get the full ucode dump. Then correct incorrect address (mostly offset) of some asm commands.

That's more similar to recovering the DNA of a fossil, but without worrying about DNA contamination from third parties and bacteria.

**Comment by Gillou68310** [comment] 2018-06-08 14:02
> @Gillou68310 Can you please help us here? Do you have a hint how to get the ucode of a n64 game?

Yes I wrote a bit of code to dump the ucode text and data sections directly from rdram provided that TASK_UCODE_SIZE and TASK_UCODE_DATA_SIZE have correct values, otherwise I just dump 4096 bytes.

But you won't be able to build a ROM with just the text and data sections. The "makerom" utility from the SDK requires ucodes in ELF format. A tool like "rsp2elf" could potentially do the job but it's not included in the SDK. Also since the application code can reference the RSP text and data sections, a symbol file will be required.

**Comment by gonetz** [comment] 2018-06-16 11:48
Merged to master.

**Closed by gonetz** 2018-06-16 11:48 UTC
Labels: Priority-High
