### ISSUE TITLE
MK64 Menus misaligned?

### ISSUE THREAD

**Issue by jfields687** [gonetz/GLideN64#607] opened 2015-07-07 16:46 UTC
Something in the 2015/07/04 commit has MK64 and possibly a few other game with misaligned textures. I used default settings and tried changing them to no avail.

You can see it around "Push Start"
![mk1](https://cloud.githubusercontent.com/assets/12734891/8551619/c5cbc3fe-24a5-11e5-921f-ed10a639ebcf.png)
More obvious here
![mk2](https://cloud.githubusercontent.com/assets/12734891/8551623/cca59100-24a5-11e5-91c6-1da9d3819990.png)
![mk3](https://cloud.githubusercontent.com/assets/12734891/8551628/d1ce33f8-24a5-11e5-8c16-4407d6bf6785.png)
Very minor problem in Paper Mario
![pm](https://cloud.githubusercontent.com/assets/12734891/8551630/d6b8b85c-24a5-11e5-9629-e4e4f7a8b88d.png)

**Comment by Predator82Germany** [comment] 2015-07-07 16:56
Can confirm

**Comment by thecoreyburton** [comment] 2015-07-08 09:34
The menu issue looks to be the same as #540

**Comment by jfields687** [comment] 2015-07-08 13:13
That was the first thing I did was try 640*480 and it still does it. It definitely looks related though. Thanks

**Comment by standard-two-simplex** [comment] 2015-07-08 15:54
320*240 does not have the issue. So it seems related. More than being a regression of that commit, it seems it made the other bug visible in this game, I believe.

**Comment by jfields687** [comment] 2015-07-08 16:05
Yep, I can confirm it looks just fine at 320*240. Definitely something to do with up-scaling to higher resolutions.

**Comment by Predator82Germany** [comment] 2015-07-08 16:08
But wasn´t before some commits

**Comment by purplemarshmallow** [comment] 2015-07-14 11:31
regression from https://github.com/gonetz/GLideN64/commit/c50b3c8c1d2a59a1bb99623e725ae02c98d52bc0

**Comment by gonetz** [comment] 2015-07-23 10:33
https://github.com/gonetz/GLideN64/commit/70c4941fb9aac0370935ce6ff3762f9434664c3a

**Comment by jfields687** [comment] 2015-07-23 13:51
Thanks Gonetz! All fixed except one little thing...
![mk](https://cloud.githubusercontent.com/assets/12734891/8851947/5f48b04c-3120-11e5-95e0-e0c61c843dcc.png)

**Comment by Predator82Germany** [comment] 2015-07-23 14:20
Dod you bring revisions like with Glide64 on GoogleCode?

**Comment by gonetz** [comment] 2015-07-24 06:56
@jfields687 - it is side effect of fix for issue #506. May be later I find a way to fix both issues.

@Predator82Germany - which revisions you are talking about? Do you mean binaries?

**Comment by Predator82Germany** [comment] 2015-07-24 07:08
Yes

**Comment by gonetz** [comment] 2015-07-26 14:52
Current master:
https://drive.google.com/file/d/0B0YqMPjGo3B2elhEeXJFLWJGYk0/view?usp=sharing

**Comment by Predator82Germany** [comment] 2015-07-26 15:21
OpenGL Error: invalid value
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/8894548/cc923b0e-33ba-11e5-81d9-6d2d09e25654.jpg)

**Comment by jfields687** [comment] 2015-07-26 15:38
No problems here. When did the error come up?

**Comment by Predator82Germany** [comment] 2015-07-26 15:40
Starting a ROM

**Comment by theboy181** [comment] 2015-07-26 18:45
@gonetz 
I cant seem to get HD textures working with the last post. Any ideas?

**Comment by baptiste0602** [comment] 2015-07-26 22:01
Same problem as Preddator. Nvidia only issue ?

**Comment by jfields687** [comment] 2015-07-26 22:03
Nope, I have a 660GTX. Maybe a C++ redistribute needs updated?

**Comment by baptiste0602** [comment] 2015-07-28 17:53
This issue happen in 1080 Snowboarding too : 
![image](https://cloud.githubusercontent.com/assets/11183826/8939019/5c1ad10c-3562-11e5-9a31-beeceb611351.png)

**Comment by jfields687** [comment] 2015-07-29 04:33
Ok, I crashing issue, but only when switching to another rom after I have one already opened. I am using the latest dev build of PJ64

**Comment by oddMLan** [comment] 2015-08-16 18:25
I guess the textures misalignment issues in many games is one of those unfortunate issues that has to be approached with a hack, due how to the game engine handles things and was not made in mind to be displayed at higher resolutions.

Here's how the PCSX2 team approached this; maybe you will get an idea of how to implement this in GLideN64's code
http://pcsx2.net/269-major-gsdx-progress-monthly-reports.html
http://pcsx2.net/developer-blog/267-explanation-hacks-needed-for-upscaling-glitches.html

**Comment by tony971** [comment] 2015-09-24 17:11
This also occurs in the intro of Mega Man 64 (U). I would take a look at @oddMLan 's suggestion and copy how the pcsx2 team handled it.

**Comment by purplemarshmallow** [comment] 2015-09-24 18:11
This is a problem with texture clamping not sure if upscaling is a problem here. However #450 seems to be a problem with upscaling at 640x480 this problem disappears. z64gl seems to work correctly in all these cases maybe it uses a hack?

**Comment by oddMLan** [comment] 2019-11-05 12:21
fixed with native texrects
should be forced in the ini

once that is added should this be closed? or is it something that shouldn't be happening without native texrects?

**Comment by gonetz** [comment] 2019-11-05 15:56
No, native res texrects were initially designed to fix texture issues in MK64.
I'll enable that option in custom ini.
@fzurita please check how MK64 will run with that option on Android devices.

**Closed** 2019-11-05 16:01 UTC
