### ISSUE TITLE
[Regression] [NEON] CBFD Rare logo no longer shiny gold color

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1280] opened 2016-12-03 22:08 UTC
Just tried the latest version. The Rare logo is no longer gold shiny color. See this screenshot:

![conker_bfd-000](https://cloud.githubusercontent.com/assets/11581687/20862514/14c1b96c-b97b-11e6-9efe-74878959f0ed.png)

**Comment by AmbientMalice** [comment] 2016-12-03 23:26
This might have been fixed by https://github.com/gonetz/GLideN64/commit/74144d6126e846f69e102fa6c618aa9c3c109945

**Comment by fzurita** [comment] 2016-12-03 23:30
Hmmm, interesting, I'll try that one and report back.

**Comment by fzurita** [comment] 2016-12-03 23:43
Just tried that commit. There was no improvement.

**Comment by loganmc10** [comment] 2016-12-04 03:14
I think this only affects mobile, I was trying this on my laptop earlier today and it looked right, but someone might have to confirm.

@fzurita maybe try the full OpenGL profile? Or maybe it's a neon thing

**Comment by fzurita** [comment] 2016-12-04 03:17
Same issue with the full OpenGL profile. I'll attempt to disable neon next,

**Comment by gonetz** [comment] 2016-12-04 04:50
Desktop build is ok. 74144d6 is not related to the problem, because LookAt is enabled for the logo.

**Comment by gonetz** [comment] 2016-12-04 04:54
@fzurita please try to locate regression commit. Is it 6af6e2c17, or something else?

**Comment by retrobenny** [comment] 2016-12-04 04:58
Is shader storage on? If used,try deleting the shader cache file maybe.
I haven't booted Conker lately on account of being more focused on Smash Bros. codes and other things.

**Comment by fzurita** [comment] 2016-12-04 05:04
Shader storage is off. I will locate the commit that broke it tomorrow.

**Comment by oddMLan** [comment] 2016-12-04 10:25
using build 7d4c5fc , no issues
![gliden64_conker_bfd_000](https://cloud.githubusercontent.com/assets/7278372/20865482/2eca7668-b9d1-11e6-8286-d29252b7d386.png)
looks pretty shiny to me
reset settings & deleted shader cache

**Comment by fzurita** [comment] 2016-12-04 16:10
Ok, it is the neon version that is breaking things. When I tested without Neon, I forgot to remove everything NEON from the build.

fc0c77a07bb7eb73e097462969773b225905c6a4 is what breaks it. I'll try to figure out what's wrong with it.

**Comment by fzurita** [comment] 2016-12-04 17:11
This is amusing, gcc is somehow optimizing away the neon code. The second I add logging to try to capture the result of the neon operation, the graphics look correct....

**Comment by fzurita** [comment] 2016-12-04 19:48
Ok, I found the problem... NEON doesn't like the NANs numbers produced by CBFD.

**Closed** 2016-12-05 16:57 UTC
