### ISSUE TITLE
Major League Baseball: incorrect graphic in game + black intro & title screen

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#146] opened 2014-11-15 06:35 UTC
In game, graphic issue

![screen78](https://cloud.githubusercontent.com/assets/8987490/5056794/3b1e83a4-6c9a-11e4-9353-2945027ad987.jpg)

solved in glide64 here: https://code.google.com/p/glidehqplusglitch64/source/detail?r=53&path=/trunk/Glide64/rdp.cpp

Title screen

![dd](https://cloud.githubusercontent.com/assets/8987490/5056781/b857acd4-6c99-11e4-93f8-1ffc1e544402.jpg)

**Comment by gonetz** [comment] 2015-04-03 17:38
No. Fixed point arithmetic magic needed to calculate texrect texture coordinates here.

**Comment by olivieryuyu** [comment] 2015-04-03 17:46
magic? :)

**Comment by olivieryuyu** [comment] 2015-07-27 20:02
no intro as well, crash with fb on

**Comment by olivieryuyu** [comment] 2016-01-22 11:45
![nearly](https://cloud.githubusercontent.com/assets/8987490/12509862/ec06b2f2-c105-11e5-9ee4-fe655e54cde4.png)

Ok it is nearly working with the syn emu fb. Can't it be fixed?

**Comment by olivieryuyu** [comment] 2016-04-09 14:54
the text are correct with commit 

https://github.com/gonetz/GLideN64/commit/4484bb5623b61825f41246810fd2587dcf0c81ae

What was fixed with this one? it seems a lot of games benefits from it (not winback however)

**Comment by gonetz** [comment] 2016-04-09 16:34
>What was fixed with this one?  

texture coordinates in texrect. Second coordinate used +1, I replaced it by +dsdx, where dsdx defines the step in texture coordinate when x coordinate is increased by 1. dsdx is usually 1, but not always.

**Comment by olivieryuyu** [comment] 2017-09-16 09:00
the solution for the public was solved by Angrylion and implemented in our good old Glide64. It is a RDP bug.

**Comment by gonetz** [comment] 2017-09-16 10:34
Not a bug, but fixed point math magic.

**Comment by AmbientMalice** [comment] 2017-09-16 10:36
>Not a bug, but fixed point math magic.

Does that mean this bug stems from GLideN64 using floating point math?

**Comment by gonetz** [comment] 2017-09-16 11:28
GLideN64 does not use fixed point math, and this causes particular issue in particular game. Easy to fix, but can't find time to do it.

**Comment by olivieryuyu** [comment] 2017-11-08 08:14
i have no mire graphics in intro and title screen with the last YUV changes.

**Comment by gonetz** [comment] 2017-11-08 14:54
I'll check it, thanks

**Comment by gonetz** [comment] 2017-11-08 17:05
@olivieryuyu  I just checked: current master has no difference from Public Release 2 on this game for me.

**Comment by olivieryuyu** [comment] 2017-11-08 18:08
hmm right but how did i get the screen from 22 Jan 2016?

**Comment by gonetz** [comment] 2017-11-10 15:20
> how did i get the screen from 22 Jan 2016?

Current master works the same.

**Comment by gonetz** [comment] 2017-11-20 03:26
"Major League Baseball: incorrect graphic in game" this issue is fixed with https://github.com/gonetz/GLideN64/commit/32e0d17468b1840acdc16e5da776ef82025df54a

black intro & title screen is another issue.

**Closed by gonetz** 2017-11-20 03:26 UTC
