### ISSUE TITLE
RTL World League Soccer (G) - Missing Textures

### ISSUE THREAD

**Issue by Predator82Germany** [gonetz/GLideN64#394] opened 2015-04-13 14:41 UTC
![unbenannt](https://cloud.githubusercontent.com/assets/6679921/7117872/e9dec76a-e1fb-11e4-99dc-a7d30c5872da.jpg)

**Comment by Predator82Germany** [comment] 2015-04-20 12:40
Other regions of the game with same problem
Mia Hamm Soccer
Michael Owens WLS 2000
Telefoot Soccer 2000

**Comment by olivieryuyu** [comment] 2017-09-29 11:19
duplicate of https://github.com/gonetz/GLideN64/issues/210

@gonetz 

can it be closed?

**Closed** 2017-09-29 12:06 UTC
Labels: duplicate
