### ISSUE TITLE
On GLES2.0, Enabling FBE displays a black screen in all games while Disabling it causes Undisplayed graphics

### ISSUE THREAD

**Issue by mckimiaklopa** [gonetz/GLideN64#1045] opened 2016-07-01 21:52 UTC
Enabling FBE causes a black screen in all games.

Disabling it will either
A) still display a black screen
B) Show only some textures, black or white.

Mario 64 has white textures on the logo and save screen but has no ingame graphics.
Mario kart only displays graphics during the race main menu screen

My device is a Samsung GT-I9082 but based on this http://www.paulscode.com/forum/index.php?topic=8820.30 , it seems to hapoen on other devices too

**Comment by loganmc10** [comment] 2016-07-02 03:27
If you are able to compile and run GLideN64 with Debugging on you will probably see some kind of error in gliden64.log or an assert will trigger, I'm not sure how that works on Android devices @fzurita , but typically i don't think a fully black screen will happen without some kind of error being triggered in debug mode

**Comment by fzurita** [comment] 2016-07-02 11:42
I may have to make a build with debug mode enabled to pass around to try to debug this kind of error

**Comment by fzurita** [comment] 2016-07-07 04:15
That phone has a VideoCore GPU, same type as Raspberry pi, but I bet the drivers are way outdated since it's samsung.

**Comment by fzurita** [comment] 2016-07-07 04:17
Good news, I can reproduce this in my old Android phone, and I'm pretty sure this was working correctly before.

**Comment by loganmc10** [comment] 2016-07-07 04:19
I don't know if this is the same issue, but after the new blending code I got a black screen on the Raspberry Pi. I documented it here:

https://github.com/gonetz/GLideN64/issues/982

And here is the pull request that fixed it:
https://github.com/gonetz/GLideN64/pull/993

It doesn't like variable indexing, so I had to make that ugly patch.

Basically look at the stuff wrapped inside #ifdef VC and #ifndef VC in ShaderUtils.cpp, that might help (but I could be completely wrong, I had a black screen even with FBE disabled.

**Comment by loganmc10** [comment] 2016-07-07 04:22
@gonetz I should point out, that when you run GLideN64 through apitrace on a device with Intel Graphics you get this warning
```Unsupported form of variable indexing in FS; falling back to very inefficient code generation```

So it seems like other drivers tolerate variable indexing, but they don't like it either.

**Comment by fzurita** [comment] 2016-07-09 04:27
Shaders are compiling fine on my old GLES 2.0 device. I found the commit that broke my device. It was this one:

https://github.com/gonetz/GLideN64/commit/b7369e905ee483cba40d5a710d2fa7f476dd5813

@gonetz Everything I read online tells me that discards are a horrible performance penalty for tile renderers. For example, see here: http://cdn.imgtec.com/sdk-documentation/PowerVR+Performance+Recommendations.The+Golden+Rules.pdf and search for discard.

**Comment by loganmc10** [comment] 2016-07-09 05:59
@fzurita that is easy enough to test, you can just remove all the "discard" lines from the code and run it. I did it and it did seem to provide a modest performance increase on the Raspberry Pi (FBE disabled during testing), although I need to get the mupen64plus OSD working on the Raspberry Pi so I can be a bit more scientific about these things...

**Comment by gonetz** [comment] 2016-07-09 13:53
@fzurita I don't have time to read the articles now, I'll do it later.
Anyway - what is alternative for 'discard' ?
If alpha test failed, the fragment calculation must finish without writing of any results: both color and depth buffer must me untouched.

**Comment by fzurita** [comment] 2016-07-09 15:27
Both articles say that alpha blending is the other option. This can be done by calling glEnable(GL_BLEND) and setting the appropriate alpha for the fragColor.

I did try this and it didn't fix the issue though for the device.

**Comment by gonetz** [comment] 2016-07-09 16:03
> Both articles say that alpha blending is the other option. This can be done by calling glEnable(GL_BLEND) and setting the appropriate alpha for the fragColor.

It will not help. Pixel will be invisible, but its z-value will be stored in depth buffer, which will cause glitches.

**Comment by fzurita** [comment] 2016-07-09 16:13
There is apparently a solution for that. Looks simple:

https://www.sjbaker.org/steve/omniv/alpha_sorting.html

But maybe I'm misinterpreting.

**Comment by gonetz** [comment] 2016-07-09 16:48
In OpenGL ES 2.0 glAlphaFunc isn't available, you have to implement it in a fragment shader.

**Comment by fzurita** [comment] 2016-07-10 02:57
Ok, back to what actually broke my device. It was the change to this method:

https://github.com/gonetz/GLideN64/blob/b7369e905ee483cba40d5a710d2fa7f476dd5813/src/GLES2/GLSLCombiner_gles2.cpp#L488

If I revert that to the previous version, my old device works fine.

**Comment by fzurita** [comment] 2016-07-10 04:36
Having no discards in the GLSL code triples performance!

**Comment by loganmc10** [comment] 2016-07-10 07:06
Apple has some good guidelines that apply to shaders on GLES devices:

https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html#//apple_ref/doc/uid/TP40008793-CH7-SW11

From what I read, if statements in general aren't great in a fragment shader, and if it's possible it can be better to just have different shaders handle the different scenarios, especially on GLES2 devices.. It also says that branching based on a value computed inside the shader is especially slow. In your if statement I believe that is true for alpha2, alphaValue, and alphaTestValue.

**Comment by fzurita** [comment] 2016-07-10 11:28
Yeah, that's a good point but that would mean switching shaders at a very high rate. This is really bad for GLES 2.0 since it has no shader cache.

**Comment by loganmc10** [comment] 2016-07-10 15:04
If you want to see what it might be like with optimized GLSL code you could take a look at https://github.com/aras-p/glsl-optimizer.

I got it working with GLideN64, you can see the changes I made here (only did it for GLES2 for testing):
https://github.com/loganmc10/GLideN64/commit/9bc63a821d8ba06071f5e81104d44cf243f3d195

The performance difference on the Pi was very noticeable. The "Statue" level on GoldenEye used to be constantly choppy and now it's smooth. The only thing I noticed is that the explosions were green, not their regular orange. Other games I tested looked normal. It's probably not the kind of thing that would be easy to integrate into GLideN64, but it can help test how optimized the current GLSL code is.

I don't know how hard it would be to get working on Android, it seems that some people have got it working (https://github.com/aras-p/glsl-optimizer/issues/127)

**Comment by fzurita** [comment] 2016-07-10 15:36
Actually, I did make am attempt at being this library working. And it seemed like I got it to work, but it produced a lot of corrupt graphics, so I gave up on it.

**Comment by fzurita** [comment] 2016-07-10 20:29
@mckimiaklopa Please try this build with frame buffer emulation disabled:

https://drive.google.com/file/d/0B57Ioy26LWegcnRfd2FOU0JBQ1E/view?usp=sharing

Does it display graphics correctly? I'm sure speed won't be that great though.

**Comment by fzurita** [comment] 2016-07-11 05:24
So replacing:
```
	_strShader.append(
		"  if ( (uCvgXAlpha != 0 && alpha2 < 0.125) || ( uEnableAlphaTest != 0 && alphaValue < alphaTestValue) ) discard; \n"
	);
```

with 

```
	_strShader.append(
		"  if ( uCvgXAlpha != 0 || uEnableAlphaTest != 0) discard; \n"
	);
```

double the frame rate at the cost of incorrect graphics.

**Comment by gonetz** [comment] 2016-07-11 05:37
Double?!
I'm starting to think about "lite" version of the plugin: without alpha test, with old blending method etc.

**Comment by fzurita** [comment] 2016-07-11 05:48
That may not be a bad idea. Unless we can figure out improve the performance of the new blending on older devices.

**Comment by gonetz** [comment] 2016-07-11 16:01
> If we were to use alpha blending instead of alpha test, then the above if statement could be replaced with some math instead, which would be a lot faster.

No, it could not. Even if we omit the fact that blending is a bad replacement for discard, blending can be used to make pixel invisible. However, condition, which pixels should be invisible still depends on pixel's alpha. It should be something like this:
```
    _strShader.append(
        "  if ( (uCvgXAlpha != 0 && alpha2 < 0.125) || ( uEnableAlphaTest != 0 && alphaValue < alphaTestValue) ) alpha2 = 0.0; \n"
    );
```

**Comment by fzurita** [comment] 2016-07-11 17:22
What about this using alpha blending:

```
    int alpha2_125Test = int(alpha2/0.125);
    int alphaValueTest = int(alphaValue/alphaTestValue);

    alpha2 = alpha2 - clamp(uCvgXAlpha, 0, 1)*clamp(alpha2_125Test, 0, 1)*alpha2;
    alpha2 = alpha2 - clamp(uEnableAlphaTest, 0, 1)*clamp(alphaValueTest, 0,1)*alpha2;
```

**Comment by fzurita** [comment] 2016-07-11 19:26
I have yet to try this on my device. I wrote that while I'm still here at work. I think it will make my device faster though.

**Comment by loganmc10** [comment] 2016-07-11 19:30
I just tested it with Super Smash Bros and there are black boxes around things, I assume that is the alpha not working correctly?

**Comment by fzurita** [comment] 2016-07-11 19:34
You have to enable alpha blending. I think it's getting disabled at times.

**Comment by fzurita** [comment] 2016-07-11 23:09
I did attempt this in my old device and it double the frame rate. But I don't think I have the GL_BLEND set correctly since I'm not getting all transparencies working correctly.

**Comment by gonetz** [comment] 2016-07-12 04:34
> What about this using alpha blending?

Interesting trick.

> It looks like I need to set the correct glBlendFunc as well. I don't have the understanding to do that.

That can be hard. glBlendFunc is set in OGLRender::_setBlendMode(). It is already correct. If you will change it, you will break things. It is another reason why blending is bad replacement for discard.

**Comment by gonetz** [comment] 2016-07-12 15:25
There is another way to improve performance. Currently all shaders contain alpha-test code. It is activated via uniform variable. I can add this code only when game enables alpha-test. That is generally there will be two or more variants of the same shader: with and without alpha test. Overheads on shader compilation and video memory - speed boost on shaders without alpha test code.

BTW, if we rewrite this part
```
         if ( (uCvgXAlpha != 0 && alpha2 < 0.125) || ( uEnableAlphaTest != 0 && alphaValue < alphaTestValue) ) discard;
```
    );
as 
```
         if ( (uCvgXAlpha != 0) {
            if (alpha2 < 0.125)
               discard;
          }
          if ( uEnableAlphaTest != 0) {
              if (alphaValue < alphaTestValue) 
                 discard;
          }

```
will not it improve performance as well? alpha2 and  alphaValue shoud be tested only when corresponding uniforms are not zero. I know, shaders work not as usual program, and most likely it will not help, but at least it is worth to check and know for sure.

**Comment by fzurita** [comment] 2016-07-12 15:36
I did try something similar to that and it didn't help. I thought it would had helped too. Also, there is a bug in older Adreno drivers that don't allow more than 1 discard per shader program.

**Comment by gonetz** [comment] 2016-07-12 15:37
ok, thanks.

**Comment by fzurita** [comment] 2016-07-13 03:39
Ok, I made some modifications, and this double my performance over the original input!

```
  lowp float alpha2_125Test = floor(alpha2/0.125);
  lowp float alphaValueTest = floor(alphaValue/alphaTestValue);
   alpha2 = alpha2 - float(uCvgXAlpha)*alpha2_125Test*alpha2 -  float(uEnableAlphaTest)*alphaValueTest*alpha2;
  alpha2 = clamp(alpha2, 0.0, 1.0);
```

So if blending could be used, it can double performance.

**Comment by gonetz** [comment] 2016-07-13 09:00
I guess such performance boost can be seen only on really old devices. What's about newer ones?

**Comment by Sarkie** [comment] 2016-07-13 09:11
I have a Moto G with Qualcomm Adreno 305, 450 MHz, If you want me to test if there's a build?

**Comment by fzurita** [comment] 2016-07-13 10:57
These optimizations leave the plugin with broken graphics. I'm just making them to see the potential improvements in performance that alpha blending could give to older devices.

**Comment by fzurita** [comment] 2016-07-13 11:00
I'm going to test these changes on my newer phone to see what they do to performance later tonight.

**Comment by fzurita** [comment] 2016-07-13 12:41
I just tried the same thing on my newer Adreno device and it makes **zero** performance difference there.

**Comment by gonetz** [comment] 2016-07-13 15:38
I tested on my Note2 (Mali 400 GPU) - no difference with current master.

**Comment by fzurita** [comment] 2016-07-13 15:40
So it must only affect specific devices. I'm going to try it in my PowerVR device later tonight. I read strong warnings about using discard with them.

**Comment by loganmc10** [comment] 2016-07-14 15:57
So what actually fixed the black screen/undisplayed graphics, what it using ShaderUtils_VC.h?

**Comment by fzurita** [comment] 2016-07-14 15:58
Yes and only having 1 discard operation per shader code.

**Comment by loganmc10** [comment] 2016-07-14 20:49
@fzurita with regards to this line:
```
if (uCvgXAlpha != 0 && alpha2 < 0.125) discard;
```
@gonetz asked if this would give better performance:
```
if ( (uCvgXAlpha != 0) {
            if (alpha2 < 0.125)
               discard;
          }
```

And I you said it didn't. I believe that is because GLSL compilers automatically do &&'ing if there are 2 if statements one after the other (the GLSL Optimizer does this, which is based off of Mesa), effectively reversing that change, but if you do something like this:

```
if (uCvgXAlpha != 0) {
  lowp float testing = clamp(alpha2,0,0.125);
  if (testing != 0.125) discard;
}
```

Then it does it properly. I think I did the clamp() correctly? I'm curious if that improves performance on your older device, since it won't be evaluating the "shader computed" variable as much.

**Comment by gonetz** [comment] 2016-07-15 03:49
> I don't think it's worth adding alpha blending for an old obsolete device.

Well, shader based alpha blending can be made optional with old blending method as the alternative.

**Comment by fzurita** [comment] 2016-07-17 04:02
>  I believe that is because GLSL compilers automatically do &&'ing if there are 2 if statements one after the other (the GLSL Optimizer does this, which is based off of Mesa), effectively reversing that change

Normally, there are short circuit mechanisms so that if an boolean operation evaluates up to a point where it the outcome of the operation cannot change even if the rest operation is performed, then the rest of the operation won't be performed. See this for a more detailed example: http://www.mathworks.com/help/matlab/ref/logicaloperatorsshortcircuit.html?requestedDomain=www.mathworks.com

This has applied to every programming language I have used so far. I would be surprised if matlab didn't implement boolean short circuits.

**Comment by fzurita** [comment] 2016-07-17 04:05
I think I'm going to work on adding the old blending back as a configuration parameter.

**Comment by loganmc10** [comment] 2016-07-17 04:38
I think the difference with GLSL is that (I don't know if this is true for every piece of hardware) based on what I read, most GPU's will pre-compile the shader based on the uniform values, so they get "hard-coded" into the shader for that run, until the uniform changes. So if you have an if statement with just a uniform in it, and that statement evaluates to false, it just skips over that block of code. However if there is a "shader computed" value in the if statement, it needs to evaluate that statement every time when it gets there.

But I guess it goes back to what you're saying, I don't know if every GPU would be smart enough to short circuit that if statement. I thought maybe it would fix your "double discard" issue, but I guess that's kind of a shot in the dark.

**Comment by fzurita** [comment] 2016-07-17 04:49
Gotcha. I'm think about adding 3 different blending modes. Here is what I think they should be:
* Accurate ( using code after this commit: 0ad53ad0e8a551e89563b03c279e1fb0ac4d9b86)
* Fast ( using code before this commit: 0ad53ad0e8a551e89563b03c279e1fb0ac4d9b86)
* Accurate with device fix ( using code after commit 0ad53ad0e8a551e89563b03c279e1fb0ac4d9b86 but with the ShaderUtils_VC.h implementation of the GLSL code)

**Comment by loganmc10** [comment] 2016-07-17 05:12
Well something to try would be to compile different shaders based on the different "if" options instead of branching based on the uniforms.  You could also try commenting out these lines:

https://github.com/gonetz/GLideN64/blob/master/src/ShaderUtils.cpp#L319-L322

To see if the variable indexing is causing the performance problems (commenting out those lines caused messed up graphics obviously)

**Comment by fzurita** [comment] 2016-07-17 05:21
Yeah, compiling different shaders depending on the different If options maybe worth trying for performance. 

The bad thing about GLES 2.0 though is that there is no shader cache, so each time we switch shaders, the GLSL needs to be recompiled. These switches may not happen very often though. It's worth trying.

In my old device, variable indexing is causing incorrect graphics. If I switch the variable indexing for the ShaderUtils_VC.h version, graphics look correct, but frame rate is reduced by a good amount. I will try completely commenting out those lines to see how much of a performance hit they are.

**Comment by gonetz** [comment] 2016-07-17 05:45
https://github.com/gonetz/GLideN64/commit/cd1b134ddc188c61c9b230669588502d62b31d6b

**Comment by gonetz** [comment] 2016-07-17 17:10
@fzurita @loganmc10 please check my legacy blending branch - is it worth to keep that option for slow devices, which have problems with new blending?

**Comment by fzurita** [comment] 2016-07-17 20:40
I will try this tonight. If the option to enable legacy blending is enabled/disabled, will the shader cache be cleared when switching?

**Comment by gonetz** [comment] 2016-07-18 01:54
New option: enableLegacyBlending. I've added that option for list of options checked by shader cache, thus the cache must update when the option switched.

**Comment by fzurita** [comment] 2016-07-18 01:58
Gotcha, see it now in ShaderCombiner::getShaderCombinerOptionsSet

**Comment by gonetz** [comment] 2016-07-18 03:55
I forgot to mention, that legacy blending option includes only "legacy blending", without hacks for special blending modes. Thus, several games,  e.g Mace, Perfect Dark, Bomberman, will have various glitches. This option is for speed.

**Comment by loganmc10** [comment] 2016-07-18 04:01
This works very well on the Raspberry Pi, there is a noticeable improvement in Goldeneye and Perfect Dark, which are both games that have slowdowns for me. I'm okay with some graphical glitches if it improves the speed. For devices that "can't keep up" like GLES2 devices there is going to have to be a trade off between accuracy and speed

**Comment by fzurita** [comment] 2016-07-18 04:19
This is a very big speed up in my old device.

**Comment by gonetz** [comment] 2016-07-18 04:22
Thanks for the info. I'll put it to master then.

**Comment by fzurita** [comment] 2016-07-18 04:26
This is a HUGE speed up for PowerVR devices.

**Comment by fzurita** [comment] 2016-07-18 05:11
I updated the master branch of Mupen64plus-AE with this change:

https://github.com/mupen64plus-ae/mupen64plus-ae

**Comment by fzurita** [comment] 2016-07-20 04:31
I'm getting reports that this is fixing the issues with older devices, so I think this should be closed.

**Comment by gonetz** [comment] 2016-07-20 04:47
Ok

**Closed by gonetz** 2016-07-20 04:47 UTC
