### ISSUE TITLE
Resident Evil 2 missing backgrounds

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#797] opened 2015-11-17 22:27 UTC
The backgrounds need CopyFromRDRAM. I tried to fix it up but CopyFromRDRAM is very broken and unstable in this game. Everything reders in the bottom left corner. Reminds me of #603 . Must be the same problem.
![2](https://cloud.githubusercontent.com/assets/7283660/11226784/6a660f4c-8d82-11e5-9f78-5918e5cca3e2.jpg)
![1](https://cloud.githubusercontent.com/assets/7283660/11226785/6d814368-8d82-11e5-8930-062ebc79baff.jpg)
![3](https://cloud.githubusercontent.com/assets/7283660/11226788/7068682c-8d82-11e5-957d-4c3324612fb6.jpg)

**Comment by AmbientMalice** [comment] 2015-11-17 23:06
But how did the other plugins render RE2? They weren't doing anything so drastic as copying from RDRAM, were they?

**Comment by purplemarshmallow** [comment] 2015-11-18 00:00
The backgrounds and the text/logos are drawn separately. Somehow they need to be assembled to get the full image. I tried to copy everything to RDRAM and then read the full image from RDRAM. Not sure how the other plugins work.

**Comment by gonetz** [comment] 2015-11-18 03:52
>The backgrounds need CopyFromRDRAM.

No. The game uses standard background commands from S2DEX ucode.

**Comment by AmbientMalice** [comment] 2015-11-18 04:53
![glide64_resident_evil_ii_01](https://cloud.githubusercontent.com/assets/10704701/11232924/b1241f06-8e03-11e5-9a29-8b6d47c4272b.png)
You might be barking up the wrong tree with RE2 and framebuffering. Glide64 renders the game okayish with the framebuffer completely disabled. There's an underlying texture problem, I think, that framebuffer RDRAM stuff sidesteps slightly -- but that's not a real solution. I think the fact that the spinning N64 logo doesn't render in HLE but renders in LLE is significant. Also, the fact the game renders garbage without the FB enabled.

**Comment by Gillou68310** [comment] 2015-11-18 10:24
> No. The game uses standard background commands from S2DEX ucode.

@gonetz is right, I made a few debugging on this game a while back and I remember backgrounds were drawn via gSPBgRectCopy.

BTW how did you get this results with gliden64? Using m64p + rsp-cxd4 in both HLE+LLE I only have the spinning logo + intro video, everything else is just a black screen (menu+ingame).

I think everybody already know that, but in order to have backgrounds with glide64mk2 you'll need rsp-cxd4 in HLE mode (DisplayListToGraphicsPlugin = True). Unfortunately depth is broken and 3D models are always drawn over 2D background.

> The game ROM contains pre-rendered depth buffer data for each background. That depth buffer data is copied into RDRAM and each frame it is rendered as 16bit texture into a color buffer which then is used as the depth buffer. To emulate it on PC hardware the depth buffer data must be converted into format of PC depth buffer and copied into PC card depth buffer.

@gonetz I saw this on your blog, how is the pre-rendered depth buffer data retreived?

**Comment by gonetz** [comment] 2015-11-18 11:44
depth background is copied the same way as color one, with bg command.

**Comment by gonetz** [comment] 2015-11-18 11:49
> Unfortunately depth is broken

AFAIR, it did not work with Glitch64, the default wrapper. Only zeckensack's glide wrapper had necessary functionality. So, it is not broken, just not implemented.

**Comment by Gillou68310** [comment] 2015-11-18 13:39
Thanks for the all the infos.

Using an external wrapper is not an option right now with glide64mk2.
How was this done in original Glide64, did you add a specific lib when linking?

Also do you have an idea of what is missing in Glitch64 wrapper?

> So, it is not broken, just not implemented.

Sorry for the wrong choice of word ;-)

**Comment by Gillou68310** [comment] 2015-11-18 14:05
> How was this done in original Glide64, did you add a specific lib when linking?

Nevermind you used glide3x.lib

**Comment by Gillou68310** [comment] 2015-11-18 14:13
Hum I get ERROR instead of EVOODOO from grGetString

**Comment by gonetz** [comment] 2015-11-18 14:57
ERROR with zeckensack's wrapper? The wrapper works fullscreen only. If it still works of course.

**Comment by Gillou68310** [comment] 2015-11-18 15:00
It still works but using GR_EXTENSION or GR_HARDWARE returns ERROR string

**Comment by Gillou68310** [comment] 2015-11-18 15:01
I override the function but I'm unsure of what extensions are available in the wrapper

**Comment by Gillou68310** [comment] 2015-11-18 15:26
Ok I finally managed to do the test with glide64mk2 + zeckensack's wrapper and you were right, depth is working perfectly fine here, I just need to find were to look in Glitch64 wrapper in order to fix this, I wished zeckensack had published the source code back then ;-)

**Comment by purplemarshmallow** [comment] 2015-11-18 15:58
>BTW how did you get this results with gliden64? Using m64p + rsp-cxd4 in both HLE+LLE I only have the spinning logo + intro video, everything else is just a black screen (menu+ingame).

LLE and copy auxiliary option. Then I experimented with copy from RDRAM. I think it's a framebuffer effect. The backgrounds render separately and you have to combine them with the rest of the image. Glide64 also can't render everything at once if I remove the ini settings.

@Gillou68310 the game should work with Glide64+Glitch64. I think you just need to disable FBOs

**Comment by Gillou68310** [comment] 2015-11-18 16:26
> LLE and copy auxiliary option

Still black screens by my side

> @Gillou68310 the game should work with Glide64+Glitch64. I think you just need to disable FBOs

Disabling FBOs give me black screens too :-(

**Comment by purplemarshmallow** [comment] 2015-11-18 16:38
With GLideN64 you should see something with "EnableCopyAuxiliaryToRDRAM" and LLE. Everything except the backgrounds will render. And if you use this branch https://github.com/gonetz/GLideN64/tree/new_buffer_swap the videos will show up too.

Glide64+Glitch64 the game should be fully compatible. No need for zeckensack's wrapper. But I tried Glide64Final. But you might need to enable or disable FBOs in the wrapper settings

**Comment by Gillou68310** [comment] 2015-11-18 16:48
Here's my settings using rsp-cxd4 in LLE mode:

```EnableFBEmulation = True
# Enable color buffer copy to RDRAM (0=do not copy, 1=copy in sync mode, 2=copy in async mode)
EnableCopyColorToRDRAM = 2
# Enable depth buffer copy to RDRAM.
EnableCopyDepthToRDRAM = False
# Enable color buffer copy from RDRAM.
EnableCopyColorFromRDRAM = False
# Detect CPU writes to frame buffer.
EnableDetectCFB = True
# Enable N64 depth compare instead of OpenGL standard one. Experimental.
EnableN64DepthCompare = False
# Copy auxiliary buffers to RDRAM
EnableCopyAuxiliaryToRDRAM = True```

Nothing except the spinning logo + video + ingame inventory renders

Also disabling FBOs in the wrapper settings with glide64mk2 doesn't help, where can I find the source for Glide64Final?

**Comment by purplemarshmallow** [comment] 2015-11-18 17:07
>Nothing except the spinning logo + video + ingame inventory renders

I tested with the same settings and I can see everything except the backgrounds. Geometry ingame renders. But in my screenshots I played with copyFromRDRAM

>Also disabling FBOs in the wrapper settings with glide64mk2 doesn't help, where can I find the source for Glide64Final?

https://github.com/gonetz/glidehqplusglitch64

**Comment by Gillou68310** [comment] 2015-11-18 17:17
> I tested with the same settings and I can see everything except the backgrounds.

That's weird I tested this on two different hardware (ATI/Nvidia) with same results.  

> https://github.com/gonetz/glidehqplusglitch64

Lol thanks ;-)

**Comment by purplemarshmallow** [comment] 2015-11-18 22:18
I tested again with PJ64 and got these screenshots (again with copy from RDRAM). I think it should also be possible to get this game working without copying from RDRAM but let's put this aside. What is more important something is wrong with the BG command. The BG command draws the image 2 times and with wrong width?
![1](https://cloud.githubusercontent.com/assets/7283660/11256145/7dd7ed5c-8e4a-11e5-90f9-6ef57fe9210c.jpg)
![2](https://cloud.githubusercontent.com/assets/7283660/11256148/8162b09c-8e4a-11e5-8cdc-9c8f2016dce9.jpg)

**Comment by Gillou68310** [comment] 2015-11-19 09:58
Looks like Glide64 is using some kind of hack to resize the background image.

```
  if (rdp.ci_width == 512 && !no_dlist) //RE2
  {
    wxUint16 width = (wxUint16)(*gfx.VI_WIDTH_REG & 0xFFF);
    d.frameH = d.imageH = (d.frameW*d.frameH)/width;
    d.frameW = d.imageW = width;
    if (rdp.zimg == rdp.cimg)
    {
      DrawDepthImage(d);
      rdp.update |= UPDATE_ZBUF_ENABLED | UPDATE_COMBINE |
        UPDATE_ALPHA_COMPARE | UPDATE_VIEWPORT;
      return;
    }
  }```

**Comment by purplemarshmallow** [comment] 2015-11-19 15:23
Interesting this looks indeed like a hack for Resident Evil 2 in the Glide64 code. I wonder what's so special about this game. I noticed the backgrounds render as stripes with GLideN64 LLE (first 3 screenshots) and duplicated with GLideN64 HLE (last 2 screenshots)

**Comment by Gillou68310** [comment] 2015-11-19 18:34
> @Gillou68310 the game should work with Glide64+Glitch64. I think you just need to disable FBOs

Ok I checked this with project64 and you're right disabling FBOs fixed the depth issue (still the implementation is missing when using FBOs with Glitch64, zeckensack's wrapper works with FBO enable)

However disabling FBOs in m64p still gives a black screen, it seems to be related to the SDL opengl context because I extracted Glitch64 from pj64 and integrated it in mp64 using wglCreateContext instead of SDL and everything went just fine.

I tried different SDL configurations for color and depth buffer size but nothing seems to work, do you guys have any idea what's going on here?

See ```grSstWinOpenExt``` at https://github.com/project64/project64/blob/master/Source/Glitch64/OGLglitchmain.cpp

**Comment by purplemarshmallow** [comment] 2015-11-19 18:53
>zeckensack's wrapper works with FBO enable

I don't think the FBO checkbox does anything if you are not using the default wrapper Glitch64. It's an option for Glitch64.

But I fear I can't help you here. I don't know much about SDL

**Comment by Gillou68310** [comment] 2015-11-19 19:07
> I don't think the FBO checkbox does anything if you are not using the default wrapper Glitch64. It's an option for Glitch64.

Hum you're probably right, latest update of zeckensack's wrapper was in 2005, I'm not even sure FBOs were available at this time :-)

> But I fear I can't help you here. I don't know much about SDL

@gonetz any ideas? ;-)

**Comment by olivieryuyu** [comment] 2015-11-19 20:56
with Rice, there is background but not 3d gfx.

**Comment by gonetz** [comment] 2015-11-20 05:44
Regarding SDL: need to check which depth buffer format it uses. If the code works with wglCreateContext but does not work with SDL, only format difference can be the reason.

Regarding Glide64 code: I made lots of hacks in it to support RE2. Background size correction hack is one of the most important. I did not want to put all these hack to GLideN64 code, but they can serve as entry point for investigation of this game peculiarities.

**Comment by olivieryuyu** [comment] 2015-11-20 09:09
i would widely guess that the background may use gSPBgRectCopy from the S2DEX microcode.

**Comment by Gillou68310** [comment] 2015-11-20 10:45
Lol what a joke the SDL code forgot to save the screen resolution for hwfbe after resolution enumeration, anyway problem fixed sorry guys for polluting this thread with glide64 issues :-(

**Comment by gonetz** [comment] 2015-11-22 06:20
This game problems reported in #71.
"The backgrounds need CopyFromRDRAM" assumption is wrong.
Closed as duplicate of existing issue.

**Closed by gonetz** 2015-11-22 06:20 UTC
