### ISSUE TITLE
Zelda Majora's Mask: Camera looks weird

### ISSUE THREAD

**Issue by phly95** [gonetz/GLideN64#577] opened 2015-06-15 18:05 UTC
Two issues here on Majora's Mask with the camera. First is the frame of the camera is kinda screwy. Second is that the pictures that come out of it are totally glitched out.
![untitled](https://cloud.githubusercontent.com/assets/3526540/8166692/69f4d25e-1367-11e5-9b74-10f4ffffcdee.png)
![untitled2](https://cloud.githubusercontent.com/assets/3526540/8166693/69f89d3a-1367-11e5-975a-7c7ad4eee46a.png)

**Comment by phly95** [comment] 2015-06-29 17:50
does anyone else have this issue? This is with the GLideN64 compatible intel drivers, but I haven't seen any other glitches with the plugin (except the fullscreen exiting glitch)

**Comment by purplemarshmallow** [comment] 2015-06-29 19:53
I have this issue. It's not a bug in intel's drivers, I have a Nvidia gpu

**Comment by gonetz** [comment] 2015-06-30 06:54
Yes, it's common issue.

**Comment by gonetz** [comment] 2015-09-27 04:16
Fixed

**Comment by AmbientMalice** [comment] 2016-03-05 05:34
Can @phly95 close this?

**Closed** 2016-03-05 06:23 UTC
