### ISSUE TITLE
Donkey Kong 64 - Missing Eyes

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1752] opened 2018-03-14 23:40 UTC
The intro to Donkey Kong, when the Kongs are gathered, their eyes and are missing. Using Project 64 2.3.2 with latest WIP.
EDIT: Not present with Glide64 that comes with Project 64.

![gliden64_donkey_kong_64_000](https://user-images.githubusercontent.com/37382324/37436706-732153b0-27a6-11e8-9bbd-0b4dc3a89df5.png)

**Comment by theboy181** [comment] 2018-03-14 23:46
Monkey see, monkey do?

**Comment by Blue-Ike** [comment] 2018-03-15 03:43
See no evil.

**Comment by loganmc10** [comment] 2018-03-15 03:48
Looks ok to me (tested mupen64plus):

![donkey_kong_64-001](https://user-images.githubusercontent.com/848146/37443360-5898186e-27d1-11e8-844b-0f0ae14a0951.png)

**Comment by theboy181** [comment] 2018-03-15 04:37
Logan!!  Your comment about it working in mupen is as helpful as mine. ;)

**Comment by Kidboy17** [comment] 2018-03-15 05:00
So it's just an issue with Project 64 then?

**Comment by theboy181** [comment] 2018-03-15 05:03
It’s an issue with project 64 video. I doubt that he tested it on mupen.

**Comment by Kidboy17** [comment] 2018-03-15 05:05
No, i did not test it on Mupen. Never used Mupen, been using Project 64 for years now.

**Comment by theboy181** [comment] 2018-03-15 05:27
Logan didn’t test it on mupen is what I meant. Pj64 doesn’t have the same plugin spec as Mupen. My suggestion is you download GLideN64 3.0 and wait for pj64 developers to finish project 64 video. (Refactored GLideN64)

**Comment by Kidboy17** [comment] 2018-03-15 06:16
Ok will do. Is GLideN64 3.0 a more stable build than the newest WIP of GLideN64?

**Comment by loganmc10** [comment] 2018-03-15 12:05
> Logan didn’t test it on mupen is what I meant. Pj64 doesn’t have the same plugin spec as Mupen. My suggestion is you download GLideN64 3.0 and wait for pj64 developers to finish project 64 video. (Refactored GLideN64)

What? That screenshot I posted was from mupen64plus. Also project64-video is a refactoring of Glide64, not GLideN64. I'm not sure what you're trying to say

**Comment by theboy181** [comment] 2018-03-15 13:14
Dis you test project64-video on mupen? I was also under the impression that project 64 video was refactor of GLideN64. But no GUI.

**Comment by loganmc10** [comment] 2018-03-15 13:17
No I tested GLideN64 on mupen64plus, the big report is saying that they have no eyes when using GLideN64.

And no, Project64-video is Glide64. I think zilmar had plans of creating a non-Qt GUI for GLideN64, but that is a separate thing

**Comment by theboy181** [comment] 2018-03-15 13:39
I see now. I totally didn’t read that right. Sorry to the both of you. 

This issue could actually be because of the bones displacement bug caused by an FPU math error. The error exists in older PJ64, and other emulators.  

Zilmar fixed it in 2.4 and Mupen fixed it after the fix was made public. (possibly why Logan stated it works)

Can you test with latest PJ64? There was also a cheat code floating around to address it on older emulators. Not too sure where that is posted atm.

**Comment by gonetz** [comment] 2018-03-15 17:08
I can't reproduce that bug with Project 64 2.3.2

**Comment by Kidboy17** [comment] 2018-03-15 18:07
Yeah I can test it with a newer PJ64. I hear there is a 2.4 floating around but I'm not sure where to get it.

**Comment by oddMLan** [comment] 2018-03-15 23:58
It's very possible that it is a shader cache issue. Does disabling shader cache make any difference? @Kidboy17

**Comment by oddMLan** [comment] 2018-03-16 00:04
Under GLideN64 settings, under "Emulation", uncheck "Use shader cache for enhanced performance"... sorta like that. You can't miss it.

**Comment by Kidboy17** [comment] 2018-03-16 00:13
When I disable them, the eyes are back.

**Comment by oddMLan** [comment] 2018-03-16 00:32
Okay, can you go to the Project64 install folder, under Plugins. Find one folder called "shaders", delete it. Re-enable Shader cache under "Emulation" on GLideN64. Restart the emu and see if that fixes the issue for good.

**Comment by Kidboy17** [comment] 2018-03-16 00:52
No need because I don't have problems with the eyes anymore. When i disabled it, the problem was fixed. I enabled the shader cache again and the eyes did not disappear. I even messed with the settings and the eyes did not disappear.

**Comment by oddMLan** [comment] 2018-03-16 01:04
Okay, your shader cache got corrupted somehow. Proably a driver update that broke it. You can close this issue.

**Comment by theboy181** [comment] 2018-03-16 01:10
YAY!! Oddman ;) (oddMLan)

**Comment by tony971** [comment] 2018-03-16 14:24
I usually delete the cache when updating GLideN64 for similar reasons. How hard would it be to implement automatic cache deletion if it was created by a different revision?

**Comment by oddMLan** [comment] 2018-03-16 16:09
It is already doing that when the shader cache version changes. Sometimes they do a certain change that should cause a version bump and forget to update that number, causing issues. Most likely not related to that, but a driver update, which broke the cache made with the old driver.

Anyway, if the issue is solved the issue should be closed.

**Closed** 2018-03-17 03:15 UTC
