### ISSUE TITLE
Super Mario 64 - Color garbage on start after logo

### ISSUE THREAD

**Issue by CharlesCorrin** [gonetz/GLideN64#1330] opened 2017-01-23 01:11 UTC
Game: Super Mario 64

Problem: When you boot Super Mario 64, it first shows the game's logo, then erroneously shows color garbage before going to the Mario's head screen.

My system: Windows 10 64-bit.

GlideN64: Using latest WIP build (December 22nd) from the WIP builds page on this Github.

**Comment by Aquatakat** [comment] 2017-01-23 01:15
Many games show colour garbage at one point or another. I wonder why.

**Comment by Yui12** [comment] 2017-01-23 06:25
I recall Glide64 has this problem with some games last time I remembered.

**Comment by retrobenny** [comment] 2017-01-24 08:52
Wasn't this mentioned before that it happens on an actual console too?

**Comment by gonetz** [comment] 2017-02-21 10:12
Duplicate of #867

**Closed by gonetz** 2017-02-21 10:12 UTC
Labels: duplicate
