### ISSUE TITLE
FBInfo not working

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1559] opened 2017-08-29 18:00 UTC
I've been working on getting FBInfo working properly in mupen64plus.

I figured out what the main issue was. Now the screen in Mario Kart works for example.

However there seem to be issues with FBInfo on the GFX plugin side. I tried the latest WIP build with 1964 1.1, and I tested Banjo Kazooie and Pokemon Snap. Banjo freezes halfway through the puzzle animation, and Pokemon Snap freezes after you press Start. I have the same issue in my fixed build of mupen64plus and 1964 1.1

**Comment by loganmc10** [comment] 2017-08-29 18:54
Also @gonetz I have a question about ```FBInfo::Write```, how do you interpret the ```size``` parameter of that function?

The API says:
```
size		1 = unsigned char, 2 = unsigned short, 4=unsigned int
```

But then I see in 1964, they just pass the overall size of the write:

https://github.com/LegendOfDragoon/1964-X/blob/master/src/core/dma.cpp#L106

It seems so strange to me that the emulator that invented this API doesn't seem to follow it's specifications...

**Comment by olivieryuyu** [comment] 2017-08-29 22:19
1964 is buggy with info.

Mupen 0.5 got it working. Dunno for Mupenplus.

**Comment by loganmc10** [comment] 2017-08-29 22:22
I tested mupen64 0.5.1 as well, same issues. Freezes in Pokemon Snap when hitting start, freezes halfway through the puzzle effect in Banjo. Maybe something broke since FBInfo was first implemented?

**Comment by Jj0YzL5nvJ** [comment] 2017-08-30 08:44
The effect on the jigsaw puzzle in Banjo Kazooie worked correctly in Linux, I don't know now... let's see...

**Comment by loganmc10** [comment] 2017-08-30 11:00
Did you enable FBInfo? It's disabled by default in mupen64plus

**Comment by LegendOfDragoon** [comment] 2017-08-30 16:56
>Maybe something broke since FBInfo was first implemented?

Probably. The puzzle effect works with other plugins in 1964.

**Comment by Jj0YzL5nvJ** [comment] 2017-08-30 17:03
> Did you enable FBInfo? It's disabled by default in mupen64plus

 With `DisableFBInfo = False` the jigsaw puzzle effect broke, but not freezes. The FPS in all the games are totally messed up. I'm not using even 30% of CPU, is like a looped code... I think.

**Comment by loganmc10** [comment] 2017-09-06 14:53
It seems to work in Public Release 2.0, so something between then and now has broken it

**Comment by loganmc10** [comment] 2017-09-11 16:25
This is the commit that broke FBInfo in Pokemon Snap (makes it freeze when hitting start in 1964/mupen64):

https://github.com/gonetz/GLideN64/commit/952769a67128379851219b45dbce219fdb5a856e

**Comment by gonetz** [comment] 2017-09-12 10:07
Interesting. I guess, this commit increases detected height of color buffer, so FBInfo writes more data and overwrites something important.

**Comment by Jj0YzL5nvJ** [comment] 2017-09-18 10:24
I'm not sure if this is related, the coronas in Zelda MM are always visible with cxd4-sse2. In Perfect Dark is exactly the opposite, they are never visible.

**Comment by AmbientMalice** [comment] 2017-09-18 10:26
>I'm not sure if this is related, the coronas in Zelda MM are always visible with cxd4-sse2.

You're not running in LLE mode, are you?

**Comment by Jj0YzL5nvJ** [comment] 2017-09-18 10:30
Pure Interpreter, Cached Interpreter and Dynamic Recompiler?
They work exactly the same to me.

**Comment by AmbientMalice** [comment] 2017-09-18 10:52
No, I mean the RSP. Is the RSP sending display lists to GLideN64? GLideN64 supports rendering games without an HLE microcode implementation, but it is extremely buggy and slow, unfortunately.

HLE:
![perfect_dark-000](https://user-images.githubusercontent.com/10704701/30538863-34480fc2-9cb3-11e7-9d4c-322ee6cea5dd.png)

LLE:
![perfect_dark-001](https://user-images.githubusercontent.com/10704701/30538864-344cb9d2-9cb3-11e7-8677-8f80f70d476c.png)

**Comment by Jj0YzL5nvJ** [comment] 2017-09-18 11:07
In me current situation, even with cxd4-sse2 in LLE mode works more faster that the HLE one T.T #1561

**Comment by olivieryuyu** [comment] 2017-09-27 07:56
@gonetz 

Should we continue to support fb notification? 

It is a great idea to have this however with the current power of graphics cards, even on mobile devices, it may not be necessary anymore. Not sure that nowadays a lot of people uses this feature.

Fact is as well that Mupenplus does not support this feature anymore and 1964 got a quite poor implementation.

It would simplify the code and its maintenance.

**Comment by AmbientMalice** [comment] 2017-09-27 08:16
@olivieryuyu Without some form of FB notification, how do you propose GLideN64 handle games where the CPU writes to the screen? Particularly above native resolution?

**Comment by olivieryuyu** [comment] 2017-09-27 09:30
CPU writes to screen are handled without fb notification. Which effects are not handled by the plugin where fb notification really help?

**Comment by AmbientMalice** [comment] 2017-09-27 09:34
Pokemon Snap, Jet Force Gemini, Conker's Bad Fur Day, and a few others. The essential problem is that Render N64 Framebuffer to Output is too glitchy (Pokemon is Broken) and it also forces the game to render at native resolution. FB notification has never properly, but if it did work properly, games would be able to render above native resolution with these effects intact. It's similar to what Dolphin does.

**Comment by olivieryuyu** [comment] 2017-09-27 09:38
That is one argument indeed.

Let's wait for Sergei opinion.

**Comment by gonetz** [comment] 2017-09-27 12:00
I'm going to fix it.

**Comment by loganmc10** [comment] 2017-11-01 21:10
So the regression seems fixed, but there are still issues with FBInfo (Mario 64 doesn't work)

**Comment by gonetz** [comment] 2017-11-02 07:51
There is a principle problem with FBInfo. How FBInfo works: emulator asks plugin for information about known frame buffers. Buffer origin, width, height. Emulator need this info to know which areas in RDRAM need to be controlled. Plugin returns that information about buffers it knows. When emulator detects read/write access to memory areas reported by plugin, it informs the plugin about such events. Thus, plugin knows which pixels were modified by CPU in color buffer and thus can show these pixels on screen. Plugin get informed, that CPU is trying to read some data from buffers and it can fill these buffers in RDRAM with data from video memory before CPU read it. Looks like a perfect solution. However, there is a problem.

The plugin returns to emulator info about buffers, which were used in display lists it previously processed. That is this info is valid until the end of current display list. This information can became invalid right after it. Game code can reuse the memory allocated for a buffer for other tasks. Next frame does not need to use depth compare? Ok, lets use depth buffer memory for something else. The same can be with color buffers as well. So, game code does some computations and writes result to area, which was a video buffer. Emulator detects writes to buffer and informs the plugin about them. Ok, plugin will copy itself some garbage to display it over that buffer. It is harmless. Then, the code reads result of calculation done before from that buffer. Emulator detects the reads and informs the plugin. Plugin fills the buffer with data from video memory. Results of the calculations are erased, game code crashes.

I found that problem long ago. GLideN64 has some protection from it: if CPU writes to some buffer and then reads from the same buffer, plugin does not fill the buffer with data from video memory. However, that protection does not always work. I will try to add more sophisticated protection, but result is not guaranteed.

**Comment by loganmc10** [comment] 2017-11-02 18:38
@gonetz is there some way to determine on the emulator side when the memory is no longer being used as a Framebuffer? Like could you track it by watching a certain VI register or something?

I'd like to get this working but it seems quite complex. It might be easier/less bug prone to just track the reads, not the writes. The writes aren't an issue for performance, only the reads, so as long as we could properly determine which reads are really for a Framebuffer, we could just track those. The end goal is basically to reduce the number of glReadPixels calls

I don't mind extending the mupen64plus api or somehow modifying Fbinfo to get that working

**Comment by AmbientMalice** [comment] 2017-11-03 07:32
>The writes aren't an issue for performance, only the reads, so as long as we could properly determine which reads are really for a Framebuffer, we could just track those.

The primary benefit of FBInfo, IMO, from an emulation accuracy perspective, is emulate CPU framebuffer writes without needing to force native resolution.

Its performance benefit is somewhat more fickle. It will probably help mobile devices quite a bit. If the HW depth buffer is ever fixed, it will greatly benefit performance overall for that side of things. But without detecting FB writes, that problem remains unresolved. I'd be inclined to force copy framebuffer from RAM for a bunch of games, but of course people will then complain about resolution.

**Comment by gonetz** [comment] 2017-11-03 08:50
> is there some way to determine on the emulator side when the memory is no longer being used as a Framebuffer? Like could you track it by watching a certain VI register or something?

Frame buffer validity is the hardest problem in HWFBE. I do not know a safe way to probe buffers. Only program code knows how memory is used. VI register points on the currently displaying buffer, but there are other buffers.  Plugin uses several techniques to detect that the buffer modified outside of RDP, but  it does not help with the problem I described above. The problem is that program code decides to reuse buffer's memory after display list processing. I don't see how plugin can distinguish "CPU to color buffer writes" situation from "CPU reuse buffer memory and writes some data to it".

> It might be easier/less bug prone to just track the reads, not the writes.

This will kill the protection I told about. If emulator tracks only reads, it will notice read from color buffer and ask plugin to fill it. If the color buffer was dropped and its memory was reused for calculations, plugin will overwrite results of these calculations with data from video memory and program will crash.
May be it is possible to apply buffer validity checks here and do not write to buffer if the check failed. I'm planning to try it. However, it hardly will work always.

Also, I don't agree that end goal is to reduce the number of glReadPixels calls. FBWrite allows plugin to emulate CPU writes much more precisely. Aim in JFG, red dot in Pokemon Snap, etc. 
JFG looks much better with FBInfo.

**Comment by fzurita** [comment] 2017-11-03 12:17
From reading this, it really sounds like the FBInfo API needs to be extended. If anyone would know if frame buffer memory is no longer used for the frame buffer, it would be the core, right? The core could let the graphics plugin know.

**Comment by gonetz** [comment] 2017-11-04 05:59
> if frame buffer memory is no longer used for the frame buffer, it would be the core, right?

I doubt that core can easily differentiate writes of additional graphics to color buffer from writes to that area when buffer is dropped. The core needs deep program code analysis to understand that difference.
I can be wrong, need to ask experts like hacktarux or zilmar.

**Comment by weinerschnitzel** [comment] 2017-11-04 15:04
FBInfo is used for specific effects. Would it be viable to research which addresses are valid color buffer writes, and allow the emulator to announce when the buffer is no longer valid using some logic and a database of these effects? 

"Deep code analysis" sounds like a steep task for optimizing FBInfo. I would think a "hackier" approach would be easier and probably faster.

**Comment by gonetz** [comment] 2017-11-04 15:55
>  Would it be viable to research which addresses are valid color buffer reads/writes

Buffer address can be valid for reads/writes for some times, but then became invalid because the buffer dropped.

**Comment by weinerschnitzel** [comment] 2017-11-04 17:03
There would also need to be more per game logic involved to alert when the buffer becomes invalid. I imagine it would be easier to write per game logic for the half dozen or so games that would use it than to come up with a universal check. It doesn't sound like a universal check would be possible or very easy. Just my 2 cents

**Comment by loganmc10** [comment] 2017-11-04 20:42
I think that might be a little impractical. Many games use framebuffer effects. To try and keep track of where each game stores the framebuffers, and when, and taking into account regional differences for the games, etc... That would be quite the project.

It's unfortunate there isn't some better way to detect when a framebuffer is no longer valid. I don't know much about this, but how does it work without FBInfo? It's obviously not copying data into invalid areas of RDRAM in that case.

I've got FBInfo working with mupen64plus except for the Puzzle Transition in Banjo Kazooie, it doesn't seem to work with this write/read detection business for invalid framebuffers. Changing the CountPerOp setting to 1 allows more of the puzzle to display (the rest is black), but it's still not perfect. It would be really nice to have a better detection method

**Comment by LegendOfDragoon** [comment] 2017-11-04 21:02
> I imagine it would be easier to write per game logic for the half dozen or so games that would use it than to come up with a universal check. 

Not only that, but also if you study a few games extensively, it could help with implementing a global version.

>It doesn't sound like a universal check would be possible or very easy

Indeed. FBRead is generally straightforward, but FBWrite is another story.

I think it would be neat to have an extensive database like Glide64 help.chm (but even more extensive of course). That way, people could tackle problems more efficiently and keep track which features are implemented in which games.

> That would be quite the project.

It would be feasible if the community chips in to help. The N64's library isn't that big.

How many games use FBWrite?

**Comment by loganmc10** [comment] 2017-11-04 21:13
I have no idea, but as far as I understand FBWrite isn't the problem. If we write into a Framebuffer that never ends up getting used it's no harm done. Games like Pokemon Snap or Dr Mario currently work perfectly with FBWrite/FBInfo

The problem is FBRead, right now the emulator might request to read data that we assume is from a Framebuffer, so we fill RDRAM with data, but we are wrong, it's no longer being used for the Framebuffer, and we just filled RDRAM with garbage

**Comment by LegendOfDragoon** [comment] 2017-11-04 21:31
> it's no longer being used for the Framebuffer, and we just filled RDRAM with garbage

What games is this happening in?

To my knowledge, graphics plugins check the address to see if it's is valid (and whether it has already been copied within the frame), before copying to RDRAM. 1964 is certainly aggressive and the FBRead function gets triggered too often (and is sometimes invalid), but gfx plugin authors have managed to do a fairly decent job (not perfect) at filtering out the invalid ones.
One example of a flaw was in z64gl where it would copy the buffer twice in 1964 during the puzzle effect (basically just performance overhead afaik).

**Comment by loganmc10** [comment] 2017-11-04 21:35
The puzzle transition has this issue, see https://github.com/gonetz/GLideN64/issues/808#issuecomment-162223042

The list of Framebuffer areas in RDRAM is provided by the GFX plugin, so it would be up to GLideN64 to provide a better list, or potentially have the emulator ignore some of the items in the FBInfo list if it knows they are invalid

**Comment by loganmc10** [comment] 2017-11-05 04:06
Another game with issues with FBInfo is Mario Tennis (pause screen), doesn't work right in 1964, mupen64, or a fixed version of mupen64plus, same issue on all 3:
![capture](https://user-images.githubusercontent.com/848146/32411871-64205222-c1ac-11e7-8548-cc5b23303037.PNG)

**Comment by fzurita** [comment] 2017-11-05 04:26
Since it affects all 3. Could it be an issue in the plugin instead of the core?

**Comment by gonetz** [comment] 2017-11-12 15:12
I put FBInfo fixes in branchhttps://github.com/gonetz/GLideN64/tree/fbinfo_fixes

I implemented Logan's idea to protect more than one buffer. SM64 does not freeze on start now.
Puzzle effect in Banjo works.
Also writes to buffer corrected: aim in JFG works again.

Windows test build:
https://drive.google.com/file/d/1pJns9PpoUUwXDktVFseOcUHOBiaOpBCh/view?usp=sharing

**Comment by AmbientMalice** [comment] 2017-11-13 00:32
Using 4kb chunking breaks Pokemon Snap. The picture you take are garbled when you view them. Without 4kb chunking, they work fine.

**Comment by loganmc10** [comment] 2017-11-13 00:35
I should have fleshed out that PR a bit more @gonetz . Right now it has issues:

Let's say the FB starts at 0xe400 and a FBRead request comes in for 0xe800

Right now it'll perform an FBRead for 0xe000 to 0xf000, but 0xe000 to 0xe3ff is outside the Framebuffer. So the start address needs to be modified, I think the end address is already dealt with if it's outside the buffer?

This might be the issue. @AmbientMalice what emulator did you test?

**Comment by AmbientMalice** [comment] 2017-11-13 00:36
I'm using your version of mupen64plus, @loganmc10 Latest build.

**Comment by loganmc10** [comment] 2017-11-13 02:49
@gonetz Super Mario no longer freezes if I use my test build of mupen64plus, but his head is missing. Is it the same in 1964?

**Comment by AmbientMalice** [comment] 2017-11-13 03:01
SM64 freezes for me on boot with m64p.

**Comment by loganmc10** [comment] 2017-11-13 03:05
Yeah the current version doesn't track all the reads/writes, it only tracks direct reads/writes to RDRAM. I've got a test build that also tracks DMA read/writes to RDRAM, it fixes the freezing, but the head is missing. I haven't tested 1964 (don't have my Windows machine on me)

**Comment by gonetz** [comment] 2017-11-13 04:57
I tested only with Mupen64, no problems with Mario head.

**Comment by loganmc10** [comment] 2017-11-13 05:08
Yeah 1964 still freezes in Mario. mupen64 works. Both 1964 and mupen64 work with the puzzle transition.

mupen64plus still has an issue with the puzzle transition, part of the image is black. Playing with the CountPerOp setting affects how much of the image is black. Mario doesn't freeze, but the head is missing... I'll try and look into it, very strange stuff

**Comment by loganmc10** [comment] 2017-11-13 05:29
Ok the missing head is a problem with mupen64plus's dynarec, it works with the interpreter. The puzzle transition still has that black image issue, related to the CountPerOp setting somehow.

**Comment by loganmc10** [comment] 2017-11-13 05:38
and @AmbientMalice yes the 4k color buffer chunk copying is broken. in Mario Kart the monitor image is upside down and pretty garbled as well (the issue still happens with 5f088c70ce893b22a48835e3dd2486814f7f0963 reverted)

**Comment by gonetz** [comment] 2017-11-13 06:14
>  image is upside down and pretty garbled

It was always pretty garbled with Mupen64, but upside down is a new regression.

**Comment by gonetz** [comment] 2017-11-14 11:18
> 4k color buffer chunk copying was always pretty garbled with Mupen64

garbled 4k color buffer chunk copying is regression too.
Chunked buffer copy fixed by commit aeba3fcf for color and depth buffers.

**Comment by loganmc10** [comment] 2017-11-14 15:18
Yep Mario Kart looks good now! I tested 4k color copies in Pokemon Snap (it works perfectly without 4k copies).

With 4k copies Prof. Oaks check looks like this:
![pokemon_snap-002](https://user-images.githubusercontent.com/848146/32787604-2e8aed1a-c914-11e7-8329-acdbc89932ec.png)

The weird thing is if you look at a picture, then go back, then look again, the picture looks normal except for a bit of a bar at the top:
![pokemon_snap-004](https://user-images.githubusercontent.com/848146/32787640-4662a8ec-c914-11e7-88ef-d93d92ce8a84.png)

But if you try to go to the actual check, the game freezes. Without 4k copies everything works normally

**Comment by loganmc10** [comment] 2017-11-15 14:21
Ok I think the fbinfo_fixes branch can probably be merged into master. I believe the remaining issues I have with mupen64plus are probably on the emulator side

**Comment by loganmc10** [comment] 2017-11-15 18:30
One game that still has issues on every emulator is DK64

**Comment by gonetz** [comment] 2017-11-16 03:37
> Ok I think the fbinfo_fixes branch can probably be merged into master.

Merged.

**Comment by gonetz** [comment] 2017-11-17 06:07
FBInfo works again, closed.

**Closed by gonetz** 2017-11-17 06:07 UTC
Labels: Regression
