### ISSUE TITLE
Mischief Makers - Mathfun questions are black and unreadable

### ISSUE THREAD

**Issue by lKomus** [gonetz/GLideN64#1183] opened 2016-10-18 07:46 UTC
This was tested with GLideN64's last master, it used to work with Glide64.

GLideN64
![project64_2016-10-18_09-34-58](https://cloud.githubusercontent.com/assets/4800879/19468585/76ff1346-9517-11e6-9011-79652c64df76.png)
Glide64
![project64_2016-10-18_09-35-15](https://cloud.githubusercontent.com/assets/4800879/19468588/7ae4cf32-9517-11e6-85df-7c9c2860ae5d.png)

Savestate: [Mischief Makers (U) (V1.0).pj.zip](https://github.com/gonetz/GLideN64/files/535535/Mischief.Makers.U.V1.0.pj.zip)

**Comment by gonetz** [comment] 2016-10-18 10:42
Could you provide savestate for older version of Project64 or for another emulator?

**Comment by gonetz** [comment] 2016-10-18 16:40
This and #1181 are the same problem. N64 uses fixed point arithmetic and non-trivial clamp of the result. Negative value of a color is clamped to zero, but if its absolute value is large enough it can became one! 
Here the board has color -1. GL clamps it to zero. N64 clamps it to 1.

Shader code to  fix it looks like this:
```
if (color1.r < -0.51) color1.r = 1.0; else if (color1.r < 0.0) color1.r = 0.0;
if (color1.g < -0.51) color1.g = 1.0; else if (color1.g < 0.0) color1.g = 0.0;
if (color1.b < -0.51) color1.b = 1.0; else if (color1.b < 0.0) color1.b = 0.0;

```
This looks ugly. Can somebody suggest better code? Preferably one vector operation.

**Comment by lKomus** [comment] 2016-10-18 16:54
Sorry I wasn't available until now. Here's a savestate made with PJ64 1.6
[MISCHIEF MAKERS.pj.zip](https://github.com/gonetz/GLideN64/files/536880/MISCHIEF.MAKERS.pj.zip)

**Comment by fzurita** [comment] 2016-10-18 17:48
ivec4 color1_temp = clamp(color1, -1, 0)/-0.51*1000; //This results in 0 or >1000 if we convert to integer, 1000 was selected for being a large number.
color1 = color1+color1_temp ; //You end up with either the same number or a number much greater than 1

With the above, if a component was <= -0.51, you end up with a number much greater than one, which will get clamped to 1.

**Comment by gonetz** [comment] 2016-10-19 02:11
I probably missed something,  but your code will map any negative value to 1. Values -0.51 < c < 0 must be clamped to zero.

**Comment by fzurita** [comment] 2016-10-19 02:30
Yeah, it's just pseudo code, so it's not exact, but I'll demonstrate:
With an input vec4 of (-0.45, -0.45, -0.45, -0.45);
```
vec4 temp1 = clamp(color1, -1, 0);  //temp1 = (-0.45, -0.45, -0.45, -0.45);
temp1 = temp1/-0.51;      //temp1 = (0.88, 0.88, 0.88, 0.88);
ivec4 temp2 = temp1; // Cast this to an integer somehow? temp2 = (0, 0, 0, 0)
ivec4 temp2 = temp2*1000; temp2 = (0, 0, 0, 0)
color1 = color1 + temp2; //Cast temp2 back to a vec4 somehow? Then you end up with color1 of  (-0.45, -0.45, -0.45, -0.45)
```

**Comment by fzurita** [comment] 2016-10-19 02:54
I guess to cast a vec4 to a ivec4 you could do
```
ivec4 temp = ivec4(int(color1.r), int(color1.g), int(color1.b), int(color1.a));
```

and the same backwards

**Comment by gonetz** [comment] 2016-10-19 03:46
This code does the trick
```
    vec3 clampColor = clamp(color1, -1.0, 0.0)/-0.51;
    ivec3 iClampColor = ivec3(clampColor)*1000;
    color1 = clamp(color1 + vec3(iClampColor), 0.0, 1.0);

```
Thanks!

**Comment by gonetz** [comment] 2016-10-19 03:47
@lKomus thanks for the save

**Comment by fzurita** [comment] 2016-10-19 03:53
No problem!

**Comment by gonetz** [comment] 2016-10-19 05:05
The fix is in https://github.com/gonetz/GLideN64/tree/color_clamp branch.
@fzurita , @loganmc10 Please check that I that fix does not break anything.

**Comment by fzurita** [comment] 2016-10-19 05:13
Tested GLES 3.1 and GLES 2.0 on one Android device. Everything seems to look the same, which is what we expect unless you run into this specific circumstance.

The change seems simple enough that I don't think different devices will act differently.

**Comment by gonetz** [comment] 2016-10-19 05:28
Yes. I was need to be sure that these modifications will compile without issues.
Thanks!

**Comment by fzurita** [comment] 2016-10-19 05:33
By the way, if you want to compile Mupen64plus-ae yourself, it's much easier now. All you need is Android Studio 2.2, clone the mupen64plus-ae github and open it using Android Studio. It should all compile and run right off the bat.

**Comment by fzurita** [comment] 2016-10-19 05:40
There is one difference with my approach than yours that I'm not sure you noticed. Mine is checking for '''<= -0.51''' your checks for '''< -0.51'''

**Comment by gonetz** [comment] 2016-10-19 05:52
'''< -0.51''' is more right.
I guess, that intended bound is -0.5, but N64 uses fixed point arithmetic, which impossible to correctly reproduce with floats. -0.5 bound produces wrong result, -0.51 bound works correct. Precise bound is somewhere near -0.506.

**Comment by fzurita** [comment] 2016-10-19 05:57
OK, so it sounds that it won't make much of a difference since we were not precisely accurate in the first place.

**Comment by gonetz** [comment] 2016-10-19 06:18
It does not make any difference because combiners rarely produce negative color values.
This game was full of strange bugs caused by too creative use of hardware capabilities.
BTW, I need to check, how large positive color values are clamped by N64. It does not care if value negative or positive, it just manipulates with bits. Probably, if color value is above 1.5 it should be clamped to 0.

**Comment by fzurita** [comment] 2016-10-20 05:10
The same mechanism can be applied to clamp 1.5 to zero.

**Comment by gonetz** [comment] 2016-10-20 05:24
Yes, but I'm not sure that it is used somewhere. It can be just waste of GPU resources.

**Comment by lKomus** [comment] 2016-10-22 23:58
Just noticed that contrary to what Glide64 shows, the question border should be white on real hardware
![firefox_2016-10-23_01-52-48](https://cloud.githubusercontent.com/assets/4800879/19623269/aef9c5de-98c3-11e6-8cd8-17d6c78eedb6.png)

The bar beneath Events should be blue:
![project64_2016-10-23_01-56-16](https://cloud.githubusercontent.com/assets/4800879/19623286/0b5d670e-98c4-11e6-9c75-4f9f679fa881.png)

This is to provide points of references just in case.

**Comment by AmbientMalice** [comment] 2016-10-23 00:01
@lKomus How do they look on GLideN64?

**Comment by lKomus** [comment] 2016-10-23 00:18
I can't compile GLideN64, so I can't tell you how they look on the color-clamp branch.

On the latest compiled master, the bar is just black, like everything else that needs the color clamp.

**Comment by standard-two-simplex** [comment] 2016-10-23 21:20
Is casting booleans to floats a bad thing?

You could always write `color1 = color 1 + (-color1)*float(color1<0.0) + float(color1<0.51);`

**Comment by fzurita** [comment] 2016-10-23 22:13
I like it better than my dilution since it gets rid of the random 1000 in the middle

**Comment by gonetz** [comment] 2016-10-24 10:44
@standard-two-simplex Thanks!

**Comment by fzurita** [comment] 2016-10-24 14:48
I wonder if this is the same problem as this in Paper Mario:

![paper_mario-000](https://cloud.githubusercontent.com/assets/11581687/19650443/5e2d384c-99d7-11e6-8cee-9eefdfc3cf42.png)

I don't think those are supposed to be black.

**Comment by fzurita** [comment] 2016-10-24 14:50
Actually, I think that blank is supposed to be full alpha.

**Comment by gonetz** [comment] 2016-10-25 03:24
This is a frame buffer effect. It worked ok on desktop last time I checked it. May be it was broken recently.

**Comment by fzurita** [comment] 2016-10-25 03:29
I just checked full OpenGL mode in shield TV and it was broken there. I don't think there is much difference between the Full OpenGL mode in Android and there desktop version.

**Comment by oddMLan** [comment] 2016-10-25 03:43
Does it work correct with texture filtering disabled?

**Comment by fzurita** [comment] 2016-10-25 03:45
The paper Mario effect does not work correctly with texture enhancements disabled.

**Comment by gonetz** [comment] 2016-10-25 03:54
Ok, please give me a savestate.

**Comment by fzurita** [comment] 2016-10-25 03:57
Here you go for mupen64plus:
[Paper mario.sav.zip](https://github.com/gonetz/GLideN64/files/549579/Paper.mario.sav.zip)

Talk while standing on the opposite side of the orb.

**Comment by gonetz** [comment] 2016-10-25 04:08
Thanks! The same on desktop, yes.

**Comment by oddMLan** [comment] 2016-10-25 04:41
Reminds me how all plugins but GLideN64 and Angrylion's can't emulate the alpha of tennis ball trace properly in Mario Tennis (the orb shows with an ugly black background much like in that Paper Mario pic) How did GLindeN64 accomplish that feat?

**Comment by gonetz** [comment] 2016-10-25 05:34
tennis ball trace is also fb effect, which blends texture of already rendered buffer with texture of the ball.

**Comment by gonetz** [comment] 2016-10-25 05:34
I fixed that crystal ball issue in Paper Mario.

**Comment by fzurita** [comment] 2016-10-25 06:26
Ok, I just verified that Paper Mario is fixed.

**Comment by lKomus** [comment] 2016-10-30 14:11
Confirmed to be fixed in last master!

**Closed** 2016-10-30 14:11 UTC
