### ISSUE TITLE
Body Harvest Clipping Issue

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#550] opened 2015-05-23 19:46 UTC
This game works fine in AL RDP, but you clip through walls in GLideN64..

Not sure if this has been brought up before, I think the emulator has always been blamed int he past.

**Comment by AmbientMalice** [comment] 2015-05-24 01:38
It's colour-buffer related, to my knowledge. Same underlying problem as Pokemon Snap. It would be nice to see the problem solved.

**Comment by theboy181** [comment] 2015-05-24 02:05
Are there any articles to support that?

**Comment by purplemarshmallow** [comment] 2015-05-26 07:02
It can be colour-buffer related because filling it with white color fixed the subscreen delay in Zelda OOT. And it is believed that it's the same problem. But nobody seems to know for sure.

**Comment by AmbientMalice** [comment] 2015-05-26 07:14
I don't have any documentation on hand. But, for example, Pokemon Snap uses the colour buffer to detect whether you're looking at a Pokemon. But for some reason, very little study has gone into figuring out how Body Harvest calculates collision.

**Comment by theboy181** [comment] 2015-06-18 05:34
Could Gliden64 share the same bug?
https://dolphin-emu.org/blog/2015/06/01/dolphin-progress-report-may-2015/
The Depth Divisor and its Farfetch'd Solution. This may be how the depth is calculated for collision in this game too?

**Comment by olivieryuyu** [comment] 2015-07-12 18:51
dunno

what you can see how the framebuffer is used in game. interesting

**Comment by olivieryuyu** [comment] 2015-07-26 21:45
how fill color could help to calculate collision. Very odd

**Comment by olivieryuyu** [comment] 2015-08-10 21:06
i analyse the rom and i can see something odd:


![sans titre](https://cloud.githubusercontent.com/assets/8987490/9184162/d7503e9c-3fb3-11e5-8688-6a0bac0b41d6.jpg)

is there some kind of check that all data are always correct in ram? in case of errors, the game goes crazy.

It is as well odd to see that with Glide64, with or without fb on, glide64 have different bugs, as if reading the memory of the emulated N64 had on impact on the behavior of the plugin.

The worst being with Nemu plugin: it blocks at the very beginning of the first level, when other can go through.

It seems like a self code checkings.

**Comment by AmbientMalice** [comment] 2016-03-23 04:56
I have a theory that for whatever reason, the game thinks the buildings are destroyed. Damaged buildings lose their collision in Body Harvest. What is especially interesting is that if you boot Body Harvest with a normal plugin, then switch to Angrylion's, the collision stays broken. But if you boot with Angrylion's, you can switch to another plugin and it works for a while. So my theory is that the game writes the status of each object into a buffer area or something.

**Comment by LegendOfDragoon** [comment] 2016-12-21 20:07
iirc it's generated in the z-buffer. The calculations need to be accurate and it involves coverage. Easiest method I can think of, is to do it in software, but not sure how much overhead that would have.

**Comment by AmbientMalice** [comment] 2017-02-01 02:51
For reference. https://github.com/project64/project64/issues/428#issuecomment-276536352

**Comment by Frank-74** [comment] 2017-06-06 02:17
@theboy181 
This can be closed I think.

I played through Body Harvest using Software Depth Buffer.  Well, I got upto the end of America without any clipping issues.  I completed Greece and Java, found America level a bit of a pain and gave up.

But it's fully playable now.

**Comment by theboy181** [comment] 2017-06-06 04:50
Are the settings now included in the ini?

**Comment by loganmc10** [comment] 2017-06-06 04:56
Software depth buffer is the default now, so Body Harvest works with the default settings

**Comment by theboy181** [comment] 2017-06-06 05:08
I guess a new thread needs to get started stating that the software mode needs improvement. Are there still issues ?

**Comment by loganmc10** [comment] 2017-06-06 05:13
https://github.com/gonetz/GLideN64/issues/1023

**Comment by olivieryuyu** [comment] 2017-10-09 20:59
interestingly it seems that this issue was somehow fixed by G_CULL_FRONT instead of G_CULL_BACK for the depth buffer before b6c6ac0. Not sure what is related between G_CULL and depth buffer but there can be a link.

**Comment by Frank-74** [comment] 2017-10-10 11:11
Body Harvest clipping only works properly with G_CULL_BACK, the change to FRONT is what broke it again.

**Comment by gonetz** [comment] 2017-10-10 12:01
G_CULL_BACK and G_CULL_FRONT are valid culling modes. N64 can use both.
I need to understand what goes wrong. I asked @LegendOfDragoon to help, since he
Investigated this issue, but I did not get any answer.

**Comment by gonetz** [comment] 2017-11-15 12:30
Fixed again: 7a11c6ca6b3042e

Test build:
https://drive.google.com/file/d/1AHlHDqYAAd_2GFIlO1qhYunr4FPSpOMJ/view?usp=sharing

**Comment by AmbientMalice** [comment] 2017-11-15 13:47
Seems fixed. And properly fixed, this time. AFAIK, the collision on these stairs were broken, but they seem fine now.
![gliden64_body_harvest_000](https://user-images.githubusercontent.com/10704701/32839175-486db8d8-ca5f-11e7-93c5-ab0bf70c2cb0.png)

**Comment by olivieryuyu** [comment] 2017-11-15 14:14
finally this game is totally fixed! let's see indeed for regression.

**Comment by gonetz** [comment] 2017-11-15 15:44
>finally this game is totally fixed

There was also a bug with map transition effect.

**Comment by olivieryuyu** [comment] 2017-12-01 14:21
can it be closed?

**Comment by gonetz** [comment] 2017-12-02 06:17
I think, yes. Original issues is fixed. It can be reopen in case of regressions.

**Closed by gonetz** 2017-12-02 06:17 UTC
