### ISSUE TITLE
[Mupen64Plus] No video in Mupen64Plus 2.5.0

### ISSUE THREAD

**Issue by gourdcaptain** [gonetz/GLideN64#1313] opened 2016-12-28 03:05 UTC
When using GLideN64 2.0 with Mupen64Plus 2.5.0 on Arch Linux 64-bit (Intel HD Graphics 515, Mesa 13.0.2) the screen shows no visuals and a black screen, while the audio plays for the game on all games I have access to. Another Arch Linux user is having the same issue with the plugin as noted here on the AUR package: https://aur.archlinux.org/packages/mupen64plus-video-gliden64/

This occurs when using Mupen64plus standalone as well as in m64py. A log from Mupen64Plus is below:

|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Goodname: Banjo-Kazooie (U) (V1.0) [!]
Core: Name: Banjo-Kazooie       
Core: MD5: B29599651A13F681C9923D69354BF4A3
Core: CRC: A4BF9306 BF0CDFD1
Core: Imagetype: .z64 (native)
Core: Rom size: 16777216 bytes (or 16 Mb or 128 Megabits)
Core: Version: 1448
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console: using Video plugin: 'GLideN64' v2.0.0
UI-Console: using Audio plugin: 'Mupen64Plus SDL Audio Plugin' v2.5.0
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.5.0
UI-Console: using RSP plugin: 'Hacktarux/Azimer High-Level Emulation RSP Plugin' v2.5.0
Core Warning: Fallback for Video plugin API (02.02.00) < 2.2.0. Resizable video will not work
Input: 0 SDL joysticks were found.
Input: N64 Controller #1: Forcing default keyboard configuration
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Mupen64Plus SDL Input Plugin version 2.5.0 initialized.
(II) Setting video mode 1920x893...
Core: Setting video mode: 1920x893
Could not open font /usr/share/fonts/truetype/freefont/FreeSans.ttf
Audio: Initializing SDL audio subsystem...
Core: Starting R4300 emulator: Dynamic Recompiler
Core: R4300: starting 64-bit dynamic recompiler at: 0x7fdc998c59d0
Core Status: Stopping emulation.
Core: R4300 emulator finished.
Core Status: Rom closed.

**Comment by gourdcaptain** [comment] 2016-12-28 03:08
[mupenlog.txt](https://github.com/gonetz/GLideN64/files/674963/mupenlog.txt)
Verbose log of the same issue.

**Comment by loganmc10** [comment] 2016-12-28 03:09
This is because GLideN64 is using a bit of "old school" OpenGL code. You can work around this by doing:

```export MESA_GL_VERSION_OVERRIDE=3.3COMPAT```

Before launching mupen64plus 

You can also try RetroArch + GLupeN64, which is a RetroArch core that uses a modified version of GLideN64 that uses modern OpenGL code

**Comment by gourdcaptain** [comment] 2016-12-28 03:11
Okay, it works for me with that. Could you throw a note in the readme or other documentation on this?

**Comment by gonetz** [comment] 2016-12-28 03:35
@loganmc10 So, new mupen64plus requires core 3.3. ?
Is it enough to switch to VBO for vertex data instead of using client side data? Or something else is required for core 3.3 compatibility?

**Comment by loganmc10** [comment] 2016-12-28 03:43
It's not mupen64plus that requires core 3.3, its Mesa. Any Linux user that uses Mesa (most of them, besides the ones that use the proprietary Nvidia driver), will run into this issue.

And yes, using VBO instead of client side data is the only thing left to be done to properly support the core profile. You can see how I accomplish this in GLupeN64 here: https://github.com/loganmc10/GLideN64/commit/d5f3601b5431f41e73aa9b16525ee8153c46c8de

That commit actually does 2 things, it replaces glTexImage2D with glTexStorage2D, which isn't required so you can ignore those bits, but the other part is replacing client side arrays with VBO's.

I found that client side arrays are still the fastest method unless the driver supports ARB/EXT_buffer_storage, so that implementation will use client side arrays on mobile devices that don't support EXT_buffer_storage, since GLES still allows client side arrays.

On desktops it never uses client side arrays (since the core profile doesn't allow it), so it uses ARB_buffer_storage if it can, and if it can't, it uses GL_MAP_UNSYNCHRONIZED_BIT + glMapBufferRange.

So it's a bit of a mess, but that is the best method I could come up with to support modern GL code and still make it fast.

**Comment by gonetz** [comment] 2016-12-28 04:03
I use VBOs in my experimental_vbo branch. These buffers are in fact immutable.
As I understand, I can just replace glBufferData by glBufferStorage (if it is supported of course) and everything will work as before, only (probably) faster.

**Comment by loganmc10** [comment] 2016-12-28 04:34
It's not quite that simple. glBufferStorage allows you to create the buffer with GL_MAP_PERSISTENT_BIT. This allows you to do a glMapBufferRange to get a pointer to the buffer, but you don't have to do a glUmapBuffer before you draw. You keep it mapped forever. So when it comes time to update the buffer, you just write the data to that pointer and issue the draw call, no glBufferSubData.

The real problem is glBufferSubData, that call is a "blocking" call, because OpenGL needs to be sure that you aren't over-writing data in the buffer that hasn't been used yet. With glBufferStorage and GL_MAP_PERSISTENT_BIT, you are saying "trust me", and you need to make sure that you don't overwrite data that hasn't been used by GL yet (https://www.khronos.org/opengl/wiki/Sync_Object). In GLupeN64 I just make the buffer storage quite large, and I use a "ring buffer" approach (keep incrementing the offset inside the buffer, when I get to the end, I start over. I just make the buffer large enough that by the time it makes it's way around the buffer, more than 3 frames have happened, so it won't be overwriting any useful data)

Anyway I don't know if I did a good job explaining that, the OpenGL wiki has a section on this topic:

https://www.khronos.org/opengl/wiki/Buffer_Object_Streaming#Persistent_mapped_streaming

**Comment by gonetz** [comment] 2016-12-28 04:56
Thanks for explanation.

I use similar approach  - large VBO buffer, which can hold vertices for several Draw commands and "ring buffer" approach. glBufferSubData updates part of the buffer, which already should not be in use on server side. I read, that glBufferSubData is blocking only if it is trying to update part of buffer, which is currently in use by pending Draw commands.

**Comment by loganmc10** [comment] 2016-12-28 05:19
I think the problem is that it doesn't really know what parts of the buffer might be in use/needed,  so it has to flush the pending draw commands

**Comment by gonetz** [comment] 2016-12-28 07:05
You might be right. Another advice for VBO performance was to use double buffering: fill vertices for next frame in one buffer, use another one for current frame drawing. I don't see how to make it in my case.

**Comment by orbea** [comment] 2017-01-09 17:19
@gonetz As this is a rather large issue for anyone using mesa drivers it would be really cool this could be fixed in upstream GLideN64. However it should be noted that this also needs to be fixed in mupen64plus's OSD and unlike GLideN64 that doesn't have a working fix as seen in GLupeN64 and @loganmc10 's GLideN64-vbo branch. As to why this is a problem, please see these two issues.

https://github.com/loganmc10/GLideN64/issues/1
https://github.com/mupen64plus/mupen64plus-core/issues/193

**Comment by loganmc10** [comment] 2017-03-20 02:04
This is fixed now

**Comment by gonetz** [comment] 2017-03-20 03:24
Good.

**Closed by gonetz** 2017-03-20 03:24 UTC

**Comment by ibrokemypie** [comment] 2017-08-09 08:50
this is still an issue for me, thought the export workaround works...
this is also on arch linux from aur

**Comment by orbea** [comment] 2017-08-10 01:49
Update your GLideN64, the package in aur is from before this was fixed.

**Comment by ibrokemypie** [comment] 2017-08-11 11:46
@orbea
I installed the -git package (https://aur.archlinux.org/packages/mupen64plus-video-gliden64-git/) which should be the latest commit as of today, and still not working for me

**Comment by orbea** [comment] 2017-08-11 13:57
That is not true, the mupen64plus-video-gliden64-git package is even older...

Look at the PKGBUILD file.
```
pkgname=mupen64plus-video-gliden64-git
pkgver=5e56691
```
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mupen64plus-video-gliden64-git

Its building commit 5e56691 which is from 2015 while this issue was fixed in early 2017...

**Comment by ibrokemypie** [comment] 2017-08-11 14:02
@orbea git packages on the aur do not have that version updated, as they build whatever is available on git at the time of installation.
that there is generated by 
```

pkgver() {
  cd $_gitname
  echo $(git describe --always | sed 's/-/./g')
}
```
during the build, and so the version in that file is meaningless

**Comment by orbea** [comment] 2017-08-11 14:11
Good point, its been a while since I used arch. However if that is true I question why you are having this issue still? It has been fixed for most of this year. Can you confirm this by building GLideN64 manually from the git repo?

That said you will get much better results using a libretro n64 core, GLideN64 has never worked well with mupen64plus upstream. The mupen64plus-libretro core (Formally GLupeN64) which uses GLideN64 still works a lot better despite not having a current maintainer...
