### ISSUE TITLE
Legend of Zelda OoT- vanishing road texture

### ISSUE THREAD

**Issue by Kidboy17** [gonetz/GLideN64#1754] opened 2018-03-15 07:08 UTC
Using Project 64 2.3.2.3 with latest GLideN64 WIP. As soon as you leave Kokiri Forest and start on the dirt path of Hyrule field, the dirt path starts to disappear behind you. I have tried with default settings and with non-default and still happens. Here are some screen shots.

![gliden64_the_legend_of_zelda_002](https://user-images.githubusercontent.com/37382324/37448742-dbd6d392-27e4-11e8-8e71-2cd60053533f.png)

![gliden64_the_legend_of_zelda_001](https://user-images.githubusercontent.com/37382324/37448759-e6067dea-27e4-11e8-9674-d3afb8594d56.png)

![gliden64_the_legend_of_zelda_003](https://user-images.githubusercontent.com/37382324/37448764-ed5c3382-27e4-11e8-9b11-67f993c2be6c.png)

**Comment by AmbientMalice** [comment] 2018-03-15 08:42
Isn't this how a real N64 behaves?

**Comment by OldGnashburg** [comment] 2018-03-15 08:57
I've recently played OoT on my Nintendo 64 on a CRT, it does exist but it isn't this pronounced and you literally have to f*ck around with the camera to see it behind you.

**Comment by loganmc10** [comment] 2018-03-15 13:07
Duplicate of https://github.com/gonetz/GLideN64/issues/541

**Comment by theboy181** [comment] 2018-03-15 13:45
I have seen this on the real hw. I am not sure if this is the same exact issue but it can happen. It’s more noticeable in HLE I would imagine.

**Comment by loganmc10** [comment] 2018-03-15 14:25
It can happen on real HW, but it is much more severe in GLideN64, especially at higher resolutions. In fact, I can't get this to happen at 640x480, but if I switch to full screen, it happens constantly.

@gonetz I believe there is a better way to fix this than glPolygonOffset. See this commit: https://github.com/gonetz/GLideN64/pull/1747/commits/d13d2153dbb5cd750d2efe72b48be9e4a64bcfe9

Instead of relying on glPolygonOffset, which seems to have different results at different resolutions, and on different hardware, do this:

When you write to gl_FragDepth, just offset the depth there. Of course this only works with fragment depth writing enabled, so you'd need glPolygonOffset as a fallback, in my testing, this fixes this issue with the roads in Zelda, no matter the resolution.

**Comment by OldGnashburg** [comment] 2018-03-18 08:35
@theboy181 This does technically happen on hardware, but it us WAY less noticeable and you have to manipulate the camera to notice it, and it doesn't make such large chunks of the texture disappear. So this is only partially accurate.

**Comment by gonetz** [comment] 2018-03-22 10:41
@loganmc10 Could you make commit which applies this "Emulate PolygonOffset" when write to gl_FragDepth is supported? After merge of "Disable clipping using Vertex shader" PR of course.

Also, since it is depth compare issue, "N64 depth compare" option can help there. Have you tried it?

**Comment by loganmc10** [comment] 2018-03-22 18:08
It still happens with N64 depth compare, but it's farrr less severe at high resolutions. Probably a lot closer to a real N64, since it sounds like it happened on occasion there as well.

**Comment by loganmc10** [comment] 2018-03-23 15:27
@gonetz https://github.com/gonetz/GLideN64/pull/1763

**Comment by gonetz** [comment] 2018-03-24 11:04
closed as duplicate.

**Closed by gonetz** 2018-03-24 11:04 UTC
Labels: duplicate
