### ISSUE TITLE
 2 zelda oot problems

### ISSUE THREAD

**Issue by ProtomanX** [gonetz/GLideN64#1521] opened 2017-07-05 16:02 UTC
1st using the latest version of glideN64 and this happens.
![zelda oot sun texture problem](https://user-images.githubusercontent.com/15960656/27872951-20366336-6170-11e7-8d13-07f21fb8c97d.PNG)
this never happen in the glide64 or the glide64 napalm wx version
all the other textures load properly aside from the sun texture and was wondering why is this a problem now?
2nd why is when using per-pixel lighting slower in fullscreen then windowed. my desktop computer is a beefy machine that can run games like devil may cry 4 special edtion on max settings just fine so per-pixel lighting on your plugin shouldn't be an issue but it is. is there any updates in like the wip builds that supposedly fixes these 2 issues?

**Comment by AmbientMalice** [comment] 2017-07-05 16:16
The texture pack you are using is likely at fault.

**Comment by theboy181** [comment] 2017-07-05 23:39
The issue is probably due to the fact that @gonetz needs to look at the CRC calculations that are getting generated for its textures. I have reported this issue, and have stopped in my tracks from developing any Hi Res texture packs until its sorted. MK64 has over 5 different CRC's that get calculated for the same texture in some of my work. 

I'm willing to bet this is related to the same issue.

**Comment by AmbientMalice** [comment] 2017-07-06 00:42
@theboy181 that sounds right.

**Comment by gonetz** [comment] 2017-07-06 05:40
Texture pack problems: I fixed issues reported in #1341 and #1286
Some bugs may remain. Sun texture is a good case to check.

Performance issue. Fullscreen resolution usually higher than windowed one. Per-pixel lighting is pretty complex set of calculations made, yes, per pixel. If you use 4K resolution, it can give serious load on GPU. Besides, mip-mapping shader, blending shader, N64 depth compare (if enabled) - all these programs calculated per pixel. N64 games are not simple at all, when emulated properly.

**Comment by theboy181** [comment] 2017-07-06 06:45
Is the problem with the crc's fixed as well then?

**Comment by gonetz** [comment] 2017-07-06 10:34
Obviously not all problems with crc are fixed. For example, reported problem with sun texture most likely caused by wrong crc.

**Comment by theboy181** [comment] 2017-07-06 15:48
Sorry, I assumed that the issue was crc creation and I figured that if it was addressed in one situation it would be fix for all. Are crc's created in different methods?

**Comment by gonetz** [comment] 2017-07-17 09:28
checksum calculation algorithm is the same for all textures. The problem is that Rice's method uses different way of texture size calculation. I reproduced it in GLideN64, but probably some discrepancy remains. Wrong texture size detection leads to wrong amount of bytes send to checksum calculation and results in wrong checksum.

**Comment by gonetz** [comment] 2017-11-03 03:24
The problem with hd textures of sun in Zelda OOT is fixed.

**Closed** 2017-11-07 05:56 UTC
