### ISSUE TITLE
Blast Corps not woring with FB emulation on

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#248] opened 2015-02-20 02:05 UTC

**Comment by Aquatakat** [comment] 2015-02-22 03:13
I think this is a duplicate of this: https://github.com/gonetz/GLideN64/issues/125

**Comment by theboy181** [comment] 2015-02-22 03:31
I'm not sure. I think shadow are working though just weird buggy screen and eventual crash.

**Comment by olivieryuyu** [comment] 2015-03-21 08:10
duplicate please close ticket!

**Closed** 2015-03-21 18:14 UTC

**Comment by theboy181** [comment] 2015-04-27 14:15
fixed from todays release
