### ISSUE TITLE
Stuttering in Android when compiling shaders

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#693] opened 2015-08-30 19:51 UTC
Compiling shaders in the Nexus Player seems to cause stuttering. I can see this based on logcat output with debug that I added that happens when compiling shaders. The times we compile seem to coincide with stutters on the screen.

Is there any way to prevent so much shader compiling? Maybe compile all possible iterations at startup?

**Comment by gonetz** [comment] 2015-09-27 05:19
Desktop version compiles some fragments at startup. GL ES does not allow to have several fragments in one shader program, so each fragment shader compiles all the code.

I have plans to implement a persistent storage for compiled shaders using glProgramBinary, which is available for GL ES 3. With such a storage each shader will be compiled only once and then instantly available in any other game, which uses the same combiner.

**Comment by gonetz** [comment] 2015-09-27 12:24
I've implemented persistent shader cache:
https://github.com/gonetz/GLideN64/commit/3bbbf361fd9e6e9c1417200487f178de34e5a9e0

UI support added for mupen64plus only. It works on my PC. It also should work for GL ES 3 devices. I can't test it since new config option must be supported by mupen64plus-ae.

**Comment by fzurita** [comment] 2015-09-27 12:29
Cool, I'll add support for the config parameter some time tonight.

**Comment by gonetz** [comment] 2015-09-27 12:40
Do you have GLideN64 forum access?

**Comment by fzurita** [comment] 2015-09-27 12:41
No

**Comment by gonetz** [comment] 2015-09-27 12:53
Bad. Ok, I'll copy my message here:

I've implemented new feature, which may improve performance : shader storage.
The idea is simple: save compiled shader programs into a file before exit, load shaders from file on start.
Next time you start a game, all previously compiled shaders will be available for you, so game will run more smooth.
Since binary representation of OpenGL shader can differ for various vendors and even for various driver versions, this file is generally not interchangeable between users.

Since it is experimental feature, user interface implemented only for Mupen64Plus.
New option available for you: ShaderStorage with 3 possible values:
0 = the feature not used
1 = one shader storage will be used for all games. Combiners sets for most of games are intersected, thus shader compiled for one game can be used in another.
From the other side, total number of combiners exceeds 10 thousands and reading/writing all of them will take time, making pauses on start and exit.
2 = use separate shader storage for each game.

Sources:
github.com/gonetz/GLideN64/commit/3bbbf361fd9e6e9c1417200487f178de34e5a9e0

Windows binary:
drive.google.com/file/d/0B0YqMPjGo3B2SFhPSEVYZ2YxRDg/view?usp=sharing

**Comment by fzurita** [comment] 2015-09-27 14:00
How much memory would it take to load 10,000 different iteration of shaders at startup? #2 seems like a better option for mupen64plus-AE. I'll make that the default.

**Comment by gonetz** [comment] 2015-09-27 15:33
Circa 30kb per shader program.

**Comment by fzurita** [comment] 2015-09-27 15:35
Assuming 30000 bytes and 10000 shader programs, I'm getting 286MB.

**Comment by gonetz** [comment] 2015-09-27 15:39
If each game will use its own storage, destination folder will be full of these files. Need to create special subfolder for shaders.

**Comment by fzurita** [comment] 2015-09-27 15:45
Yep, I'll try it with Mupen64Plus-AE tonight (about 12 hours from now).

**Comment by fzurita** [comment] 2015-09-28 04:15
Gonetz, must one still donate to get access to your forum?

**Comment by gonetz** [comment] 2015-09-28 04:30
Donations are closed.
I'm not admin on the forum; not sure about current registration policy.

**Comment by fzurita** [comment] 2015-09-28 04:40
I created a branch for this in my personal mupen64plus ae fork. Right here:

https://github.com/fzurita/mupen64plus-ae/tree/shader_cache

I've been running this with no issues so far, but I'm not convinced it's working since I'm not seeing any files generated anywhere.

**Comment by gonetz** [comment] 2015-09-28 04:54
It is stored in the path returned by ConfigGetUserCachePath() API function.

**Comment by fzurita** [comment] 2015-09-28 04:56
Ok, I found the problem, Adreno 330 does not support the GL_ARB_get_program_binary extension.

**Comment by gonetz** [comment] 2015-09-28 05:03
I guess, I know why it does not work: swprintf most likely does not work on Android. Need to rewrite that part: convert result of api().GetUserCachePath(strIniFolderPath) to char* with wcstombs and use normal sprintf.

**Comment by gonetz** [comment] 2015-09-28 05:04
> Adreno 330 does not support the GL_ARB_get_program_binary extension.

:( Ok, I'll check it on my NV Shield

**Comment by fzurita** [comment] 2015-09-28 05:05
Hmm.... something is wrong. I printed out all the extensions, and I see GL_ARB_get_program_binary printed as one of the supported extensions.

I don't think the isExtensionSupported method is working correctly.

**Comment by fzurita** [comment] 2015-09-28 05:08
Ok, never mind, I mis-read the extension list. We have GL_**OES**_get_program_binary not GL_**ARB**_get_program_binary

**Comment by fzurita** [comment] 2015-09-28 05:19
For reference, here is where stuff is getting written in android:

/storage/emulated/0/mupen64plusae-v3-alpha/CoreConfig/UserCache/mupen64plus//GLideN64.eb4d37c1.shaders

I'll try to switch it to the mupen64plus-ae folder instead.

**Comment by fzurita** [comment] 2015-09-28 05:26
The files seem to be generating correctly.

**Comment by fzurita** [comment] 2015-09-28 05:38
Hopefully it's not placebo, but I'm not seeing any stuttering any more. Time will tell for sure.

**Comment by fzurita** [comment] 2015-09-28 05:55
i updated the branch i made

**Comment by gonetz** [comment] 2015-09-28 09:43
Please make a pull request with your changes

**Comment by fzurita** [comment] 2015-09-28 10:02
It's just that.

**Comment by gonetz** [comment] 2015-09-28 12:39
Good, thanks!

**Comment by gonetz** [comment] 2015-09-29 12:38
I've made lots of changes to the shader_cache branch:
- correct query for get_program_binary extension for Android.
- EnableShaderStorage option is now boolean. If Shader storage is enabled, it is enabled per file.
- All .shaders files goes into Shaders subfolder of the folder returned by ConfigGetUserCachePath() API function. I needed filesystem functions for that, so
- osal filesystem functions from GLideNHQ are now made as separate library. I've updated project files for Visual Studio and for cmake. Android make file **need similar corrections**.

Please made corrections in your repo and test it. Until that I can't put these changes to the master, because build for mupen64plus-ae will be broken.

**Comment by fzurita** [comment] 2015-09-29 12:41
I'll update the branch and try this tonight.

**Comment by gonetz** [comment] 2015-09-29 12:47
thanks!

**Comment by fzurita** [comment] 2015-09-30 03:55
Ok, I got it all compiling after messing around with all the make files. It still seems to work as expected. It is also creating a subdirectory called Shaders in the UserCache directory.

**Comment by fzurita** [comment] 2015-09-30 03:56
And here is my latest branch with your changes if you want to try it:

https://github.com/fzurita/mupen64plus-ae/tree/shader_cache

**Comment by gonetz** [comment] 2015-09-30 06:42
Good, thanks!

**Comment by gonetz** [comment] 2015-09-30 14:09
Seems to work despite the fact that my _cutLastPathSeparator function does not work on Android.

The version works unstable though. If I restart a game, it often crashes. Crash in Zelda OOT can reset my device. I put log string to check that shader storage file loaded without exception:
```
bool CombinerInfo::_loadCombinersCache()
{
...
	catch (...) {
		LOG(LOG_ERROR, "Can't open shader storage: %s\n", fileName_c);
		m_shadersLoaded = 0;
		return false;
	}
```
but I never saw it in adb log. That is the new functionality seems to work as expected.

**Comment by fzurita** [comment] 2015-09-30 18:08
What's crashing? The front end or your plugin?

**Comment by waltzz92** [comment] 2015-10-01 22:16
Is it possible for a shader cache user interface to be created for Zilmar spec (Project64)? When I use GLideN64, I get stuttering that goes away over time, but comes back when I start playing again. A shader cache would solve the issue.

**Comment by gonetz** [comment] 2015-10-02 17:05
@fzurita Both. Sometimes game closed right after start, sometimes emulator closed. Zelda OOT causes my phone to restart. It's does not happen all the time, and since emulator currently in alpha stage, it's probably normal.

@waltzz92 Sure it's possible. Currently it has status of experimental feature. I'll add it to GUI when it will go to master.

**Comment by fzurita** [comment] 2015-10-02 17:09
It sounds like we could be having dynarec issues.

**Comment by waltzz92** [comment] 2015-10-03 02:17
@gonetz I tested all of my games with your mupen64plus shader cache build. Everything worked well on my end. No issues.

**Comment by gonetz** [comment] 2015-10-03 12:12
Great. I need some time to prepare Zilmar build.

**Comment by gonetz** [comment] 2015-10-03 15:16
Zilmar build to test:
https://drive.google.com/file/d/0B0YqMPjGo3B2SzNkNHgtT3VDb0U/view?usp=sharing

**Comment by oddMLan** [comment] 2015-10-03 19:49
Tested Zilmar build

Lighting gets bugged in DK64 if you
-1. Run the game to let GLideN64 generate the shader cache
-2. Open the Settings and enable hardware lightning

Result
![shader cache bug](https://cloud.githubusercontent.com/assets/7278372/10264778/87a7f122-69cb-11e5-8902-dfb904f852c6.png)

-If you disable the Hardware Lightning, it becomes normal again.
![normal](https://cloud.githubusercontent.com/assets/7278372/10264795/fb9dc26e-69cb-11e5-992e-b769ef38f4dd.png)

-Try to enable it again, lightning becomes bugged again.

-3. Close Project64 and delete the "Shaders" folder that GLideN64 generated
-4. BEFORE running the game, enable Hardware Lightning in the Settings.
-5. Now it works correctly.

![hardware](https://cloud.githubusercontent.com/assets/7278372/10264797/0ee86356-69cc-11e5-94b2-233b53ccce5e.png)

-Disable Hardware Lightning while running the game, gives the second picture result, no issue.
-Enable Hardware Lightning again and it gives the third pic result, working as intended.

Maybe GLideN64 should regenerate the shader cache if enabling Hardware Lightning? Or should always generate a shader cache contemplating Hardware lightning in the code, regardless whether it's enabled or not.

Or it's just other kind of bug.

Note that this doesn't happen using rev.5ca35ad from the master branch I compiled myself. But it doesn't have the shader storage functionality. 

If you have disabled the Shader Storage option in the config while using this test build, the lightning bug doesn't trigger.

Well, at least we know for sure that the Shader Storage is working in the Zilmar builds :smile:

**Comment by oddMLan** [comment] 2015-10-03 20:06
Also, Anti-aliasing is broken in this test build
Setting any anti-alasing level for Conker's Bad Fur Day gives you this result
![creepy](https://cloud.githubusercontent.com/assets/7278372/10264872/a530e764-69ce-11e5-83ec-704e9b630a6b.png)

The breakage doesn't happen with DK64... until you disable shader cache and re-enable it
![what the fuck](https://cloud.githubusercontent.com/assets/7278372/10264890/73edae2a-69cf-11e5-8cb9-8d6b0ce2d9f4.png)

Did you compile it with the old code before commit 05e62b7ffda2899efed3f89f9747f3285bbf06ae ?

**Comment by AmbientMalice** [comment] 2015-10-04 03:44
Out of curiosity, will the Zilmar version shader caching have any noticable benefits in regards to stuttering or such? I notice DK64 tends to stutter during the logo spin, but the cause is unclear.

**Comment by oddMLan** [comment] 2015-10-04 03:52
>I notice DK64 tends to stutter during the logo spin
That used happen to me, but not anymore with this version.

Try with AI = 0  and FAT On and Azimer's XA2 Audio

I haven't determined if it's because these settings or because the shader cache.
It didn't seem to stutter regardless the Shader Storage was enabled or not when I did the previous tests.

**Comment by AmbientMalice** [comment] 2015-10-04 03:59
>Try with AI = 0 and FAT On and Azimer's XA2 Audio

99% sure it does it with those settings. The tricky thing is that if you boot DK64, stop it, and then restart, it doesn't stutter. Closing PJ64 itself and starting DK64 again, there's a good chance of stutter.

Unpredictable stuttering is very bad from a netplay support perspective.

**Comment by oddMLan** [comment] 2015-10-04 04:04
Literally just tried what you said it would generate the stutter and it doesn't stutter for me. Weird

**Comment by gonetz** [comment] 2015-10-04 05:02
@oddMLan Thanks for the testing. Yes, some functions, including hardware lighting, are included to shader only when corresponding config option is enabled. Kind of optimization. It works without shader storage because plugin reset all GL content on settings change, thus shaders re-compiled in accordance with the current settings. Enabling shader storage causes the problem, because shader in storage does not correspond current settings.

I see two ways to solve the problem:
* always include everything to shader program, that is make it compatible with any config settings.
* reset shader storage on settings change.

I think the second way is better. Making uber-shaders will cause lots of overheads.

Regarding AA - yes, this branch does not include commit 05e62b7.

**Comment by oddMLan** [comment] 2015-10-04 05:49
What you said sounds reasonable. Anyway, the shaders are a couple of hundred kilobytes in size, and that can add up very quickly with lots of games.

Just a thought, maybe the "shaders" folder should be inside the "cache" directory. Makes sense in the sense that, the compiled/stored shaders could be called, shader cache, right?

**Comment by gonetz** [comment] 2015-10-04 07:27
"cache" directory is for hd textures cache files. I don't want to put shaders cache to the same folder. Currently you may remove all shader storages by removing Shaders folder, and it will not touch your other data.

**Comment by gonetz** [comment] 2015-10-05 16:56
Branch updated:
https://github.com/gonetz/GLideN64/commits/shader_cache

New binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2cGpuSno2em5sSkU/view?usp=sharing

**Comment by fzurita** [comment] 2015-10-05 17:06
I'll try this tonight on Android

**Comment by gonetz** [comment] 2015-10-05 17:08
Good, thanks in advance.

**Comment by gonetz** [comment] 2015-10-05 17:29
I forgot to merge master to this branch to have AA fixed. Done.

New binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2ZXJnUllDTF9KUGM/view?usp=sharing

**Comment by fzurita** [comment] 2015-10-06 03:34
@gonetz there is currently a build error in the GLES2 version. You forgot to rename _saveCombinersCache and _loadCombinersCache to the new versions.

**Comment by gonetz** [comment] 2015-10-08 16:19
Good, thanks! I'll fix the build error and push it to master.

**Comment by gonetz** [comment] 2015-10-08 17:50
Done. Can we close it?

**Comment by fzurita** [comment] 2015-10-08 20:48
Sure, it looks pretty good to me.

**Closed** 2015-10-08 21:21 UTC
