### ISSUE TITLE
[Mupen64Plus] Gauntlet Legends doesn't boot.

### ISSUE THREAD

**Issue by Papermanzero** [gonetz/GLideN64#552] opened 2015-05-24 18:31 UTC
Description:
With Mupen64Plus Gauntlet Legends cannot be started. Independent of setting and independent of HLE or LLE mode, the game doesn't start and the plugin is going to freeze. 

System: Windows 7
Frontend: M64Py 2.2
Graphic Plugin: GLideN64 1.1 
RSP Plugin: CXD4 SSSE3 or RSP-HLE
Mupen64Plus Version: Build from 2015-05-09 (c7fa0de)
Game: Gauntlet Legends (PAL)

**Comment by AmbientMalice** [comment] 2015-05-25 00:44
The problem is with mupen64plus, not GLideN64 in this case. Only Project 64 can boot Gauntlet Legends/World Driver Championship/Stunt Racer.

Regardless, Gauntlet Legends doesn't work in GLideN64's HLE for PJ64.

**Comment by Papermanzero** [comment] 2015-05-25 09:05
Gauntlet in general requires LLE.
However I don't think its a Mupen64plus issue, because mupen64plus is much more accurate and stable than project64. You can boot and play Gauntlet with the right plugins on mupen64plus (cxd4 together with glide64mk2 -> improved version of the the mupen64plus team). But there are graphical glitches which most likely can be fixed with GlideN64 (no status bar on the bottom). But GlideN64 is freezing the emulator. This is also what the tasks in windows display (GLideN64 doesn't react anymore).

**Comment by AmbientMalice** [comment] 2015-05-25 09:16
>However I don't think its a Mupen64plus issue, because mupen64plus is much more accurate and stable than project64.

That's highly disputable.

>You can boot and play Gauntlet with the right plugins on mupen64plus (cxd4 together with glide64mk2

Running the game with Glide64 is running it in HLE. GLideN64 won't boot the game in HLE for whatever reason in Project 64, so it won't run it in HLE for mupen64plus, either. Running the game in LLE in PJ64 introduces a problem related to CPU-RSP synchronisation (causing freezes), which Project 64 can handle, but mupen64plus cannot.

**Comment by Papermanzero** [comment] 2015-05-25 09:47
You are right. So it's related to CPU-RSP synchro.
Thanks for the explenation. But it's strange that the game doesn't boot in HLE.

**Comment by purplemarshmallow** [comment] 2015-05-25 11:28
but it's already reported #111

**Comment by olivieryuyu** [comment] 2015-08-14 09:59
please closed this duplicate

**Comment by olivieryuyu** [comment] 2016-02-12 09:45
please close it is duplicate

**Closed** 2016-02-12 10:12 UTC
Labels: duplicate
