### ISSUE TITLE
[HLE] Lighting issue

### ISSUE THREAD

**Issue by ichee** [gonetz/GLideN64#1417] opened 2017-03-12 10:42 UTC
Various games have some form of lighting issue, possibly depth related. Sometimes it appears to pop in.
Both of the Zeldas and the first Mystical Ninja seem to be the most obvious of those that I've tested.

![light](https://cloud.githubusercontent.com/assets/22252639/23830972/7b073368-06ed-11e7-8f5a-704491e9c734.gif)

Also, in Majora's Mask, lens flare effect occasionally show through objects, though only for an instant.
Easiest way to see is to start a new three day cycle and go immediately to east clock town, go to the exit with the guard, and go into first person view and look up near the top of the exit and continuously move the camera back and forth. Tested with "Software" depth buffer.
"VRAM" and "Never" completely breaks the effect.

Neither occurs with LLE.

**Comment by ichee** [comment] 2017-03-12 11:16
Upon further testing, I noticed that neither of the above issues occur with Public Release 1.2.

**Comment by ichee** [comment] 2017-03-20 10:52
May be related to issue #778.

**Comment by olivieryuyu** [comment] 2017-09-01 20:42
duplicate of #778. 

@gonetz 

Please close.

**Comment by gonetz** [comment] 2017-09-18 14:34
Not duplicate of #778. @ichee is right, it is regression.  Public Release 1.2 works correct.

**Comment by gonetz** [comment] 2017-09-18 15:28
Bad commit: 6af6e2c17fe7

**Closed** 2017-09-21 16:22 UTC
Labels: Regression
