### ISSUE TITLE
topgear overdrive texture bug

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#2464] opened 2021-02-27 22:14 UTC
![GLideN64_Top_Gear_Overdrive_000](https://user-images.githubusercontent.com/8987490/109401860-8542ee00-7951-11eb-8524-14497cb68fd9.jpg)

**Comment by Squall-Leonhart** [comment] 2021-02-28 01:42
this is a sprite, not a texture.

**Comment by gonetz** [comment] 2021-02-28 14:10
@olivieryuyu is it a regression?

**Comment by weinerschnitzel** [comment] 2021-02-28 17:50
Looks like some textures are getting clamped to the right. 

There is also the right hand side of the speedometer needle that has some artifacts that look like they belong on the left.

Does the use screen coords branch help?

The top of the speedometer looks to be at wrong coords or maybe a different case.

**Comment by olivieryuyu** [comment] 2021-03-01 09:49
the one on the upper right corner is indeed correct

It is a regression compared to gliden64 4 at least

![GLideN64_Top_Gear_Overdrive_002](https://user-images.githubusercontent.com/8987490/109480403-c800e500-7a7b-11eb-8667-6b60a62cf9d5.png)

**Comment by standard-two-simplex** [comment] 2021-03-02 21:10
@olivieryuyu Is this a bug with master or with branch use_screen_coords?

**Comment by Jj0YzL5nvJ** [comment] 2021-03-03 06:51
> Is this a bug with master or with branch use_screen_coords?

Both.

**Comment by gonetz** [comment] 2021-03-13 11:59
@standard-two-simplex could you check that issue? 2D look ugly with current master and with "use_screen_coords" branch even in native resolution.

**Comment by standard-two-simplex** [comment] 2021-03-13 18:44
Yes, I will look into it. See if I can find out anything.

**Comment by standard-two-simplex** [comment] 2021-03-16 21:48
I might have a clue about why the issue is happening.

The game apparently uses LOD to render the 2D HUD. In spite of this, I think the texture has only one mip-map level. It might be possible that the clamp wrap mirror shader uses unintended clamping bounds.

I believe the changes in use_screen_coords only made the issue more visible, but  it was introduced in LOD related code in 4834359, as it has already been pointed out.

**Comment by gonetz** [comment] 2021-03-17 14:31
Yes, gauge textures use LOD.
However, track icon with cars position also has plenty of errors in compare with PR 4.0:
![TGOD](https://user-images.githubusercontent.com/8983092/111484190-185c9000-8768-11eb-8117-ff1220c917bb.png)
It does not use LOD.

**Comment by gonetz** [comment] 2021-03-17 15:19
The problem is in UTextureEngine::update() :
```
	aTexClamp[t][0] = (pTile->flrs - pTile->fuls + 1.0f) * pTexture->hdRatioS - 1.0f;
	aTexClamp[t][1] = (pTile->flrt - pTile->fult + 1.0f) * pTexture->hdRatioT - 1.0f;

```
flrs and flrt ate 7.0, but fuls and fult are 0.5
lrs and lrt are 7, uls and ult are 0.

If use integer tile's coordinates
```
	aTexClamp[t][0] = (pTile->lrs - pTile->uls + 1) * pTexture->hdRatioS - 1.0f;
	aTexClamp[t][1] = (pTile->lrt - pTile->ult + 1) * pTexture->hdRatioT - 1.0f;

```
 this particular issue is completely fixed. I'm not sure, is it the correct fix.

**Comment by standard-two-simplex** [comment] 2021-03-17 18:49
> If use integer tile's coordinates this particular issue is completely fixed. I'm not sure, is it the correct fix in general.

I checked angrylion's sources and he computes clampdiffs using only the integral part. Besides, texel 7 must be used in those textures, and I can't think of another way of making that subtraction at least 7. On top of that, the function clampWrapMirror is meant to handle integral coordinates (even though they are in floating point format) so it makes sense passing an integer to vClamp.

So I say your guess is probably correct, I would go for it.

**Comment by gonetz** [comment] 2021-03-18 09:45
Ok, thanks!
I put that fix to master and rebased your screen coordinates branch.
@olivieryuyu could you test that the issue is fixed in the master?

**Comment by olivieryuyu** [comment] 2021-03-18 12:39
fixed :)

**Closed** 2021-03-18 12:39 UTC
