### ISSUE TITLE
Regression Donald Duck - Goin Quackers

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1816] opened 2018-05-15 02:27 UTC
Game letters will partially disappear if 
![image](https://user-images.githubusercontent.com/9299743/40033320-c2a48750-57ac-11e8-97af-0f6009f6879d.png)
Is set to on.

**Comment by loganmc10** [comment] 2018-05-15 02:31
Duplicate of https://github.com/gonetz/GLideN64/issues/1814

**Comment by gonetz** [comment] 2018-05-16 05:57
Closed as duplicate.

**Closed by gonetz** 2018-05-16 05:57 UTC
Labels: duplicate
