### ISSUE TITLE
Fighting force 64, everything is backwards

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1176] opened 2016-10-15 13:46 UTC
Everything looks backwards for some reason in this game:

![fighting_force-000](https://cloud.githubusercontent.com/assets/11581687/19410503/42e53340-92bc-11e6-95f0-123482d89b52.png)

**Comment by gonetz** [comment] 2016-10-15 14:28
Duplicate of #6

**Closed by gonetz** 2016-10-15 14:28 UTC
Labels: duplicate
