### ISSUE TITLE
BSOD on Windows 10

### ISSUE THREAD

**Issue by phly95** [gonetz/GLideN64#641] opened 2015-07-31 14:07 UTC
Windows 10 Bluescreens when running GlideN64. I've had a chance to try it with both an Nvidia and an Intel GPU and they both have a bluescreen.

**Comment by phly95** [comment] 2015-07-31 14:13
compatibility mode for Windows 8 seems to fix the issue, however Intel cards still have the terrible graphical glitches. There needs to be a fix for Windows 10 though because not a lot of people are likely to try using compatibility mode.

**Comment by WizLizard** [comment] 2015-08-01 10:48
It's not just GlideN64 go to Project64 forums. Also many other emulators are getting Bluescreens.

**Comment by Breadwinka** [comment] 2015-08-03 07:14
I looked into this, its actually all versions of glide cause BSOD. Old Jabo plugin 1.7.0.57 doesnt BSOD, neither does Angrylions RDP.

**Comment by theboy181** [comment] 2015-08-06 03:34
DEP?

**Comment by Breadwinka** [comment] 2015-08-06 06:48
This issue is caused by Project64.

**Comment by GamingHD** [comment] 2015-08-07 17:19
To confirm the above, it happens in Project 64 but neither the older Mupen64 (using the zilmar spec) nor Mupen64Plus experiences the issue. It does appear to be an emulator bug.

**Comment by gonetz** [comment] 2015-08-31 12:27
O, if it is Project64 issue, I close it.

**Closed by gonetz** 2015-08-31 12:27 UTC
