### ISSUE TITLE
Resetting once breaks rendering via transparency of many textures.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#1553] opened 2017-08-19 22:12 UTC
This happens to me on a myriad of revisions for GLideN64 and its very frustrating because I have to re-open the emulator to fix it and soft/hard reset is completely useless as a result.
It appears to be both transparency and/or alpha that gets broken but some stuff that fades still look okay like the Dolby logo seen in one of the screenshots below.

![image](https://user-images.githubusercontent.com/16418716/29490411-77357a06-8500-11e7-8db7-383a860d43c4.png)

![image](https://user-images.githubusercontent.com/16418716/29490417-9bd849b0-8500-11e7-858a-9810d840bb68.png)

![image](https://user-images.githubusercontent.com/16418716/29490421-b751cea0-8500-11e7-9776-2fe5103cc3d3.png)

I have seen glitched rendering in another fashion after restarts before,but it wasn't specifically just entirely breaking transparency.
Zelda Ocarina looks much worse with solar flares happening on every single screen transition instead of normal fading.
I can't use savestates because loading them closes the memory viewer search windows (crash inducing) usually or triggers crashes anyway when trying to take advantage of debugger/breakpoints for code searches as they would've been convenient to undo any game freeze.
Sad thing is GLideN64 is actually faster than Project64 Video/Glide64-wxwidgets by a few frames or so with the right settings.

**Comment by retrobenny** [comment] 2017-08-19 22:20
This issue is not present on Public Release 2.0 so at least there is some info that can help for figuring out the issue.

**Comment by loganmc10** [comment] 2017-08-20 02:10
Lately I've run into a similar issue in Linux. It only happens if I am playing a game, stop the game, and then start a new game. If I close mupen64plus and then re-open it to play a new game, the issue doesn't occur. I thought it was an issue with a recent Mesa update or something, since it doesn't happen for me on Windows.

It could be some kind of Mesa issue, just thought I'd mentioned it since it looks like a similar issue.

![smash_brothers-000](https://user-images.githubusercontent.com/848146/29491472-3e08d4de-851a-11e7-9634-a1db65cc4878.png)

**Comment by AmbientMalice** [comment] 2017-08-20 02:22
This only happens with the new combiner, right?

**Comment by AmbientMalice** [comment] 2017-08-20 02:27
I've done a bit of testing, and I only seem to be able to trigger this in Project 64. (Run Mario Kart 64, quick save, load quick save.) Mupen64plus seems fine.

**Comment by Aquatakat** [comment] 2017-08-20 11:35
I've experienced this in Rush 2049 (smoke sprites) by just opening the config dialogue and changing a thing or two, using PJ64.

**Comment by loganmc10** [comment] 2017-08-27 04:09
This is caused by https://github.com/gonetz/GLideN64/commit/3b9f16e8ddce81be8121ce0a29d743807b6d7a41

I bisected it to that commit. The last time we had an issue like this is was also a program with the Combiner, and it was fixed by this PR: https://github.com/gonetz/GLideN64/pull/1270

I'm having trouble seeing what the issue is with the commit that broke it, but hopefully this helps track down the issue.

**Comment by fzurita** [comment] 2017-08-27 04:34
I think I see a problem... g_cycleType is only updated here:
https://github.com/gonetz/GLideN64/blob/3b9f16e8ddce81be8121ce0a29d743807b6d7a41/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp#L1836

The above only happens when a shader is built. It would probably make more sense if that would happen any time the current shader is switched in ```CombinerInfo::setCombine```.

**Comment by loganmc10** [comment] 2017-09-06 03:48
I submitted a PR with a fix for this issue:

https://github.com/gonetz/GLideN64/pull/1566

**Closed** 2017-09-21 16:22 UTC
