### ISSUE TITLE
Project64 now builds in x64. Need x64 version of GlideN64.

### ISSUE THREAD

**Issue by tony971** [gonetz/GLideN64#716] opened 2015-09-18 20:13 UTC
The x64 version of PJ64 will only work with x64 plugins.

**Comment by tony971** [comment] 2015-09-18 21:20
Here's a copy of x64 PJ64 for testing https://www.dropbox.com/s/5sta8bg31z0cc36/x64.7z?dl=0

**Comment by tony971** [comment] 2015-10-30 01:37
Project64's x64 version is now fully functional. https://www.dropbox.com/s/g6qj0j2whro14jp/Project64.7z?dl=0

**Comment by theboy181** [comment] 2015-10-30 01:47
recompiler CPU?

**Comment by tony971** [comment] 2015-10-30 01:49
No but @cxd4 's RSP exists so it's not a show stopper.

**Comment by theboy181** [comment] 2015-10-30 01:57
I think you prematured all over this post. 

This is not fully functional at all. I have been unable to load any ROMS with LLE, and recompile appears as though its not working..

Maybe rename?

**Comment by tony971** [comment] 2015-10-30 03:33
You did remember to use spconfig.exe to tell the RSP you want to use LLE, right? The GUI buttons are useless with cxd4's RSP. And LLE worked befor HLE did.

**Comment by theboy181** [comment] 2015-10-30 04:21
was unable to get zilmar's plugin to work with HLE or LLE..

**Comment by tony971** [comment] 2015-10-30 19:03
Cool, then it's only a plugin issue.

**Comment by theboy181** [comment] 2015-10-30 19:33
I guess so. So not fully functional then. Too bad.

**Comment by tony971** [comment] 2015-10-30 19:46
If I made a bad x32 plugin, would that make x32 builds not fully functional? No, because functional ones exist.

**Comment by theboy181** [comment] 2015-10-30 20:06
I'm taxing you Tony. Just tickled that you said fully functional. 

I think 64bit being fully functional let alone benafical is a litte far off. There is still much more to do.

**Comment by LegendOfDragoon** [comment] 2015-10-30 20:07
>I think 64bit being fully functional let alone beneficial is a little far off. There is still much more to do.

Agreed.

**Comment by gonetz** [comment] 2015-11-22 06:11
duplicate of #537

**Closed by gonetz** 2015-11-22 06:11 UTC
