### ISSUE TITLE
Texture caching still broken

### ISSUE THREAD

**Issue by Traace** [gonetz/GLideN64#493] opened 2015-05-03 10:36 UTC
Emulator: Project64 2.2.0.3 (Nightlies)
Plugin-Version: GlideN64 Public r 1

Tested Rig:
cpu: AMD-FX-8530 8x 4.3ghz
gpu: AMD R9 280
ram: 8gb ddr3-1888
Windows 8.1 x86

System is way powerful enough

Bugs :
-Texture Packs Path is broken due a typo
(U can't choose the right path, it changes to some wired typo after click "ok")
-Texture Packs .dat doesn't load at all
-Texture Packs .png just load sometimes. In 1 of 10 situations.
-If Texture Packs .png is loading (without any info text) it crashs the emulator after.

I already tested other plugin languages beside german, it's same there too

![untitled](https://cloud.githubusercontent.com/assets/12219341/7444688/a0ce4b46-f190-11e4-809a-2c025febf32a.png)

Please fix, its known as bugged since early release

**Comment by gonetz** [comment] 2015-05-03 10:46
-Texture Packs Path is broken due a typo
It's already reported

-Texture Packs .dat doesn't load at all
.dat file is not GLideN64 format. It will not load.

-Texture Packs .png just load sometimes. In 1 of 10 situations.
Badly created texture packs are not supported. Well created texture packs loaded ok.
Use texture pack checker to test the packs you want to use.

**Comment by Traace** [comment] 2015-05-03 11:11
Yeah pretty easy to answer like that, right? ;)

-Texture Packs Path is broken due a typo
Wasn't reported so far, i searched before.

-Texture Packs .dat doesn't load at all
Got it, but u can add support like Glide64 got back in the days. Idc

-Texture Packs .png just load sometimes. In 1 of 10 situations.
(If i can not swim, it must be the swim cap, ofc what else, again a pretty easy answer)
Well, ghqchk.exe is crashing too at any pack. (That .Net-Framework stuff makes me sick anyway)
However
Texture loaded fine at very first time, i played Zelda without any issues(700mb ram used~). Well, after i paused, it just blackscreen(no info texts anymore) right away after start while still filling my ram (e.g-> your plugin crashed)

**Comment by gonetz** [comment] 2015-05-03 11:28
Easy with you attitude, boy.

Your report is duplicate of #456, where it is described with all details.

>Got it, but u can add support like Glide64 got back in the days. Idc
Glide64 is a different plugin. I never promised to do anything for it.

If you have problems with texture packs load, open new bug report and describe your problem with full details: texture pack, download link, crash scenario. That's way you will have much more chance to get that problem fixed.

**Closed** 2015-05-03 13:43 UTC
Labels: duplicate
