### ISSUE TITLE
Zeldda OOT graphic glitches

### ISSUE THREAD

**Issue by resinate** [gonetz/GLideN64#2124] opened 2019-11-04 08:03 UTC
Version - BizHawk Git (2019/11/02)
desert wasteland shows a nasty huge black bar on top of screen

also random cut offs on textures - defualt and texture packs do this this
https://cdn.discordapp.com/attachments/397553832852455424/640823103227822080/unknown.png
https://cdn.discordapp.com/attachments/397553832852455424/640559637741174804/unknown.png

**Comment by gonetz** [comment] 2019-11-04 10:16
I'm not responsible for BizHawk builds.
Please test my WIP build from #2037
I don't have a savestate for desert wasteland. Intro looks ok for me:
![GLideN64_THE_LEGEND_OF_ZELDA_008](https://user-images.githubusercontent.com/8983092/68113640-d215e080-ff26-11e9-8f49-19606666391c.png)

**Comment by resinate** [comment] 2019-11-04 13:01
lame bizhawk doesnt allow updated dlls ill make a msg for them

**Comment by gonetz** [comment] 2019-11-05 13:40
> which emu does ur glide work on the best?

Depends on the platform. Project64 and mupen64plus for Windows.
mupen64plus for MacOsX and Android.

>what texture pack u using?

AFAIR, this one:
http://www.emutalk.net/threads/56438-2016-OOT-3DS-Pack-for-GlideN64

**Comment by gonetz** [comment] 2019-11-14 05:10
I downloaded [Celda]THE LEGEND OF ZELDA_HIRESTEXTURES.htc pack. Both reported issues reproduced on the current version. However, I can't fix them without original png textures.
Since "T" in "PRESS START" looks correct in [3DS] pack, I suppose it is a problem with [Celda] pack. Sun is incorrect in both packs. @Djipi, can you give me textures for sun in Zelda OOT?

**Comment by GhostlyDark** [comment] 2019-11-16 16:04
Celda and Nerrel's Sun textures for OoT: [Sun.zip](https://github.com/gonetz/GLideN64/files/3854389/Sun.zip)

Djipi never released the png files of the pack, so the only way to get hands on those is to extract them from the HTC cache. Such extracts are available here:
[https://emulationking.com/djipis-2016-cellshade-oot/](https://emulationking.com/djipis-2016-cellshade-oot/)
[https://emulationking.com/djipis-2016-3ds-oot/](https://emulationking.com/djipis-2016-3ds-oot/)

As a side note, Pieschie and Bad Randolph's pack for Super Smash Bros. has similar missing textures due to GLideN64 sometimes excepting different hashes. I think this applies to any old pack that was designed for an old version of GLideN64 or Rice.
[https://emulationking.com/pietschie-bad-randolphs-smash-bros-hd/](https://emulationking.com/pietschie-bad-randolphs-smash-bros-hd/)

**Comment by gonetz** [comment] 2019-11-17 09:57
> Djipi never released the png files of the pack

Early versions of [Celda] pack distributed in png form. Besides, I need not the full pack, just a few textures. I tried to load old [Celda] pack, but it has no issues with sun or text.

> missing textures due to GLideN64 sometimes expecting different hashes

It can be of course. It would be great to have an open-source utility library, which would do all checksum calculation and texture dumping. In that case any graphics plugin with hd textures support could use it and get the same result. Instead of it I need to extract details of implementation from RiceVideo sources.

**Comment by GhostlyDark** [comment] 2019-11-17 12:26
You are right. The 2009 release of the Celda pack is actually structured properly so it released as PNG pack. I somehow totally overlooked this.

This 2009 release doesn't seem to have textures for the Sun, which is probably why it looks normal (vanilla textures). The sun textures I shared above are the ones used by Djipi in later releases I suppose (both Celda and 3DS).

**Comment by GhostlyDark** [comment] 2019-11-17 18:02
Never mind. I stumbled upon the Sun in `04 - Plaine Hyrule/Soleil`
[Sun - Celda 2009.zip](https://github.com/gonetz/GLideN64/files/3855912/Sun.-.Celda.2009.zip)

**Comment by gonetz** [comment] 2019-11-21 10:23
@GhostlyDark Sun textures from Celda 2009 work fine.

**Comment by gonetz** [comment] 2019-12-02 11:03
@resinate, @GhostlyDark, @Nerrel
I think I found the issue with sun textures.

Color combiner for the sun uses 2 textures. The problem part, the top of the sun, uses textures
1. THE LEGEND OF ZELDA#EF9CCF63#4#1_all.png
2. THE LEGEND OF ZELDA#7444ADCB#4#1_all.png

The second texture does not present in texture packs. I dumped these textures, attached.
[dump.zip](https://github.com/gonetz/GLideN64/files/3910874/dump.zip)

I checked existing textures and found that texture `THE LEGEND OF ZELDA#7444ADCB#4#1_all.png` looks like 'THE LEGEND OF ZELDA#BCF206C3#3#0_all.png'. I searched for 'THE LEGEND OF ZELDA#BCF206C3#3#0_all.png' among my dumped textures and did not find it. I dumped textures with RiceVideo, but situation is the same: `THE LEGEND OF ZELDA#7444ADCB#4#1_all.png` is dumped, `THE LEGEND OF ZELDA#BCF206C3#3#0_all.png` is not. I suppose that authors of texture packs dumped textures with GLideN64, when it had mistakes in checksum calculation. So, `THE LEGEND OF ZELDA#BCF206C3#3#0_all.png` texture has wrong CRC, and actually must be renamed to  `THE LEGEND OF ZELDA#7444ADCB#4#1_all.png`. I made it for both Celda and Nerrel's packs and got correct results in Zelda OOT.

**Comment by GhostlyDark** [comment] 2020-02-07 20:33
I just noticed that `THE LEGEND OF ZELDA#7444ADCB#4#1_all.png` and `THE LEGEND OF ZELDA#BCF206C3#3#0_all.png` are (visual) duplicates of each other and are both dumped with GLideN64. I found it while being in the Death Mountain Crater. It is likely that this texture has even more duplicates.

**Comment by gonetz** [comment] 2020-02-08 05:57
These textures have different format. 4-1 is 8bit IM_FMT_I (intensity), while 3-0 is 4bit IM_FMT_IA (intensity-alpha). They can be visually the same, but they are different.

**Closed** 2020-06-28 02:46 UTC
Labels: Waiting for response
