### ISSUE TITLE
QUAKE - transparent walls - Sprite too

### ISSUE THREAD

**Issue by elcorsico** [gonetz/GLideN64#807] opened 2015-11-22 05:34 UTC
hi, in game : QUAKE

transparent walls and sprite are very bad , please resolve this bug team GLN64 ;-)

![2015-11-21](https://cloud.githubusercontent.com/assets/10583821/11322248/f13a62a8-90e2-11e5-8468-04ac75f43171.png)

**Comment by Frank-74** [comment] 2015-11-27 07:07
Also transparent walls/floors in TWINE.
![twine_gliden64](https://cloud.githubusercontent.com/assets/11056843/11435728/7f0cc3f0-94d5-11e5-8350-0aa0b91e281a.PNG)

**Comment by purplemarshmallow** [comment] 2015-11-27 07:25
texture bugs in Quake are known https://github.com/gonetz/GLideN64/issues/328
I don't get any transparent walls not in quake and not in TWINE. Please provide more details or a savestate.

**Comment by Frank-74** [comment] 2015-11-27 09:12
Savestate on demo.  
https://dl.dropboxusercontent.com/u/9498358/n64/007%20-%20The%20World%20is%20Not%20Enough%20%28U%29.pj.zip

Intel (R) HD Graphics, driver date = 17-08-2015.
GLideN64 rev.59f4e2b.

**Comment by purplemarshmallow** [comment] 2015-11-27 09:42
@Frank-74 I think I know your problem. TWINE has N64 depth compare enabled in the ini. It needs OpenGL 4.2 I think. Your GPU does not support it. You need to disable N64 depth compare.

**Comment by Frank-74** [comment] 2015-11-27 09:46
@purplemarshmallow Thanks, yes that fixes it.

**Comment by gonetz** [comment] 2016-01-30 17:09
closed as duplicate of #328

**Closed by gonetz** 2016-01-30 17:09 UTC
Labels: bug, duplicate
