### ISSUE TITLE
roadmap to catch Glide64

### ISSUE THREAD

**Issue by purplemarshmallow** [gonetz/GLideN64#855] opened 2016-02-06 13:34 UTC
If Glide64 looks correct then the issue is collected here. Please comment more issues here because I likely missed something. If Glide64 uses a hack it get it correct i marked it with (hack)

~~#859~~
~~#795~~
~~#790~~
~~#777~~

~~#768~~ (wontfix)
#764

~~#743~~
~~#710~~

~~#682~~
~~#681~~
~~#651~~
~~#648~~
~~#633~~
~~#628~~
~~#625~~
~~#603~~
#600
#585

~~#570~~ (hack)
~~#555~~
~~#547~~

~~#527~~
~~#510~~
~~#495~~
~~#472~~
~~#464~~
~~#444~~

~~#418~~
~~#394~~

~~#391~~
~~#375~~

~~#369~~
~~#368~~ (fixed by native)
~~#366~~ (fixed by native)
#354

~~#342~~ (wontfix)
~~#328~~
~~#325~~
~~#316~~
#315 (hack)
~~#305~~
~~#301~~

~~#283~~
~~#282~~
~~#280~~
~~#274~~
#250

~~#224~~
~~#210~~
#190
#179 (hack)

~~#173~~
~~#171~~
~~#167~~
~~#163~~
~~#161 (hack)~~
~~#159~~

~~#141~~
~~#111~~
~~#99 (hack)~~
~~#71 (hack)~~
~~#6~~

**Comment by AmbientMalice** [comment] 2016-02-07 03:45
These seem to be the most pressing. I would maybe add https://github.com/gonetz/GLideN64/issues/325 but Glide64 only works with the E version, and the U version has FB alignment problems.

The texture scaling issues are a big one. Heaps of games have splash screens with black lines that get worse as you raise resolution. I imagine fixing one would fix them all. GLideN64 is in a fairly impressive state. It's primarily a handful of crucial bugs affecting a wide variety of games. That issue about Wave Racer, for example, is a symptom of the plugin's almost global problems with PAL games.

**Comment by olivieryuyu** [comment] 2016-02-07 08:06
#6 is important as well. All plugin have issue with those games.

**Comment by AmbientMalice** [comment] 2016-02-07 08:18
>#6 is important as well. All plugin have issue with those games.

If Glide64 is broken, too, then it doesn't count. This is a list of issues that GLideN64 suffers but Glide64 doesn't.

**Comment by olivieryuyu** [comment] 2016-02-07 08:32
it is not broken, it works but certainly with a kind of hack

**Comment by purplemarshmallow** [comment] 2016-02-07 15:44
I added them

One problem is that GLideN64's options are too slow. Glide64's hacks are faster

Like in Toy Story 2 GLideN64 needs the expensive N64 depth compare optin just to render the laser charge bar. The z mode comare less hack in Glide64 is much faster.

Also Glide64 has the increase texrect edge hack to fix upscaling related problems like gaps and borders. GLideN64's fixed 2D fixes some of these problems but causes slowdowns again.

**Comment by AmbientMalice** [comment] 2016-02-09 05:09
>Like in Toy Story 2 GLideN64 needs the expensive N64 depth compare option just to render the laser charge bar. The z mode comare less hack in Glide64 is much faster.

IMO, GLideN64 should add a version of this hack so that lower spec PCs can render these games correctly. Currently, if hardware doesn't support GL4.2, there are glitches.

**Comment by purplemarshmallow** [comment] 2016-02-13 15:50
@gonetz you asked me to make this list but I somehow dislike this idea. Does it make sense to fix up all discrepancies with Glide64? This will also involve adding hacks from Glide64. I think that's a bad idea. As you can see this list is so huge and it will be much work. Would be better to put this work into somethig else  like optimized LLE and N64 depth compare.

Would be better to surpass Glide64 instead of trying to catch up everywhere.

Not sure where your priorities are. If you want to fix up everything in this list I will leave this open. But if you agree with me I will stop looking for discrepancies and close this.

**Comment by weinerschnitzel** [comment] 2016-02-13 23:25
Whether HLE is a priotity for some or not, it is a project goal and this list provides great direction for that goal. Might as well keep it open.

**Comment by AmbientMalice** [comment] 2016-02-13 23:53
The vague purpose of this list is to isolate the serious issues that currently prohibit GLideN64 from replacing Glide64. If GLideN64 is going to replace Glide64, it doesn't need to match Glide64 exactly, but rather be in the same vicinity.

HLE bugs that don't affect Glide64.
PAL framebuffer issues.
Depth buffer.

The buggy, slow LLE is another matter. A very important one, but it's not strictly related.

**Comment by gonetz** [comment] 2016-02-14 05:51
I will not work specially on LLE direction anytime soon.
There are several reasons. Most serious are:
* Current HW implementation of LLE triangle is buggy and it causes many annoying glitches. Who will take the task to fix it? LLE can't replace HLE without that task completed.
* LLE speedup task will take more time than I currently have.

Most of issues in the buglist are common for HLE and LLE. Framebuffer emulation, texture handling etc. I need some criteria which issue to take. Glide64 is a good reference point. If a problem is solved with Glide64 than solution exists and known. It is better to start with already solved issues, because otherwise I may just spend my time with no visible effect.

Thus, the list is very useful for me, thanks! Of course, you may stop looking for discrepancies. The list is really large, plus I need to finish other tasks I'm working on.

**Comment by gonetz** [comment] 2016-03-15 05:31
Why #544 is in the list? As I remember, the problem is not fixed with Glide64 as well.

**Comment by AmbientMalice** [comment] 2016-03-15 05:59
@purplemarshmallow Maybe you should cross off all the "native resolution fixed" options and add (fixed by native) to the line?

**Comment by purplemarshmallow** [comment] 2016-03-15 19:19
> Why #544 is in the list? As I remember, the problem is not fixed with Glide64 as well

Yes my mistake Glide64 is incorrect. Most other plugins are correct like Rice Video, Jabo's D3D, z64gl I think I mixed it up somehow

> Maybe you should cross off all the "native resolution fixed" options and add (fixed by native) to the line?

Ok

**Comment by AmbientMalice** [comment] 2016-03-22 12:12
https://github.com/gonetz/GLideN64/issues/633 seems to be fixed now, so cross it off.

**Comment by purplemarshmallow** [comment] 2016-03-22 16:04
This list was created to help gonetz and he can edit it if he wants
But I can also look at it from time to time and cross off some fixed bugs. Not sure what can be rearranged, I think they are in order

**Comment by olivieryuyu** [comment] 2016-03-23 14:34
please add #354

**Comment by olivieryuyu** [comment] 2016-04-09 07:24
please add #625

**Comment by rcaridade145** [comment] 2016-05-08 12:55
Going through all the list it seems like #859 and #651 at least can be closed no?

**Comment by gonetz** [comment] 2016-05-08 14:45
Yes. 
I've closed  #859. 
#651 still has an issue: garbage may appear in the bubble, as on the first screenshot.

**Comment by AmbientMalice** [comment] 2016-05-11 01:07
This is a slight tangent, but I notice that Mario Tennis's swipe transitions seem to work without EnableCopyAuxiliaryToRDRAM now. Can anyone else confirm?

![mariotennis-000](https://cloud.githubusercontent.com/assets/10704701/15167039/7f2c3c2e-1768-11e6-8ead-4b2671f1da3d.png)

**Comment by oddMLan** [comment] 2016-05-11 04:53
Confirmed. Wait, wasn't it working before? (with CopyAuxiliaryToRDRAM on).

**Comment by oddMLan** [comment] 2016-05-11 05:04
Can't reproduce. Are you sure you don't have Custom Game settings enabled? Maybe you added the line to enable copying of Aux buffers to RDRAM.

Also tried using Native res x1 (as you seem to be using judging by the pic you posted) and it doesn't work either. Tried other settings and it only works with EnableCopyAuxiliaryToRDRAM.
Using the latest build from #885

**Comment by olivieryuyu** [comment] 2016-05-11 05:31
#173 should be as well included

**Comment by gonetz** [comment] 2016-05-11 05:52
@AmbientMalice Yes, Mario Tennis's swipe transitions works without EnableCopyAuxiliaryToRDRAM now. Tested with mupen64plus.

**Comment by gonetz** [comment] 2016-05-11 05:52
Included #173

**Comment by gonetz** [comment] 2016-05-11 10:42
@oddMLan Mario Tennis's swipe transitions seems to be fixed by my latest commits. My build from #885 does not include them.

**Comment by oddMLan** [comment] 2016-05-13 10:47
Interestingly, I bisected the commits and found out that https://github.com/gonetz/GLideN64/commit/87f307c3fffc3d5d196f37319b6023bfa8cf8320 fixed the swipe transitions in Mario Tennis.

**Comment by gonetz** [comment] 2016-05-13 11:23
I made that commit without link to a particular problem; I just noticed that place can cause problems and corrected it. Good to know that it was for good :)

**Comment by rcaridade145** [comment] 2016-05-20 13:09
Can't #842 and #958 be closed?

**Comment by Papermanzero** [comment] 2017-09-03 07:20
Several can be closed: #777 #710 #464 #444 #375 #305 #6 

Can features be added to the list? Force bilinear filtering to all textures would be one for example.

**Comment by Papermanzero** [comment] 2017-10-28 13:10
Almost catched glide64.
Following issues can be crossed out from the list, because there are solved:
#71 #444 #464 #394

**Comment by gonetz** [comment] 2017-10-28 14:07
> Can features be added to the list? Force bilinear filtering to all textures would be one for example.

I'd say that no force filtering is a feature of GLideN64.
What else feature of Glide64 are missing in GLideN64?

**Comment by Papermanzero** [comment] 2017-12-21 09:22
I thought it is more. I will look at the features.

**Comment by olivieryuyu** [comment] 2018-12-11 14:01
to be closed?

**Closed** 2019-01-21 04:14 UTC
Labels: Priority-High

**Comment by LegendOfDragoon** [comment] 2019-01-21 05:04
What about #585, #315, #250, and #190?

**Comment by theboy181** [comment] 2019-01-21 16:33
Doesn’t 190 work in other plugins?

**Comment by gonetz** [comment] 2019-01-22 04:20
#190 works in LLE. It may works in hle, if plugin implements software polygon's clipping and has support for N64 clipping box. It was done in Glide64, I don't know about other plugins.
