### ISSUE TITLE
Top Gear Hyper Bike (Wrong Ground)

### ISSUE THREAD

**Issue by schubertguilherme** [gonetz/GLideN64#2188] opened 2020-03-11 13:02 UTC
![55324233-cf668080-5457-11e9-971e-3caaf2d1437d](https://user-images.githubusercontent.com/36903073/76419489-333f3c00-637f-11ea-92ff-c3d2262a15c4.jpg)

Problem textures ground. The problem continue in HLE and LLE render.

**Comment by olivieryuyu** [comment] 2020-03-11 20:59
duplicate

**Comment by gonetz** [comment] 2020-03-12 08:04
Duplicate of #257

**Closed by gonetz** 2020-03-12 08:04 UTC
