### ISSUE TITLE
(Majora's Mask) Glass in Postman House not rendering

### ISSUE THREAD

**Issue by Ceptor101** [gonetz/GLideN64#1941] opened 2018-11-08 02:29 UTC
So I didn't know if I should post this because it's pretty small, but after some testing I noticed that it was actually fixed in past versions.
This happened in Project64, m64p and m64py. In the public release 3.0 and latest WIP build, the glass in the postman house in Majora's Mask would not show up:
![gliden64 3 0](https://user-images.githubusercontent.com/44855256/48173866-bb758300-e2ec-11e8-91cb-dce7b7ae97b8.png)

But in versions 2.0, 1.2 and 1.0 it did show up:
![gliden64 2 0](https://user-images.githubusercontent.com/44855256/48173898-d1834380-e2ec-11e8-8786-21f405139459.png)

Also, just a little side thing, in 2.0 the glass looked a little different when you were a little away from it, better transparency quality I think, and close it would look less triangley but worse transparency quality. But in 1.2 and 1.0 it looked like the close version all the time.

**Comment by gonetz** [comment] 2018-11-09 10:14
It is not a minor issue, thanks for the report.
Could you give a savestate from this place?
I don't remember where Postman House located.

**Comment by Ceptor101** [comment] 2018-11-09 16:06
Of course, here you go: https://drive.google.com/file/d/1BFC6ohhkKrQtyOsqToLoUX3jvu_vYpPY/view

**Comment by matthewharvey** [comment] 2018-11-10 21:35
Reproduced on an Intel HD4000 running Debian testing with the Mesa drivers.

Bisected to being caused by adc2b547e881d792da31575c8e1e502558b0f9e4

On the commit before the above one that broke the glass (haha), the reflections coming off of the glass still definitely don't react well to changes in the camera. The transparency changes are really jarring as the camera moves.

**Comment by matthewharvey** [comment] 2018-11-11 20:38
Never mind. Ignore my bisecting result. I was not properly using the development version of GLideN64.

Which leaves open the question: How did I get it to work at all? I'll do a little more investigation today, and see if I can get it working again, because I went back and forth a few times to ensure that it was this commit that broke it, and the issue went back and forth a few times with me.

**Comment by loganmc10** [comment] 2018-11-11 20:39
Do you have the shader cache disabled? You need to disable it or clear it between tests to be sure you are testing the right shader code

**Comment by matthewharvey** [comment] 2018-11-11 20:52
EnableShadersStorage = False

Is that the one I should be setting? It was true for me, and I think it's been causing me issues all day. It took me forever to figure out that this could be the issue, because I was changing my graphics driver at the same time, which was also causing shader cache problems (which are fixed in the latest version).

Thanks for letting me know you can turn it off! A few minutes ago I started just deleting the folder each time to try and get rid of any errors due to caching.

**Comment by loganmc10** [comment] 2018-11-11 21:43
Yes exactly, always set that to false when testing

**Comment by gonetz** [comment] 2018-11-12 04:05
@Ceptor101 Thanks! It is a HLE issue. The glass looks correct in LLE mode.

**Comment by olivieryuyu** [comment] 2018-11-12 18:33
I need a Pj64 savestate to debug this issue please

**Comment by matthewharvey** [comment] 2018-11-12 22:00
[LoZMM.zip](https://github.com/gonetz/GLideN64/files/2573784/LoZMM.zip)

This one was generated with mupen64plus.

**Comment by Ceptor101** [comment] 2018-11-12 22:36
Olivieryuyu: https://drive.google.com/file/d/1UhiHr8l9vFNb7Vc1iE8h9fvLQ8rW-xMT/view
So yeah, like gonetz said, changing PJ64 to LLE mode does fix the issue.
Is it possible to change GLideN64 to LLE mode in m64p? I tried changing the RSP to cxd4-sse2 but it's doesn't fix the glass issue, so it's probably not LLE with that plugin right?

**Comment by Jj0YzL5nvJ** [comment] 2018-11-14 08:01
On `rsp-cxd4`:
`DisplayListToGraphicsPlugin = True` is HLE
`DisplayListToGraphicsPlugin = False` is LLE

BTW, angrylion's RDP Plus only works using the last one.

**Comment by matthewharvey** [comment] 2018-11-23 03:15
I just checked the latest version. The glass looks good to me.

I wasn't able to compare to LLE, because I wasn't sure which configuration option on mupen64plus to set in the configuration file.

**Comment by olivieryuyu** [comment] 2018-11-28 15:09
Can we close the ticket please?

**Closed** 2018-11-28 15:33 UTC
