### ISSUE TITLE
Goldeneye broken skies

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#1778] opened 2018-03-31 04:42 UTC
After this commit, skies have a strange effect:

https://github.com/gonetz/GLideN64/commit/bdb0f7ca94df7fc127aa6b7190f9494c16f25905

Here is a screenshot after that commit:

![goldeneye-000](https://user-images.githubusercontent.com/11581687/38159722-6c1ba81c-347c-11e8-88d0-661c432a465a.png)

This effect only happens if the player is moving. One thing special about the sky is that it's drawn using LLE commands.

**Comment by gonetz** [comment] 2018-03-31 06:01
Thanks! I'll check it ASAP.

**Comment by gonetz** [comment] 2018-03-31 10:29
@fzurita I can't reproduce it on my PC. Do you have that regression with mobile device?

**Comment by fzurita** [comment] 2018-03-31 12:07
Yep, mobile device.

**Comment by loganmc10** [comment] 2018-03-31 12:29
I'll look into this on Monday

**Comment by gonetz** [comment] 2018-04-17 05:16
Is it fixed now?

**Comment by fzurita** [comment] 2018-04-17 11:06
Yep

**Closed** 2018-04-17 11:12 UTC
Labels: Priority-High, Regression
