### ISSUE TITLE
Banjo Kazooie & Tooie have text corruption with txEnhancementMode 1

### ISSUE THREAD

**Issue by cascardian** [gonetz/GLideN64#1993] opened 2019-01-28 16:16 UTC
It's as shown in the examples below. The build is the x64 one from m64p. It happens consistently with txEnhancementMode 1, "store as is", and not with any other setting of that option. I've replaced the ROM to check whether it was bad and it's not. I've tried everything else one by one, always deleting texture cache and shaders inbetween.

![kazooie](https://user-images.githubusercontent.com/6861423/51794172-4b7ce780-21cd-11e9-8cb7-03b795bac0eb.jpg)
![tooie](https://user-images.githubusercontent.com/6861423/51794173-4d46ab00-21cd-11e9-89d7-2da1bf3b777e.jpg)

**Comment by gonetz** [comment] 2019-01-30 04:08
> It happens consistently with txEnhancementMode 1, "store as is", and not with any other setting of that option.

Confirmed, thanks!

**Comment by retrobenny** [comment] 2019-02-06 08:24
I get that issue in a different way when using 6xBRZ on Android via Mupen64Plus FZ Edition with Banjo-Tooie.

It seems that only the letter i and . and : are affected,this issue has been around for ages on my end.

**Comment by ShareScene** [comment] 2019-02-06 12:49
same problem here

**Comment by gonetz** [comment] 2019-02-19 08:45
Fixed with commit edc81952.
Please test with latest WIP build from #1574

**Comment by ShareScene** [comment] 2019-02-19 19:41
can confirm, fixed.

**Closed** 2019-02-20 04:19 UTC

**Comment by thaumatrope** [comment] 2019-09-27 15:45
The error is caused by cached textures.
Disable them in Options for Mupen (Retroarch) and you are fine to go with this splendid game.
