### ISSUE TITLE
Render Buffer Help

### ISSUE THREAD

**Issue by duckey77** [gonetz/GLideN64#1556] opened 2017-08-25 21:41 UTC
Hi,  this is not an issue.

I am working on an OpenEmu implementation of GLideN64 for the Mupen64Plus-Core.  I am trying to figure out which frame buffer object is the final render frame buffer presented to the emulator to display.

I am currently using m_pCurrent->m_FBO bound just before wnd.swapbuffer in FrameBufferList::renderBuffer.  But it doesn't seem complete, like it's missing depth.  Mario is shown kinda floating in front a tree he is climbing in Super Mario 64.

FrameBufferObject 0 appears blank.

Any help would be appreciated.

Thanks

**Comment by loganmc10** [comment] 2017-08-25 21:57
This is probably the same issue as https://github.com/gonetz/GLideN64/issues/1548

**Comment by duckey77** [comment] 2017-08-25 22:01
I'm not even sure it that is the Main Frame Buffer or not.

Can someone confirm that it is?

**Comment by gonetz** [comment] 2017-09-12 10:17
Render frame buffer presented to the emulator to display is the one, which corresponds to VI regirster *REG.VI_ORIGIN.  This line in FrameBufferList::renderBuffer() gets it:
`	FrameBuffer *pBuffer = findBuffer(rdpRes.vi_origin);
`
m_pCurrent represents current buffer to render into. It can be incomplete on the moment where renderBuffer() called.

**Comment by duckey77** [comment] 2017-09-12 17:11
Thanks gonetz.  Appreciate the response.

**Comment by gonetz** [comment] 2017-09-19 09:36
@duckey77 I close this ticket. Please reopen or open a new one in case the problem is not solved.

**Closed by gonetz** 2017-09-19 09:36 UTC
