### ISSUE TITLE
Mario Tennis on Galaxy S5- reduced FPS since change to play store builds

### ISSUE THREAD

**Issue by kev4cards** [gonetz/GLideN64#1105] opened 2016-09-02 23:52 UTC
In Mario Tennis, I'm experiencing a dip in fps when the ball is on "fire" (surrounded by red or blue). It goes from avg. 25 fps to 11-19 fps in the 3-25 paulscode mupen64plus ae build. It's much slower in the current fz edition (15 fps to 8-11 fps on "fire"). I'm using the gliden64 GLES 2.0 plugin with 800x600 screen resolution on a galaxy s5. GLES 3.0 makes the "fire" black and blocky and does nothing to improve performance. Also, disabling copy color buffer to RDRAM had no effect. Overall, gameplay behaves jittery especially when trying to make a move towards a "fiery" ball.

**Comment by fzurita** [comment] 2016-09-03 01:57
I may have talked to you before. Did you make sure that legacy blending was enabled? The new blending really is hard on performance.

**Comment by kev4cards** [comment] 2016-09-03 03:24
Yeah. The legacy blending was enabled. Also, disabling it doesn't change performance at all, which seems strange. Speaking towards the game's problem, I've noticed that there is no change in behavior/performance between a normal exhibition match and a ring shot mini-game.

**Comment by fzurita** [comment] 2016-09-03 08:39
Do you have any texture enhancements enabled?

**Comment by kev4cards** [comment] 2016-09-03 22:37
Nope. Using them does nothing to the performance. Although, I have encountered a few times now where I would change a setting and resume the game only to find the back scoreboard and serve speed display black. Also, the rings in ring shot mode turn black. I can fix those problems by changing GLES 2.0 to 3.0 then back to 2.0. 

Another thing to note is the game mode and player select screens occasionally are aligned to the left third of the screen in a letterbox, not centered and wide like the rest of the game. 

Finally, I am experiencing some crashing now. It will occur when selecting the icon to start a match and when pressing start during a match.

I wonder if some of these problems are interconnected.

**Comment by fzurita** [comment] 2016-09-03 23:00
I'll look into the crashes. I'm not sure what the cause of the performance issues are. That will be hard to figure out.

**Comment by fzurita** [comment] 2016-09-03 23:01
Have you tried disabling ”Copy color buffer to RDRAM”?

**Comment by kev4cards** [comment] 2016-09-03 23:20
Yeah. I tried that before, and it had no effect.

I know that turning off frame buffer emulation will bring the FPS up to 30 when running around before the serve. Though, the FPS for when the ball is on "fire" (or supposed to be when frame buffer is on) stays at 8-11.

**Comment by fzurita** [comment] 2016-09-04 00:38
One last thing, have you tried reducing resolution to see if that helps?

**Comment by kev4cards** [comment] 2016-09-04 00:55
I guess it helps somewhat. The lowest resolution (160x120) performs at 21-24 fps with a dip to 15-18 fps when the ball is on "fire". As a result, the gameplay is a bit smoother but not where it should be.

**Comment by fzurita** [comment] 2016-09-04 00:56
Ok, thanks.

**Comment by kev4cards** [comment] 2016-09-04 01:03
I totally forgot to mention this. One time, I tried to start up the game from the app's main menu, but I received an error about the core not attaching properly. It might have just been a fluke, but I wanted to pass it along just in case.

**Comment by fzurita** [comment] 2016-09-04 01:35
Weird one. I haven't seen that one yet. I'll keep an eye on it. Since it's such a low occurrence and it didn't seem to hurt anything, I'm probably going to ignore it.

**Comment by fzurita** [comment] 2016-09-04 01:43
Also, I'm able to reproduce the crash when going to the pause menu, so I think a fix should be doable.

**Comment by fzurita** [comment] 2016-09-04 22:50
The crash is pretty nasty, there is no back trace. It seems to be crashing at the kernel. This will be tough to debug.

**Comment by fzurita** [comment] 2016-09-06 02:53
This seems to be crashing only in Adreno based devices. The shield TV is perfectly happy with the pause menu.

**Comment by kev4cards** [comment] 2016-09-07 01:12
Adreno likes to cause trouble. Have you considered cataloging all these issues in a spreadsheet broken down by cpu, gpu, os version, issue type, etc. to see if there is a need to create a patch A for device group A and patch B for device group B? It might be helpful.

**Comment by fzurita** [comment] 2016-09-07 02:42
Yes, I have thought about it. This is kind of handled by the source code itself since we document when we have to take separate paths depending on architecture by using "if/else" statements that have checks for the GPU type.

**Comment by kev4cards** [comment] 2016-10-16 21:55
Update: The play store build from Oct. 12/13th has helped performance some. It's now comparable to the paulscode build from 3-25. Plus, the fire around the ball is fixed on GLES 3.0. The other issues are still present including the pause menu problem (although, I did access it a few times in one play-through).

**Comment by fzurita** [comment] 2016-10-16 22:00
OK, that's good to hear. I'm trying to figure out what's up with the pause menu crashing. It only seems to crash for me in an Snapdragon 805 device, but not with Snapdragon 820 with Adreno 530. They both have the same driver version.

**Comment by kev4cards** [comment] 2016-10-17 01:41
Do you think it might just be the GPU? The game's dip in performance when adding the "fire" to the ball may be too much for the GPU to handle? Likewise, the pause menu might be too much too fast.

**Comment by fzurita** [comment] 2016-10-17 01:43
No idea really. I need to figure out the line of code that is causing the problem.

**Comment by fzurita** [comment] 2016-10-28 04:24
@kev4cards Some good news, I found the fix for the Mario Tennis crashing issues. A fix should be incoming soon.

**Comment by kev4cards** [comment] 2016-10-31 20:58
Sorry about getting back so late. The fix only works for me when I restart the game. If I resume the game, a crash will occur if I press start. Loading a savestate from a restart works okay, but a resume then load causes a crash when pressing start.

On a side note, performance remains the same.

**Comment by fzurita** [comment] 2016-10-31 21:10
Hmm, interesting, sounds like I didn't test every possible scenario. I'll have to check for more errors with that game. I hadn't tested that scenario.

**Comment by fzurita** [comment] 2016-11-02 03:44
@kev4cards I was able to reproduce this. I wonder why it's not fixed when loading a save state.... very odd. No GL errors are happening.

**Comment by fzurita** [comment] 2016-11-02 03:59
@gonetz If you save a state during a match, then restart and then load that save state, do you get any issues?

**Comment by kev4cards** [comment] 2016-11-02 21:19
The issue is fixed when loading a save state from restart but not resume. The screen looks like this when a load a save state from restart then hit start to bring up the pause menu:

![tmp_13567-mariotennis-000-1036980641](https://cloud.githubusercontent.com/assets/21962903/19947854/5dafdad2-a120-11e6-8e40-3cd41857b48f.png)

**Comment by kev4cards** [comment] 2016-11-02 21:25
This is from the 2nd time I brought up the pause menu. The first time showed the character icons underneath the players label. Everything else was the same as above. So, the behavior of the textures are inconsistent. Same can be said for the scoreboard and the bob-ombs on the scoreboard end of the court.

**Comment by gonetz** [comment] 2016-11-03 03:19
I have that issue on desktop sometimes. Icons can be broken when I press pause, and next time they may look ok.

**Comment by fzurita** [comment] 2016-11-03 03:25
Some kind of state of probably being set at restart that is not being set when the game is started from a save state. Since there are no gl errors being produced, it will probably be a pain to find.

**Comment by kev4cards** [comment] 2016-11-03 20:42
I did a little more investigating with the pause screen. The issue occurs with every video plugin. It has to deal with the autosave and the driver, I believe. That said, glide64 and rice can show the pause screen correctly (although, the background is incorrect) when the game is loaded from a restart or restart then load save state.

**Comment by gonetz** [comment] 2016-11-05 07:27
@fzurita it is wrong use of frame buffers. Validity check passes when it should not. Very hard to find and fix indeed.

**Comment by fzurita** [comment] 2016-11-15 21:19
@gonetz Should we close this issue? We already have an issue for Mario Tennis freezing when pausing when starting the app from a save state on Adreno devices. We can also write a new issue for the pause menu being corrupt when loading save states.

**Comment by gonetz** [comment] 2016-11-16 01:17
Ok

**Closed by gonetz** 2016-11-16 01:17 UTC
