### ISSUE TITLE
FPS locked? Vsync not working?

### ISSUE THREAD

**Issue by oCanna** [gonetz/GLideN64#1935] opened 2018-10-19 09:48 UTC
I'm running latest mupen64plus (qt gui) along with latest gliden64 on my kubuntu 18.04 system.
What I've noticed is that while playing Super Mario 64 PAL/EU the fps won't go any higher than 25.

I assume that this is some kind of fps lock?
The problem is that because of this very low fps rate I experience massive tearing on my screen.

Is it somehow possible to remove this fps lock?

**Comment by dankcushions** [comment] 2018-10-19 10:04
PAL version of SM64 was 25fps - that's an internal lock within the game. the NTSC version (USA/JP) will be 30fps which may have no tearing since it's a multiple of 60hz.

**Comment by oCanna** [comment] 2018-10-19 10:29
Thats a little disappointment that the actual frame rate is locked to some internal clock.
Because my screen is already set to 50Hz which is a multiple of 25 I don't think that the NTSC version will be a huge improvement.

As I remember there was no such thing like a locked frame rate with video-rice.
Back in the days with interlaced, analog monitors 25fps my not be an issue, but nowadays this is a real setback. I can't even enable vsync. :(

**Comment by Jj0YzL5nvJ** [comment] 2018-10-19 10:34
If you use Mesa drivers, simply activate TearFree. I do that.

Example:
`xrandr --output DisplayPort-0 --set TearFree on`

**Comment by oCanna** [comment] 2018-10-19 11:29
nvidia here.

I disabled the compositor and vsync seems to work now. 
It's not perfect but at least playable now.

**Comment by Jj0YzL5nvJ** [comment] 2018-10-19 17:40
Some compositors have their own Vsync, KWin is one of them.
[Advanced Desktop Effects Settings > Use VSync](https://userbase.kde.org/Desktop_Effects_Performance#Use_VSync)
[KWin > Practical Features](https://userbase.kde.org/KWin#Practical_Features)

**Comment by oCanna** [comment] 2018-10-19 18:37
@gonetz 
Yes, it does help now. I had to disable the compositor in order to get it working. But that is not a problem as you can specify a window rule that disables the compositor automatically.

@Jj0YzL5nvJ 
This didn't work for me, but as said vsync works now with the disabled compositor.

I wish the emulator could run at a higher frame rate, but I can live with it as long as at least vsync works.

**Comment by gonetz** [comment] 2018-10-21 04:04
@oCanna Please close it if the problem is resolved..

**Closed** 2018-10-21 04:05 UTC
Labels: question, wontfix
