### ISSUE TITLE
Random texture corruption, possible instability.

### ISSUE THREAD

**Issue by AmbientMalice** [gonetz/GLideN64#975] opened 2016-04-27 00:21 UTC
I can't reliably reproduce this problem. Sometimes it happens after settings are changed, sometimes it happens after booting a game for the first time. It could perhaps be a weird shader cache bug, but it occurs even with the cache disabled.

![gliden64_star_wars_ep1_racer_001](https://cloud.githubusercontent.com/assets/10704701/14838083/3b9b6848-0c61-11e6-9559-024bd885eac9.jpg)

![gliden64_turok_3 _shadow_of_o_000](https://cloud.githubusercontent.com/assets/10704701/14838095/47deb966-0c61-11e6-9073-eeb3acaf7e21.jpg)

![gliden64_super_mario_64_000](https://cloud.githubusercontent.com/assets/10704701/14838100/56b43290-0c61-11e6-8f4b-cb335be62164.jpg)

Also, the plugin seems to have gotten strangely unstable. When this bug occurs, changing settings or closing the emulator (PJ64 in this case) can cause the emulator to crash. I'm not 100% sure whether the emulator might be a factor.

**Comment by olivieryuyu** [comment] 2016-04-27 05:05
have the same with the new blender plugin

**Comment by oddMLan** [comment] 2016-04-27 05:10
Hmm.. that does ring a bell... could this be the same issue I faced in DK64?
https://u.pomf.is/zelokv.webm

At first I thought it happened because I forgot to delete the old shader cache but @gonetz said that he changed the shader cache version so the new blender version shouldn't have loaded anyways.

**Comment by AmbientMalice** [comment] 2016-04-27 05:19
@oddMLan Yes, that looks like the issue. It's very hard to reproduce, and seemingly impossible to reproduce 100% reliably. Common factor seems to be transparent textures, however. Text, bubbles in water, smoke, that sort of thing. Looks to me like the melon you pick up is a 2D HUD icon that rapidly pans.

I initially thought it might be related to https://github.com/gonetz/GLideN64/issues/882 where copying Aux buffers to RDRAM gives you garbage, but I think this occurs regardless of whether aux buffers are enabled.

**Comment by gonetz** [comment] 2016-05-03 12:21
It may happen when you run several games without closing the emu. Something is not cleared between sessions.

**Comment by oddMLan** [comment] 2016-05-13 10:09
For what it's worth, I've been experiencing this issue more often. I came to the conclusion that deleting the shader cache does not help or alleviate the issue; it still happens (and it's recurrent) with shader storage disabled. It's even recurrent between emulator restarts.

Changing the filtering to 3-point filtering sometimes triggers it. And switching back and forth between that and bilinear filtering sometimes fixes it, other times it makes it worse.
I found that entering fullscreen and getting out of fullscreen does the same thing, sometimes it makes transparencies break, but if you repeat it it sometimes fixes them.
I think it's an OGL issue and something it's not getting cleared.

Resetting settings (by pressing the "Reset settings" button) mid-emulation also fixes transparencies when they are broken, though I haven't tested that a lot, but it has worked for me a couple of times.

**Comment by olivieryuyu** [comment] 2016-05-13 11:41
change to native always bring this issue to me

**Comment by gonetz** [comment] 2016-05-13 12:12
Please update to commit 71caf75b7, it may help.

**Comment by oddMLan** [comment] 2016-05-13 12:38
Ok so far, I tested this really quick, and I've been trying hard to trigger the bug again (changing bilinear -> 3-point filtering), changing native res factors back and forth, antialasing, changing windowed resolutions. I don't know if I was being lucky but it feels like the commit has helped, since the issue is not as glaring, but unfortunately it is still happening. The most consistent way to trigger the bug is to switch back and forth from windowed mode to fullscreen, and oddly like I mentioned doing this sometimes fixes the issue. And the breakage is sometimes not the same.

I'll post a bunch of screenshots in a bit and show how my testing has been so far.

**Comment by AmbientMalice** [comment] 2016-05-13 12:40
It has helped, I *think* but the issue is still there. This is Extreme G 2 on mupen64plus.

![extreme_g_2-000](https://cloud.githubusercontent.com/assets/10704701/15248071/84ece0ce-195b-11e6-93df-b61b7a8a8051.png)

![extreme_g_2-001](https://cloud.githubusercontent.com/assets/10704701/15248079/8f12fe6c-195b-11e6-826c-85abb0284a61.png)

As @oddMLan mentions, repeatedly hitting ALT+ENTER to go fullscreen and windowed over and over is a good way to triggger the bug.

![extreme_g_2-002](https://cloud.githubusercontent.com/assets/10704701/15248102/aa4cb31c-195b-11e6-9d23-3ddd1aa66111.png)

Doing it over and over will fix some textures elements while breaking others.

**Comment by oddMLan** [comment] 2016-05-13 13:10
First thing I do, I hurriedly go and compile from the latest commit, reset my computer for good measure, open Project64, reset GLideN64's settings, run Mario Tennis, everything seems normal until
![gliden64_mariotennis_000](https://cloud.githubusercontent.com/assets/7278372/15248274/202c4162-18ce-11e6-8b6b-a497c98750d3.png)
![gliden64_mariotennis_001](https://cloud.githubusercontent.com/assets/7278372/15248275/2198f8f6-18ce-11e6-8a1c-5efd82f764dc.png)
Stopping emulation and opening the game fixed it,

Next game I try is Conker, everything seems perfect, I try changing bilinear -> 3-point back and forth, Anisotropic and Antialasing and Native Resolution factors, no breakage. From this point I used Native Res x4
Alt-Enter to go fullscreen, I see this

![gliden64_conker_bfd_000](https://cloud.githubusercontent.com/assets/7278372/15248449/211efe2e-18cf-11e6-90c6-5732c00a5736.png)
![gliden64_conker_bfd_001](https://cloud.githubusercontent.com/assets/7278372/15248451/233dd6ee-18cf-11e6-96ae-c00a73dbfb82.png)

Alt-Enter to exit fullscreen. Blending is back to normal.
Try changing settings one more time back and forth. Everything normal.
Alt-Enter -> fullscreen. Nothing happens. Alt-Enter -> windowed. This happens

![gliden64_conker_bfd_003](https://cloud.githubusercontent.com/assets/7278372/15248497/659b0b9c-18cf-11e6-8e99-fcaeb0f05498.png)

Alt-Enter -> fullscreen.
Butterflies fixed. the landscape broke
![gliden64_conker_bfd_005](https://cloud.githubusercontent.com/assets/7278372/15248670/528331a0-18d0-11e6-8949-9b9dae63861c.png)

Alt-Enter -> Windowed
All fixed............
![gliden64_conker_bfd_006](https://cloud.githubusercontent.com/assets/7278372/15248724/90f1f318-18d0-11e6-84ac-93ac1381be8d.png)

........or so I thought
![gliden64_conker_bfd_009](https://cloud.githubusercontent.com/assets/7278372/15248735/a7ec915e-18d0-11e6-92f8-2d5bb3f69621.png)
![gliden64_conker_bfd_012](https://cloud.githubusercontent.com/assets/7278372/15248741/b1aa0bc2-18d0-11e6-92aa-081f31f90d90.png)
![gliden64_conker_bfd_013](https://cloud.githubusercontent.com/assets/7278372/15248748/b7223656-18d0-11e6-8ae2-420256b6cc32.png)


Move onto the next game
Close emulator. Open game. Load training level and mess around a bit. Switch filtering from bilinear to 3-point, mess with native resolution factor, antialasing, etc. Nothing breaks yet.

Then fullscreen, this happens:
![gliden64_a_bug s_life_000](https://cloud.githubusercontent.com/assets/7278372/15248774/cdf31954-18d0-11e6-9134-4903bf07b421.png)

Windowed, fixed.
![gliden64_a_bug s_life_001](https://cloud.githubusercontent.com/assets/7278372/15248814/0d09a6bc-18d1-11e6-93bb-12f4e9185099.png)

Fullscreen, bug.
![gliden64_a_bug s_life_002](https://cloud.githubusercontent.com/assets/7278372/15248837/339c3d4e-18d1-11e6-996c-ee5268677e6d.png)
![gliden64_a_bug s_life_003](https://cloud.githubusercontent.com/assets/7278372/15248841/3633531c-18d1-11e6-93b3-9aca48e3585c.png)

Windowed, fixe-- nevermind
![gliden64_a_bug s_life_004](https://cloud.githubusercontent.com/assets/7278372/15248848/414f69fc-18d1-11e6-88d3-ec558d13c467.png)
![gliden64_a_bug s_life_005](https://cloud.githubusercontent.com/assets/7278372/15248855/449f090a-18d1-11e6-86ed-88745a21b972.png)

Fullscreen, bug
![gliden64_a_bug s_life_007](https://cloud.githubusercontent.com/assets/7278372/15248876/67060d9a-18d1-11e6-8fc8-7c2116e2d2be.png)

**Comment by gonetz** [comment] 2016-05-13 14:34
Ok, thanks. Scenarios to reproduce that bug are to complex for efficient debugging.  The only way is to guess, what can cause that. My experience says that it can be anywhere :(

**Comment by fzurita** [comment] 2016-06-04 22:06
By the way, this is an issue in Android add well. It may not be as bad though.

**Comment by olivieryuyu** [comment] 2016-06-21 05:09
I have corruptions all the time, with many games and even closing and restarting the emu does not fix all of them. It is really a very serious bug,

**Comment by AmbientMalice** [comment] 2016-06-24 01:30
The issue definitely began with commit https://github.com/gonetz/GLideN64/commit/0ad53ad0e8a551e89563b03c279e1fb0ac4d9b86 but of course there could be an underlying bug that the new combiner system has revealed.

**Comment by gonetz** [comment] 2016-06-24 02:11
Thanks!

**Comment by gonetz** [comment] 2016-06-26 14:03
Please test again with latest master build:
https://drive.google.com/file/d/0B0YqMPjGo3B2aW1GUHNSeTlGSkk/view?usp=sharing

**Comment by AmbientMalice** [comment] 2016-06-26 14:36
It seems to be improved in the sense the distortion of text in Turok 3 seems to be gone, but various texture issues still be reliably triggered by switching between windowed and fullscreen. Mario's dust clouds from rapid turns, for example.

**Comment by AmbientMalice** [comment] 2016-06-27 06:18
![gliden64_super_mario_64_000](https://cloud.githubusercontent.com/assets/10704701/16370405/a49a7004-3c82-11e6-880e-d586fcc47a5f.jpg)
It is much mroe difficult to trigger now, likely due to https://github.com/gonetz/GLideN64/commit/cb54444b416bd031702d50a5c7f6feb9e326a3ba but if you keep toggling fullscreen, alpha will break.

**Comment by gonetz** [comment] 2016-06-27 07:12
IIRC, such things rarely happened with old blending code too.

**Comment by olivieryuyu** [comment] 2016-07-06 08:49
way better with last commits

**Comment by olivieryuyu** [comment] 2016-07-17 17:19
I have no more this issue

**Comment by olivieryuyu** [comment] 2016-09-23 06:40
still a valid bug?

**Comment by AmbientMalice** [comment] 2016-09-23 06:43
Yes. It's fairly simple to trigger in Turok 3. You just repeatedly switch between fullscreen and windowed, and the transparencies will break.

**Comment by AmbientMalice** [comment] 2016-11-12 23:20
Just want to note that this is still a thing, and it's probably the biggest bug in the plugin currently.

**Comment by loganmc10** [comment] 2016-11-13 00:24
I play quite a bit and I've never run into this issue, maybe it's a Windows related thing or something?

**Comment by AmbientMalice** [comment] 2016-11-13 00:30
@loganmc10 I assume Linux probably handles fullscreen and windowed switching differently? Because this is primarily triggered by switching from windowed to fullscreen and from fullscreen to windowed.

**Comment by fzurita** [comment] 2016-11-13 00:37
This also happens in Android still. It happens whenever the plugin is reset without shutting down the app first. It's probably happening because something is not getting cleaned up correctly in a reset.

**Comment by Frank-74** [comment] 2016-11-13 00:58
I've never been able to switch from full screen back to window.  Just get a black screen.  Have to open task manager to get the desktop back.

Project64.  Intel HD Graphics.  OpenGL 4.0.  Glide64 and z64gl are ok switching.

**Comment by loganmc10** [comment] 2016-11-13 01:07
I guess I don't do a lot of window switching so maybe that's why I haven't run into this

**Comment by gonetz** [comment] 2016-11-13 04:32
>It happens whenever the plugin is reset without shutting down the app first.

Yes, this is the  case.

**Comment by AmbientMalice** [comment] 2016-11-21 11:23
I notice that currently the issue is far more common with shader cache enabled.

**Comment by gonetz** [comment] 2016-11-21 12:07
May be cache does not correspond current version? Shader cache version not always changed with changes in shaders. Better to clear Shaders folder and try again.

**Comment by AmbientMalice** [comment] 2016-11-21 12:08
I wiped the mupen64plus shader folder, and it doesn't help.

**Comment by weinerschnitzel** [comment] 2016-11-27 19:06
I'm in the same boat as Frank-74 with switching back from fullscreen. I'm on Intel HD Graphics as well. Used the RC build for 1.3.

**Comment by weinerschnitzel** [comment] 2016-12-04 16:21
Thanks to @fzurita's work on fixing this, I can't reproduce this anymore.

**Comment by gonetz** [comment] 2016-12-04 17:16
That bug was easy to overlook. Francisco did great work for finding true source of the problem.

**Comment by oddMLan** [comment] 2016-12-04 19:19
Marvelous!! The Heiseinbug has been found and prosecuted 😛 
FIXED

**Closed** 2016-12-05 00:43 UTC
Labels: Heisenbug
