### ISSUE TITLE
Paper Mario: Subscreen Delay

### ISSUE THREAD

**Issue by ghost** [gonetz/GLideN64#709] opened 2015-09-07 13:19 UTC
Paper Mario (E/U) and Mario Story (J) 
It takes a long time to open the menu, like Zelda OoT.

**Comment by purplemarshmallow** [comment] 2015-09-07 13:54
The subscreen delay fix hack also works in Paper Mario. But in Paper Mario it breaks the background because it fills the colorbuffer with white pixels. I hope it's possible to find out what the game does and to make a proper fix

**Comment by olivieryuyu** [comment] 2015-09-07 21:42
small and certainly stupid question:

VI CONTROL REG REGISTER doesn't provide the color depth? would it not fix at least incorrect depth colors, which is not always black as previously implemented?

**Comment by LegendOfDragoon** [comment] 2015-09-07 21:43
@olivieryuyu you can find good information here
https://dragonminded.com/n64dev/Reality%20Coprocessor.pdf

**Comment by olivieryuyu** [comment] 2015-09-07 21:44
indeed, i was actually refering to this. So why do we have an issue to find the correct color depth for instance for Quake 2 or Zelda subscreen?

**Comment by purplemarshmallow** [comment] 2015-09-08 20:00
before copying to RDRAM GLideN64 must convert the data into the correct format. GLideN64 has code for copying 32 bit colorbuffers but as you can see in #348 this works incorrect. I'm not sure if it reads VI CONTROL REG to get the color depth.

However in games with the subscreen delay problem copy color seems to work correctly. In Paper Mario you can see the correct background in the subscreen if you enable copy color. Copying the image to RDRAM does not fix the subscreen delay. Filling RDRAM with white pixels fixes the subscreen delay for an unknown reason.

**Comment by LegendOfDragoon** [comment] 2018-05-29 04:17
Seems that I don't get delay when using sync mode. Async mode is still broken.

**Comment by oddMLan** [comment] 2018-06-01 18:49
Confirmed. The delay is 100% fixed with the default settings. Wonder what commit did the trick, as it used not to work.

I guess it can be closed.

**Comment by olivieryuyu** [comment] 2018-06-02 05:35
Yes it would be good to understand this. It could avoid a hack in oot !

**Comment by LegendOfDragoon** [comment] 2018-06-04 06:15
I've been playing around with Angrylion's RDP, trying to test out some stuff and came across this.
![image](https://user-images.githubusercontent.com/10492645/40901068-5ba0e5da-6783-11e8-9fa6-5749a150f498.png)
This is the framebuffer image rendered when pressing start in Zelda OOT. The reason you don't see this with angrylion is because VI-origin points to the other buffer instead, during this time. So while this frame is renderered, it's never displayed but instead just used for the subscreen code. That would explain why filling the color with white makes it work.

Also I'm not sure why async wasn't working for me previously, but it works fine now after retesting. So basically if GLideN64 renders this particular frame properly, there's no need for the white fill color hack.

**Comment by oddMLan** [comment] 2018-06-04 07:04
That looks a lot like coverage being used. Why though? To me it looks like the edges are being smoothed out on the subscreen bg

@gonetz, any insight into the matter?

**Comment by LegendOfDragoon** [comment] 2018-06-04 08:34
You just reminded me, I couldn't tell a diff in performance when switching between async and sync. I guess that explains why. Not sure why settings are inconsistent for me..

I saw a similar kind of image in Paper Mario too, but didn't screenshot it :smile: . It was a little more grey as opposed to white.

**Comment by Kidboy17** [comment] 2018-10-01 20:07
With the newest build ( Master +FB) this issue no longer exists. No more slowdown in the menu. I have Vsync, n64-style 3 point, render 2D elements and N64 depth compare all active, game runs very smooth. Maybe better than before in all honesty.

**Comment by weinerschnitzel** [comment] 2018-10-01 23:15
Interesting. I wonder if someone like @LegendOfDragoon could step through and catch the frame that is passing if there is some other magic that makes it pass without delay. If it regresses again, we will have a better idea for a consistent hack until coverage gets looked into

**Comment by LegendOfDragoon** [comment] 2018-10-01 23:56
Is async still default?

**Comment by oddMLan** [comment] 2018-10-02 00:39
No, Sync is the default for Paper Mario
https://github.com/gonetz/GLideN64/blob/master/ini/GLideN64.custom.ini#L92
0=disabled, 1=sync, 2=async

**Comment by LegendOfDragoon** [comment] 2018-10-02 02:37
@gonetz yes

**Closed** 2018-10-02 02:59 UTC

**Comment by theboy181** [comment] 2018-10-02 04:57
What made you pull ledgendofdraggons name ?
