### ISSUE TITLE
Initial implementation of BOSS ZSort ucode (WDC, Stunt Racer)

### ISSUE THREAD

**Issue by Gillou68310** [gonetz/GLideN64#1685] opened 2017-12-14 16:06 UTC
@gonetz, @olivieryuyu

I rebased my work against master:
https://github.com/Gillou68310/GLideN64/commits/wdc

The game will only run fullspeed if you disable all LOG_WARNING.

The game won't work until https://github.com/mupen64plus/mupen64plus-rsp-hle/pull/62 is merged.

**Comment by loganmc10** [comment] 2017-12-14 16:23
You should check if REG.SP_STATUS before trying to modify it. If the emulator doesn't support that (Project64 or older versions of mupen64plus), it's going to crash.

**Comment by loganmc10** [comment] 2017-12-14 16:24
For instance with Gauntlet Legends, I only enabled the infloop hack if SP_STATUS wasn't nullptr:

https://github.com/Gillou68310/GLideN64/blob/02bf5444df0d37e59cdc12c4d0032444bf79299c/src/RSP.cpp#L337-L338

**Comment by Gillou68310** [comment] 2017-12-14 16:33
You're right. BTW why not checking direcly if SP_STATUS is null instead of using this hack flag?

**Comment by gonetz** [comment] 2017-12-14 16:38
@Gillou68310 Are you going to fully implement this ucode?

**Comment by Gillou68310** [comment] 2017-12-14 16:42
I don't have much time to work on it these days, that's why I'm sharing it in it's current state ;-)

**Comment by Gillou68310** [comment] 2017-12-14 16:44
Last time I worked on it was October 2

**Comment by loganmc10** [comment] 2017-12-14 17:37
> You're right. BTW why not checking direcly if SP_STATUS is null instead of using this hack flag?

@Gillou68310 I did it because I wasn't sure if the check ```address == (RSP.PC[RSP.PCi] - 8)``` was true in any other games. Basically I wanted to make sure that it only applied to Gauntlet Legends, since that check will be executed for other games. I didn't do any testing to see if it affected any other games, I assume not.

BTW, in your commit (https://github.com/Gillou68310/GLideN64/commit/942756db8b48e5f62c8a59dcc52b4ba1bd842760) it doesn't seem to catch every instance, there is usage of SP_STATUS in RSP_ProcessDList(), ZSortBOSS_EndMainDL(), ZSortBOSS_WaitSignal() and ZSortBOSS_Obj() as well

**Comment by olivieryuyu** [comment] 2017-12-14 17:44
I will try to continue on this ucode after the next HLE project...

**Comment by Gillou68310** [comment] 2017-12-14 17:53
> @Gillou68310 I did it because I wasn't sure if the check address == (RSP.PC[RSP.PCi] - 8) was true in any other games. Basically I wanted to make sure that it only applied to Gauntlet Legends, since that check will be executed for other games. I didn't do any testing to see if it affected any other games, I assume not.

Ok I will keep it then.

> BTW, in your commit (Gillou68310/GLideN64@942756d) it doesn't seem to catch every instance, there is usage of SP_STATUS in RSP_ProcessDList(), ZSortBOSS_EndMainDL(), ZSortBOSS_WaitSignal() and ZSortBOSS_Obj() as well

Damn I need to stop doing things in a hurry :-)

**Comment by Gillou68310** [comment] 2017-12-14 18:18
> @Gillou68310 I did it because I wasn't sure if the check address == (RSP.PC[RSP.PCi] - 8) was true in any other games. Basically I wanted to make sure that it only applied to Gauntlet Legends, since that check will be executed for other games. I didn't do any testing to see if it affected any other games, I assume not.

Thinking about this twice if address == (RSP.PC[RSP.PCi] - 8) is true the game will be locked anyway, so it won't harm if we always do the test.

**Comment by loganmc10** [comment] 2017-12-14 18:40
> Thinking about this twice if address == (RSP.PC[RSP.PCi] - 8) is true the game will be locked anyway, so it won't harm if we always do the test.

Yes you are probably right, at the time I added the hack because I didn't have the time/motivation to test and make sure it was needed, it's probably safe to change it like you've done

**Comment by Gillou68310** [comment] 2017-12-15 10:20
Ok I updated the last commit, if ucode type is ZSortBOSS and pointer to SP_STATUS reg is null, an assertion failure is triggered. It will avoid checking the pointer every time we try to access it.

**Comment by loganmc10** [comment] 2017-12-16 04:42
Just for reference/interest, this is what it looks like in mupen64plus:

![world_driver_champ-000](https://user-images.githubusercontent.com/848146/34067344-9f32384a-e1e0-11e7-83ee-fa54f1428275.png)
![world_driver_champ-001](https://user-images.githubusercontent.com/848146/34067345-9f4ea0f2-e1e0-11e7-9f65-a177c829c529.png)

Not bad, seems like a good amount of progress!

**Comment by loganmc10** [comment] 2017-12-16 05:57
@Gillou68310 I'm curious why there is no sound. I was under the impression that these BOSS games used the CPU to work on the audio, not the RSP, and it doesn't seem like an audio task is ever called for the RSP, yet there is no audio.

**Comment by LegendOfDragoon** [comment] 2017-12-16 06:41
The graphics microcode affects audio

**Comment by Gillou68310** [comment] 2017-12-16 07:32
Hum good question. I'm using the dummy audio plugin when working on the emu so I didn't even realize audio was missing. I will investigate!

**Comment by Gillou68310** [comment] 2017-12-19 16:17
Wow this is one hell of an optimized ucode!!! The ucode is doing both audio and graphic processing, plus everything fits in less then 1024 instructions so no overlay needed.
@loganmc10 this explains why there is no sound, audio commands are unimplemented yet!
@gonetz This is going to be weird, having audio commands inside video plugin.

**Comment by LegendOfDragoon** [comment] 2017-12-19 23:00
>The ucode is doing both audio and graphic processing

I figured as much since I remember an RSP regression made the audio sound terrible. Do you know which part of the ucode handles audio?

**Comment by gonetz** [comment] 2017-12-20 05:04
> This is going to be weird, having audio commands inside video plugin.

I have no idea how to resolve it. Add special audio library?

**Comment by Gillou68310** [comment] 2017-12-20 09:03
> I figured as much since I remember an RSP regression made the audio sound terrible. Do you know which part of the ucode handles audio?

@LegendOfDragoon here's a log extract of commands execution:

```
ZSortBOSS_MoveWord (Write 0x00000c20 to DMEM: 0x0010)
ZSortBOSS_ClearBuffer (Write 0x0 to DMEM: 0x0c20 -> 0x0e20)
ZSortBOSS_1CF0 (0x220cdfc8, 0x803f4440)
ZSortBOSS_MoveWord (Write 0x32e22f6e to DMEM: 0x0904)
ZSortBOSS_MoveWord (Write 0x00000000 to DMEM: 0x0000)
ZSortBOSS_1D20 unimplemented (0x2400003f, 0x003e0798)
ZSortBOSS_1BCC unimplemented (0x260000ec, 0x803f4440)
ZSortBOSS_1BF0 unimplemented (0x1c00d000, 0x80000000)
ZSortBOSS_1CF0 (0x220cf100, 0x803f4448)
ZSortBOSS_MoveWord (Write 0x065a05eb to DMEM: 0x0904)
ZSortBOSS_MoveWord (Write 0x00000000 to DMEM: 0x0000)
ZSortBOSS_1D20 unimplemented (0x24000012, 0x003e0f30)
ZSortBOSS_1BF0 unimplemented (0x1c003333, 0x80000000)
ZSortBOSS_MoveMem (R/W: 1, RDRAM: 0x003f129c, DMEM: 0x0c20; len: 512)
```

Audio buffer in DMEM is cleared by ```ZSortBOSS_ClearBuffer``` command.
Audio buffer is send from DMEM to RDRAM by ```ZSortBOSS_MoveMem``` command.
So I would say that commands, 1CF0, 1D20, 1BCC and 1BF0 are audio commands.

Here's the disassembly if you want to take a look at the commands. I added a few comments to help understanding the code:
[WDC.txt](https://github.com/gonetz/GLideN64/files/1574807/WDC.txt)

@gonetz Don't worry we won't need any special audio library, you can take a look at typical audio commands in mupen64plus-rsp-hle. It's just a bit confusing to have to implement them in the video-plugin.

**Comment by LegendOfDragoon** [comment] 2017-12-20 16:51
@Gillou68310 Thanks for the info. I really should have wrote more things down instead of just relying on my own memory.

Iirc, there was some code that never gets executed unless you significantly increase the number of times it yields. I also remember there being a lot of interesting ways to optimize the code for this ucode. Like for instance, $v0 always = 0, and they did interesting stuff with that.

@gonetz The ucode is relatively lightweight and can be done on CPU without any need for any libraries.

**Comment by gonetz** [comment] 2017-12-21 06:10
> Don't worry we won't need any special audio library, you can take a look at typical audio commands in mupen64plus-rsp-hle. It's just a bit confusing to have to implement them in the video-plugin.

If this code will not leave ZSortBOSS.cpp, its ok.

**Comment by Gillou68310** [comment] 2017-12-22 18:29
More progress on this:
```ZSortBOSS_TransposeMTX``` and ```ZSortBOSS_TransformLights``` commands are now implemented. ```ZSortBOSS_1444 (Lighting)``` command is still wip but reflection seems to work.
I thought that the car wrong color was caused by lighting but the light number is equal to zero so I still need to investigate.

**Comment by Gillou68310** [comment] 2018-01-04 17:28
Progress report:
-Fixed cars wrong colors (```ZSortBOSS_SetOtherMode_L``` and ```ZSortBOSS_SetOtherMode_H``` commands were not correctly implemented)
-Fixed cars reflection (the square root reciprocal needs to be saturated when normalizing light vectors)
-Added ```ZSortBOSS_Obj``` command to reflect what the assembly code actually do (I'm not relying on original ```ZSort_Obj``` command anymore)

Remaining issues:
-No audio (audio commands are not implemented yet)
-Clipping issue (probably related to the```ZSortBOSS_MultMPMTX``` command, I need to investigate)

https://github.com/Gillou68310/GLideN64/commit/59bf5bef47992eb5040cb42474ce3c434cd23c78

**Comment by gonetz** [comment] 2018-01-05 07:10
Lots of works is done, great!

However, how to run it? I guess, it will not work with Zilmar-spec emus.
I tried to run it with M64PY, but it seems to be too old and does not have necessary changes in core and RSP.
I tried to run it with latest m64p, but it always run WDC in LLE mode, despite of RSP-HLE set as rsp plugin. The same problem is with Indi: m64p runs it in LLE mode only.

**Comment by theboy181** [comment] 2018-01-05 08:30
I have a zilmar spec RSP plugin that may work. Can you send a build and I’ll test it out. ?

**Comment by gonetz** [comment] 2018-01-05 08:57
Sure. Here WDC WIP build for Windows, zilmar and mupen64plus:
https://drive.google.com/file/d/19veV2yqkOppCSH0N2gyhxGsqy34pX6oz/view?usp=sharing

**Comment by theboy181** [comment] 2018-01-05 09:55
Aio has buld a zilmar rsp with hole support for gaintlet and I figured it may work. :( nop

**Comment by AmbientMalice** [comment] 2018-01-05 10:59
I seemingly got it working on m64p by replacing the mupen64plus-rsp-cxd4-sse2.dll file with a duplicate of mupen64plus-rsp-hle.dll Graphical distortions. No audio.

**Comment by gonetz** [comment] 2018-01-05 12:36
> I seemingly got it working on m64p by replacing the mupen64plus-rsp-cxd4-sse2.dll file with a duplicate of mupen64plus-rsp-hle.dll which overrides the override.

Yes, it works, tahnks. I did not hit upon this myself.

>Graphical distortions. No audio.

As promised.

The overall result is very good. Especially for such complex microcode. I remember how I implemented zsort ucode. I had documentation and two test roms, but I spent many time to get it working.

**Comment by Gillou68310** [comment] 2018-01-05 13:21
> I tried to run it with latest m64p, but it always run WDC in LLE mode, despite of RSP-HLE set as rsp plugin. The same problem is with Indi: m64p runs it in LLE mode only.

Look for "RspFallback" in mupen64plus.cfg. If you specify an empty string it should disable LLE fallback.

> The overall result is very good. Especially for such complex microcode. I remember how I implemented zsort ucode. I had documentation and two test roms, but I spent many time to get it working.

Thanks, it would have been much more difficult without your implementation of the ZSort ucode ;-)

**Comment by loganmc10** [comment] 2018-01-05 15:08
> Look for "RspFallback" in mupen64plus.cfg. If you specify an empty string it should disable LLE fallback.

The GUI included with m64p forces the cxd4 RSP in LLE mode for these games currently. Tricking it by renaming the plugin like they are doing is probably the only way to get around it currently

**Comment by StenApp** [comment] 2018-01-06 13:48
Nice progress @Gillou68310, 2 of 4 of the last LLE only games are port to HLE, thanks.

**Comment by Gillou68310** [comment] 2018-01-11 14:24
Progress report:
-Stunt racer allow the combined matrix to be stored to RDRAM. This is now implemented.
-Fixed ```ZSortBOSS_MultMPMTX``` command including clipping code, fog and sx/sy computation.
-In ```ZSortBOSS_DrawObject```, vertex could arrive without ```1/w``` information. The field contains rgba information instead. ```w``` is forced to 1 in this case. ```w``` is also forced to 1 when ```1/w < 0```.

I made some quick testing and didn't notice any graphical distortions. A few textures are flickering but they also fickler in LLE. Any additional testing is welcome ;-)

TODO:
-Implement audio commands.
-Implement LightVertex (Is this ever happening?)

https://github.com/Gillou68310/GLideN64/tree/wdc

**Comment by olivieryuyu** [comment] 2018-01-11 14:43
great!!! thanks!!

**Comment by Gillou68310** [comment] 2018-01-11 16:20
Arf I found another graphical distortions in stunt. It's a matrix issue.

**Comment by Gillou68310** [comment] 2018-01-12 10:28
Issue fixed! https://github.com/Gillou68310/GLideN64/commit/7746bc04853eca1756c235c5ceead3ec20bdf1c7

**Comment by gonetz** [comment] 2018-01-14 09:09
Wow! Now WDC looks really cool!
I see only one issue ingame: reflection textures mapped wrong.
Stunt Racer looks good too.
Great work!
I need to fix the flickering line in WDC intro, and it will be nearly perfect.

**Comment by Gillou68310** [comment] 2018-01-14 09:51
Yeah I noticed reflection textures are still not perfect. I will investigate ;-)

**Comment by Gillou68310** [comment] 2018-01-15 09:39
Hum @gonetz I double checked but I could not reproduce the reflection textures issue. Could you provide a savestate?
Please apply this patch first https://github.com/Gillou68310/mupen64plus-core/commit/d9129e10c69a0111fde0fb536aaf65f3ad01c624, otherwise you could end up with unusable savestate.

**Comment by gonetz** [comment] 2018-01-18 14:13
No need for savestate, the problem is seen on any race.
Quick start => select car => RAGE 512 EVO
Even on this screen the problem is visible.
You may start arcade race to see this car from behind - the problem is obvious.

**Comment by Gillou68310** [comment] 2018-01-21 17:07
Well looks like I was too accurate :-) The problem is indeed obvious but I have the same exact behavior with rsp-z64 (this is what I use to dump and debug ucodes). rsp-cxd4 doesn't have this issue, it will be a good starting point to investigate the issue.

**Comment by Gillou68310** [comment] 2018-01-23 17:09
Ok I see what is happening. Here's the offending code:
```04001564 sdv     v4[12], -$0008(r27)```

This instruction should store 8 bytes starting at v4[12] to DMEM.
Or rsp-z64 stops at the vector boundary (v4[15]), so only 4 bytes are actually stored to DMEM.
rsp-cxd4 uses the VR_STATIC_WRAPAROUND hack in order to fix this issue.

This should fix the issue:
https://github.com/Gillou68310/GLideN64/commit/672f910d795523231a4087cebc8d2d43a98159d5

**Comment by StenApp** [comment] 2018-02-03 16:43
@Gillou68310 
Just curious what the status is...

**Comment by Gillou68310** [comment] 2018-02-03 17:38
All graphic commands are implemented, I still need to implement audio commands. They don't look very complex, I just need to find time to work on it.

**Comment by gonetz** [comment] 2018-02-04 14:37
WDC looks nearly perfect in-game. This is really cool!
The performance is not that good. I have freezes for a moment each one-two seconds.
May be it is core issue.

**Comment by Gillou68310** [comment] 2018-02-04 18:30
> The performance is not that good

@gonetz with or without the log warning commented out?

> I have freezes for a moment each one-two seconds.

Is it reproducible or is it randomly happenning?

**Comment by loganmc10** [comment] 2018-02-05 19:04
It's probably the log warnings. I just tested this on Windows + mupen64plus. My CPU was about 13-15% (4 core, so 25% would be maxed out).

Seemed to perform really well and looked good, didn't freeze for me.

**Comment by Gillou68310** [comment] 2018-02-05 21:10
Nice thanks for testing :-)
It works well on windows for me too. However I tested on my galaxy note3 and the performance was not good there, plus textures were all messed up, not sure what the issue is.

**Comment by fzurita** [comment] 2018-02-05 21:52
My best guess on the bad textures is probably driver issues.

**Comment by Gillou68310** [comment] 2018-02-06 08:14
I tested on my odroid c2 and I have the same texture problem, maybe it's a gles2 specific issue. Anyway the game was running fullspeed on my odroid c2 so I don't think performance is an issue here.

**Comment by olivieryuyu** [comment] 2018-02-08 22:34
Seriously why the Zsort ucode was not used more games. It is obvious that it palliates the fillrate issue of the N64 and allows way better graphics in consequence.

Just compare Mia Soccer with FIFA98 on a real N64: the difference is so obvious, it is shocking!

**Comment by AmbientMalice** [comment] 2018-02-08 22:40
Was released too late in the system's life, I think. And was also a bit obtuse. 

Feb 1999.

Q4 What is the current status of the Z Sort microcode?

A4 Its release has been announced. It is now a matter of distributing the Z Sort microcode, but the Z Sort microcode libraries have not yet been completed. Consequently, the microcode still hasn't been officially released.

There is no official release schedule for the Z Sort microcode. There are various reasons for this, including the following.

Since it is not compatible with F3D GBI, it is not easy to incorporate into games
Preprocessing by the CPU is necessary to run the microcode
A minimum RSP and CPU scheduling sample (including sound processing) using a game has not been created
There are no tools for output with Z Sort structures 
The current latest version 0.34 is available as a beta evaluation version at NTSC-ONLINE.

Note: While you can expect that using this microcode and library will be effective for games which currently cause bottlenecks in the RDP, please note that it will have no effect on those with bottlenecks in the CPU and/or RSP. In addition, even if the RDP processing is affected, this cannot be guaranteed to improve the overall performance of the game application. Please, keep these things in mind when using and evaluating this microcode.

Since the current version 0.34 is a beta version, please be forewarned that the specifications may vastly differ in the future. Now, while the majority of this is outside the scope of support, it would be extremely helpful if you would contact NTSC regarding bugs, etc. 

http://n64devkit.square7.ch/qa/graphics/ucode.htm

**Comment by Gillou68310** [comment] 2018-02-09 13:41
I finally implemented the audio commands!
Since I'm not familiar with audio processing I can't really put a name on those commands.
Anyway at least we have audio now!

**Comment by fzurita** [comment] 2018-02-09 14:51
That's pretty amazing work.

**Comment by loganmc10** [comment] 2018-02-09 15:48
@Gillou68310 looks and sounds great! Definitely ready to be merged as far as I can tell (well you have a tiny merge conflict in the wdc branch). Great work! The CPU usage is relatively low on my PC, so I assume that a device with GL support like the Shield would be able to run the game really well. It sounds like there might be some GLES issues but that is unrelated to the ucode.

**Comment by Gillou68310** [comment] 2018-02-09 15:57
@fzurita, @loganmc10 thanks for the feedback!

Game is running fullspeed on my odroid c2, it should definitely run fullspeed on a Shield too.

**Comment by fzurita** [comment] 2018-02-09 15:59
I have yet to try it. But I'll give this a shot to see how it goes. I can probably debug the GLES issues if I get sone glErrors.

**Comment by olivieryuyu** [comment] 2018-02-09 18:50
amazing! great work! :)

**Comment by fzurita** [comment] 2018-02-09 23:40
Well, I can say it works on Android with GLES, but there are a lot of texture glitches and the game runs sluggish. Also, sound seems to skip a lot. Also, there may be same near plane issues.

**Comment by fzurita** [comment] 2018-02-09 23:44
Also, loading save states seem to lock up the game.

**Comment by fzurita** [comment] 2018-02-10 00:32
Full GL mode doesn't look much better on the Shield TV.

**Comment by loganmc10** [comment] 2018-02-10 06:37
Could the arm dynarec be screwing something up? Did you guys try the interpreter? I'm surprised it doesn't work on the Shield

**Comment by Gillou68310** [comment] 2018-02-10 07:03
> Also, loading save states seem to lock up the game.

Savestate should not happen while rsp task is locked:
> Please apply this patch first Gillou68310/mupen64plus-core@d9129e1, otherwise you could end up with unusable savestate.

> Could the arm dynarec be screwing something up?

Looks like it is, interpreter has no texture glitches!

**Comment by gonetz** [comment] 2018-02-10 11:11
Amazing work, Gilles!

Yes, it can be merged with master. Things to do:
- Put ZSortBOSS sources to proper place in Visual Studio project: Header files/uCodes for ZSortBOSS.h
  Source files/uCodes for ZSortBOSS.cpp
- rebase to current master, fix conflicts
- Squash all commits to one commit
- Make PR :)

**Comment by gonetz** [comment] 2018-02-10 11:14
Note: I see several "ZSortBOSS_Audio4: Index out of bound" messages in gliden64.log

**Comment by fzurita** [comment] 2018-02-11 16:26
So this turns out to run a lot faster if you disable the LLE checks in rsp-hle. Whoops, I wasn't even testing the HLE portion. After fixing that, speed is excellent. Texture issues remain though. Unfortunately, speed using interpreter with HLE is as slow as dynarec with LLE.

**Comment by Gillou68310** [comment] 2018-02-11 19:37
> Yes, it can be merged with master. Things to do:
> 
>     Put ZSortBOSS sources to proper place in Visual Studio project: Header files/uCodes for ZSortBOSS.h
>     Source files/uCodes for ZSortBOSS.cpp
>     rebase to current master, fix conflicts
>     Squash all commits to one commit
>     Make PR :)

I will take care of this tomorrow ;-)

> Note: I see several "ZSortBOSS_Audio4: Index out of bound" messages in gliden64.log

Yes this is happening on LLE too. It's either a core issue or a bug that is also present on real hardware.

> So this turns out to run a lot faster if you disable the LLE checks in rsp-hle. Whoops, I wasn't even testing the HLE portion. After fixing that, speed is excellent. Texture issues remain though. Unfortunately, speed using interpreter with HLE is as slow as dynarec with LLE.

Lol I just realized that I did the same mistake, that's why performance was not good on android :-D
I'll see what I can do about the new dynarec issue. At least it's not happening on x86 new dynarec, this should help debugging the issue.

**Comment by Gillou68310** [comment] 2018-02-12 11:34
Done https://github.com/gonetz/GLideN64/pull/1717

**Comment by fzurita** [comment] 2018-02-12 13:00
I wonder if the new dynarec issues in this game are related to the new dynarec issues in multi racing championship. It's also texture issues when new dynarec is enabled:

https://github.com/mupen64plus/mupen64plus-core/issues/433

**Closed** 2018-02-13 10:13 UTC

**Comment by Gillou68310** [comment] 2018-02-14 16:45
@fzurita Looks like the DMULT/DMULTU recompiled code is broken on arm. Texture issues are fixed by switching to interpreted opcode https://github.com/Gillou68310/mupen64plus-core/commit/d019477b718f4e3a0fa3c435ab7d795a7985fa5f
I still need to understand what is wrong with the recompiled code.

**Comment by fzurita** [comment] 2018-02-14 16:52
Ok, that's good to know. You are really good at finding dynarec issues.

**Comment by Gillou68310** [comment] 2018-02-14 16:53
Trust me it takes a lot of time and patience ;-)

**Comment by gonetz** [comment] 2018-03-13 04:20
> olivieryuyu: The only bug is the missing coronas in game in both LLE and HLE.

Hmm, that is interesting. Usually corona is depth buffer based effect. CPU analyzes values in depth buffer and decides: include coronas rendering to display list or not. ZSort microcode does not use depth buffer at all. How it should work? May be coronas rendered by CPU? Could you give me savestate from the place, where corona should be visible?

**Comment by olivieryuyu** [comment] 2018-03-13 11:43
You don't need a savestate: just let the intro runnning and you will see with Angrylion plugin the coronas within few mins appearing.

**Comment by Tasosgemah** [comment] 2018-03-13 14:40
There's also a lens flare effect in the last part of first track that is missing in both LLE and HLE. You can see it in Angrylion, when you exit the final tunnel.
