### ISSUE TITLE
Monster Truck Madness 64

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#237] opened 2015-02-12 18:43 UTC
TEXT issues 
![capture](https://cloud.githubusercontent.com/assets/9299743/6174495/fb3faaf6-b2a3-11e4-9d06-2780b194de54.PNG)

**Comment by gonetz** [comment] 2015-02-16 15:08
Duplicate of #25

**Closed by gonetz** 2015-02-16 15:08 UTC
