### ISSUE TITLE
Auxiliary Buffer for Project64

### ISSUE THREAD

**Issue by LuigiBlood** [gonetz/GLideN64#847] opened 2016-01-29 22:27 UTC
I found out Auxiliary Buffer is quite effective for Mario Artist, why can't you enable it in zilmar API builds?

After playing around with @purplemarshmallow's build showing that it works, why isn't it in there?

Just linking the build I'm talking about: https://github.com/gonetz/GLideN64/issues/803#issuecomment-175121706

**Comment by purplemarshmallow** [comment] 2016-01-29 23:33
This option is still WIP it does not work good enough.
Basically you need it in 2 cases:
1 The CPU checks the content of auxiliary buffers or modyfies them (Pokemon Snap camera detection, Body Harvest collisions, ...)
2 Hardware framebuffer emulation fails (Knockout Kings portraits, Top Gear Hyperbike ground, Yoshi's Story background, ...)

Current problems are it's slower than it should be and it does not work good enough in cases where something is drawn over an existing image. I experimented with it but haven't found a good solution yet #791

Body Harvest collisions are still not working properly and the ground in Top Gear Hyperbike does not look perfect. I added an option for Mupen64plus because it was easy but I haven't looked into Qt yet and I don't have the libraries ready on my PC. That's why my build has no GUI. I looked more into getting the functionality right but problems are still not solved.

**Comment by gonetz** [comment] 2016-01-30 04:39
May be it is better to set this option per-game in custom ini, until it does not work good enough in general.

**Comment by LuigiBlood** [comment] 2016-01-30 13:15
I still feel like leaving the option is good enough though, at least saying like "Auxiliary Buffer (Experimental)", something like that.

**Comment by gonetz** [comment] 2016-01-30 16:36
I will change GUI for FBInfo options and will add that option too.

**Comment by purplemarshmallow** [comment] 2016-01-31 11:52
Currently it makes sense to enable it in Pokemon Snap, Top Gear Hyperbike, Knockout Kings and Mario Artist games

**Comment by LuigiBlood** [comment] 2016-01-31 14:31
Though there's no way to detect 64DD games for now (except Cart Hacks). That's also why I wanted the option at least in the main INI.

**Comment by AmbientMalice** [comment] 2016-02-02 01:46
@purplemarshmallow Would you mind explaining the differences between these three branches?

https://github.com/purplemarshmallow/GLideN64/commits/FB2_RAM

https://github.com/purplemarshmallow/GLideN64/commits/fb2RDRAM

https://github.com/purplemarshmallow/GLideN64/commits/FB2RAM

Also, does FBInfo work for aux framebuffers?

**Comment by purplemarshmallow** [comment] 2016-02-02 11:00
>@purplemarshmallow Would you mind explaining the differences between these three branches?

I experimented back then and did not delete them. There is nothing useful in all 3. Anything useful is already merged.

>Also, does FBInfo work for aux framebuffers?

They are not sent to the emulator the spec does not allow it. Only 6 buffers can be sent but games can create many more. But if you enable copy auxiliary they all get copied and the CPU can read and modify them.

>Also, I notice that https://github.com/gonetz/GLideN64/tree/FBInfo has merged your auxiliary FB code. When I was testing, I noticed Jet Force Gemini shadows looked more accurate, but Turok 3 shadows were broken with aux FB copies.

Yes gonetz inplemented 8 bit buffer copy in this branch. The background in Yoshi's Story is also not perfect I think the problem is that the game draws something over an existing image.

**Comment by LuigiBlood** [comment] 2016-02-07 19:30
Actually I didn't even notice FBInfo branch. lol

But doesn't change much on compiling that I can't really do since I don't really want to update Qt else I expect another thing I'm contributing on to break really hard.

**Comment by LuigiBlood** [comment] 2016-02-08 01:28
I just noticed there was a build of it.

Therefore I'm showing what's wrong with Mario Artist Talent Studio:
![image](https://cloud.githubusercontent.com/assets/952602/12876994/a16ac57c-ce0b-11e5-8f4d-0bf570aa881d.png)

**Comment by AmbientMalice** [comment] 2016-02-08 01:57
@LuigiBlood FBinfo isn't supported in PJ64. It should be, but we can't have everything we want.

**Comment by LuigiBlood** [comment] 2016-02-08 01:58
I know FBInfo isn't supported. I made sure it's disabled too. This problem is mostly likely related to Auxiliary Buffer.

**Comment by AmbientMalice** [comment] 2016-03-02 05:02
So in case this has been lost in the wash, framebuffer notifications+aux framebuffer still causes Jet Force Gemini to crash in mupen.

**Closed** 2016-10-05 16:19 UTC
