### ISSUE TITLE
The black lines in mario kart portraits

### ISSUE THREAD

**Issue by budtz** [gonetz/GLideN64#1142] opened 2016-09-28 05:52 UTC
Is there any way to get rid of the black lines in mario kart 64 portraits?

**Comment by orbea** [comment] 2016-09-29 04:38
Try enabling `EnableNativeResTexrects`.

**Comment by budtz** [comment] 2016-09-29 14:46
It is enabled. It dosnt remove the problem

**Comment by fzurita** [comment] 2016-09-29 14:56
For that setting to work, you have to set nativeResFactor to 0 and disable all texture enhancements.

Also EnableNativeResTexrects causes big slowdowns. Setting nativeResFactor=2 also fixes the portraits without causing slowdowns.

**Comment by gonetz** [comment] 2016-09-29 15:18
> Also EnableNativeResTexrects causes big slowdowns.

On Android only.

**Comment by budtz** [comment] 2016-09-29 21:15
I get a less sharp image with native res set to 2. I run games at 1080p. How does the normal resolution setting combine with the native res Setting?

**Comment by oddMLan** [comment] 2019-11-05 13:29
duplicate of https://github.com/gonetz/GLideN64/issues/607 (which is fixed by native texrects)

**Closed** 2019-11-05 16:21 UTC
Labels: duplicate
