### ISSUE TITLE
Pokemon Stadium Trainer Overlay

### ISSUE THREAD

**Issue by AlexN64gamer** [gonetz/GLideN64#1832] opened 2018-06-05 17:18 UTC
When a battle ends and it shows the trainers you have beaten theres the red cross but it doesnt show the trainers face, also Ive seen today playing the gym leader castle an error with Depth compare enabled, when using the attack Thunder with Raichu, the rival pokemon and the background of the gym totally disappears (black background) I dont know if it has something with Intel gpu.

Also the "Warning" advise that shows in the first screen of the game should have black and yellow lines, not transparent.

![trainer overlays](https://user-images.githubusercontent.com/38527600/40991640-47a5a222-68ec-11e8-9f1d-85b7e851eb8c.png)
![raichuthunderblack](https://user-images.githubusercontent.com/38527600/40991792-c80cfcee-68ec-11e8-819c-97d423c13bad.png)
![warningbug](https://user-images.githubusercontent.com/38527600/41060848-bd0a233a-69c8-11e8-92d7-514d8e7f43d0.png)

**Comment by purplemarshmallow** [comment] 2018-06-30 09:55
duplicate? https://github.com/gonetz/GLideN64/issues/728
But the issue with the red crosses is different now https://github.com/gonetz/GLideN64/issues/722

**Comment by oddMLan** [comment] 2019-11-05 21:46
duplicate of #722 and #728

**Closed** 2019-11-06 07:34 UTC
Labels: duplicate
