### ISSUE TITLE
Mortal Kombat Mythologies - Sub-Zero

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#238] opened 2015-02-12 18:49 UTC
GLideN64 HLE game is rendered upsidedown (LLE working)
![capture](https://cloud.githubusercontent.com/assets/9299743/6174645/dfc8c43c-b2a4-11e4-929d-799735e2fb7f.PNG)

**Comment by gonetz** [comment] 2015-02-16 14:58
Duplicate of #6

**Closed by gonetz** 2015-02-16 14:58 UTC
