### ISSUE TITLE
Banjo-Kazooie (U) (v1.0), freezes randomly

### ISSUE THREAD

**Issue by Noenko** [gonetz/GLideN64#857] opened 2016-02-07 17:19 UTC
On Project64 Banjo-Kazooie frezees randomly. It seems to happen mostly on "treasure trove cove".
Plugins i used are:
Audio: Azimer's XA2 Audio v.070 WIP 4
Input: Jabo's DirectInput 1.7.0.12
RSP: Iconoclast's SP Interpreter (MLE)

Audio is set to LLE
Graphics are set to HLE

**Comment by LegendOfDragoon** [comment] 2016-02-07 17:22
How do you know it's caused by GLideN64?

**Comment by retrobenny** [comment] 2016-02-07 18:38
Strange that it is happening on Project 64 unless the use of an alternate RSP plugin is the cause.
If you happen to be using the original 60fps code,Treasure Trove Cove likes to freeze randomly after an average amount of time,especially on the 1.0 version,but normally only occurs on Mupen64Plus including M64P-AE.
A fixed version cuts TTC out of it,leaving it at 30fps while the rest of the game is 60fps,I may need to tweak it for all rooms in TTC so the sand castle/Nipper's shell/Sharkfood Island rooms don't trigger freezes.
The 1.1 version recently freezed on me randomly with 60fps which is a really unfortunate result since I first thought it was fixed in the changes like the Ticker's Tower slopes.

**Comment by Noenko** [comment] 2016-02-07 18:40
Oh, yeah. That might be it. Forgot i used the code since I'm so used to having it on. Thanks for the help!

**Comment by oddMLan** [comment] 2016-02-07 18:53
can you close the bug

**Closed** 2016-02-07 19:23 UTC
