### ISSUE TITLE
Mario Tennis: misplaced/wrong texture in menu/game

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#215] opened 2014-12-21 18:52 UTC
Transition effect in menu seems incorrect.

Gliden64:

![tennis1a](https://cloud.githubusercontent.com/assets/8987490/5519251/d637315c-894a-11e4-81c5-c06e909518a7.jpg)

LLE Software

![tennis1](https://cloud.githubusercontent.com/assets/8987490/5519253/e0db2dfc-894a-11e4-99d4-f08a42248cd0.jpg)

**Comment by purplemarshmallow** [comment] 2015-05-15 05:17
sometimes pause menu is broken
most likely a problem with validity checking
![gliden64_mariotennis_000](https://cloud.githubusercontent.com/assets/7283660/7647297/711b5164-fad2-11e4-8311-27d9c9fc7f02.jpg)

**Comment by AmbientMalice** [comment] 2015-05-26 05:40
The horizontal swipe transitions rely on framebuffer as texture. (They partially work with Glide64.) The problem is that enabling framebuffer as texture in Mario Tennis crashes GLideN64.

**Comment by purplemarshmallow** [comment] 2015-07-02 22:29
@AmbientMalice I found out why framebuffer as texture crashes in Mario Tennis. The problem is that VI.width is wrong, if you remove this line in VI.cpp framebuffer as texture works correctly:
VI.width = min((u32)floorf((hEnd - hStart)*xScale + 0.5f), *REG.VI_WIDTH);

But this option does not seem to fix a single effect in this game, it was added to emulate CPU writes to colorbuffer, I don't think this game uses these effects. Usually the CPU only draws a few pixels (pills in Dr. Mario, red dot in Pokemon Snap ...)

**Comment by AmbientMalice** [comment] 2015-07-02 22:41
@purplemarshmallow I believe the game uses FB to texture for the horizontal wipes, and also various Vigilante 8 menu effects. I'm not 100% sure, though. I was tinkering with Glide64, where FB to texture seemed to improve horizontal wipes. (Plus GLideN64 FBtT crashes Vig 8, too.)

On this note, though, there are definitely some underlying bugs in GLideN64's FB, and fixing them will likely have positive side effects.

**Comment by purplemarshmallow** [comment] 2015-07-02 23:47
a big problem with fb emulation is validity checking, many developers tried to find a solution. I hope it's possible to fix this problem.

**Comment by AmbientMalice** [comment] 2015-07-03 00:04
>a big problem with fb emulation is validity checking, many developers tried to find a solution. I hope it's possible to fix this problem.

True, true. Both of GLideN64's validity check methods are unsatisfactory. The second one is downright wrongheaded, since it doesn't actually solve Ocarina of Time's problem, but rather tricks the game. It's by no means an easy problem to fix, though.

**Comment by baptiste0602** [comment] 2016-04-10 09:15
Fixed by "copyAuxToRDRAM=1", do we add it to custom.ini ?

**Comment by AmbientMalice** [comment] 2016-04-10 09:27
@baptiste0602 It fixes the wipe, but not the VS screen, and it causes a huge performance hit. Possibly the worst of any N64 game.

**Comment by oddMLan** [comment] 2016-05-13 22:50
Swipe transitions (fixed by 87f307c3fffc3d5d196f37319b6023bfa8cf8320) and broken pause menu no longer an issue (but if you enable copy depth it happens, though the game does not need it so...)

Only remaining issue is the VS screen before the start of a match.

**Comment by AmbientMalice** [comment] 2016-05-14 01:39
>Only remaining issue is the VS screen before the start of a match in HLE.

It's broken in LLE, too. It's interesting to note that the Vs effect works correct in z64gl, along with the Turok 3 thermal goggle scan lines, seemingly because z64gl handles VI and FB differently.

**Comment by gonetz** [comment] 2016-05-14 12:27
>It's broken in LLE, too.

FB emulation has no special HLE or LLE code, or at least I can't remember any difference.

**Comment by olivieryuyu** [comment] 2016-09-11 07:09
this seems fix, no?

**Closed** 2016-09-11 07:10 UTC
