### ISSUE TITLE
[feature request] Option to Windowed fullscreen/Borderless 

### ISSUE THREAD

**Issue by LuismaSP89** [gonetz/GLideN64#2518] opened 2021-06-19 04:33 UTC
There are some problems in windows 10 HDR mode when Gliden64 is on use. All the games (Using project64 + Gliden64) looks with washed colors when fullscreen mode is used. If I switch back to windowed mode, all colors looks as they should.

Looked on a lot of forums, and seems this is happening to a lot of users, not only for project64 or Gliden64, but indeed can be solved by having the option to enable a windowed fullscreen/borderless instead of exclusive fullscreen, because windows 10 takes this as HDR content even if Gliden64 + Project64 are only SDR capable.

Also (I don't know if this can be related, the mouse is stuck when entering in fullscreen mode, and cannot be moved or hide) 

Using other plugins such as Jabo doesn't have this problems (Mouse stuck problem & HDR problem) 

Attached you'll find 2 image (You can see the color difference between windowed & Fullscreen) sorry for the quality.

![2](https://user-images.githubusercontent.com/12205048/122630989-3b307480-d0c8-11eb-9bd8-140c88241dd9.jpg)

![1](https://user-images.githubusercontent.com/12205048/122630984-32d83980-d0c8-11eb-866e-ffb9136c5a7b.jpg)

**Comment by LuismaSP89** [comment] 2021-06-20 01:38
Note: I found that other emulators like snes9x (x64 version) bypassed this problem with HDR in the latest windows versions by using a emulated fullscreen without borders. And works like a charm.
![1](https://user-images.githubusercontent.com/12205048/122659439-96ba3b00-d178-11eb-97a1-ae717b9d0897.jpg)

**Comment by gonetz** [comment] 2021-08-28 09:37
Any links to articles or example of how it can be done would be nice.

**Comment by LuismaSP89** [comment] 2021-08-28 11:40
I'll check if I can found the PR that added it to the snes9x. In any case, this "emulated fullscreen" feature is the same as most PC games had, "windowed fullscreen" or "windowed borderless" instead of fullscreen.

**Comment by LuismaSP89** [comment] 2021-08-28 12:42
I saw a lot of programs that allow this, maybe can take the code of a free one?

Anyway, there's a lot of info about this:

https://www.pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed

https://www.makeuseof.com/tag/windowed-fullscreen-borderless-modes/

https://westechsolutions.net/sites/WindowedBorderlessGaming/

**Comment by Jj0YzL5nvJ** [comment] 2021-08-28 15:19
https://github.com/project64/project64/issues/2068#issuecomment-873341593

**Comment by gonetz** [comment] 2021-08-28 15:39
I mean "example of how it can be done", that is some OpenGL scenario, to not invent a wheel.

**Comment by Jj0YzL5nvJ** [comment] 2021-08-28 15:59
[mpv can do borderless with any API, not only OpenGL.](https://mpv.io/manual/master/#video-output-drivers)

**Comment by LuismaSP89** [comment] 2021-08-28 16:05
@Jj0YzL5nvJ Yes, I posted also other apps to allow borderless in any app on windows, there are a lot, but the idea is to integrate borderless in the plugin without needed to install 3rd party apps.

Info related with borderless in Opengl can be found here, hope this helps:

https://community.khronos.org/t/windowed-fullscreen-mode/21571/9

https://stackoverflow.com/questions/22259067/opengl-non-exclusive-fullscreen-mode-a-k-a-fullscreen-borderless-window


Also it can be done by using: PFD_SUPPORT_COMPOSITION in the PIXELFORMATDESCRIPTOR of ChoosePixelFormat/SetPixelFormat

https://www.opengl.org/pipeline/article/vol003_7/

**Comment by Jj0YzL5nvJ** [comment] 2021-08-28 16:22
The one that has to implement the option is the client (Project64, 1964, Mupen64Plus, m64p, etc), not the plugin.

**Comment by LuismaSP89** [comment] 2021-08-28 16:42
The thing is that this HDR problem is only happening with Gliden64, other plugins such as jabo don't look with washed colors when HDR + fullscreen is enabled. So maybe the plugin itself can solve something here. Also in the info I posted, there is information on how this technique works on opengl, then the graphics backend has something to do with it. 

Of course this is not urgent and there is other issues to solve before. But in case this can be solved quickly by creating/copy a few lines of code, since there is a lot of info about windowed fullscreen in opengl, I think a lot of people will appreciate it.

**Comment by Jj0YzL5nvJ** [comment] 2021-08-28 18:11
The issues of HDR with OpenGL in NVIDIA hardware are "[driver product limitations](https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/226956/10-bit-color-output-on-consumer-cards/)".
[ANGLE can effectively skip such "limitation"](https://github.com/project64/project64/issues/2068#issuecomment-873187795).

**Comment by LuismaSP89** [comment] 2021-08-28 18:57
@Jj0YzL5nvJ I don't get your point. I mean, what's the problem for allowing the plugin can have windowed borderless option and solve the issue by doing this little trick such as other emulators do? Opengl can support HDR mode with this workaround in gliden64. 

Other emulators such as rpcs3 and dolphin have an opengl backend and the HDR works fine. In case of snes9x it doesn't. They implemented this option and luckily this solves the issue. 

Like I said of course there are other important things to do before. But if with a little research and a few lines of code a option like this can be implemented, I don't see the reason to discuss about it. Indeed if the dev see that he is going to spend a lot of time to implement this, he can decide if yes or not.

**Comment by gonetz** [comment] 2021-08-29 04:04
> The one that has to implement the option is the client (Project64, 1964, Mupen64Plus, m64p, etc), not the plugin.

It is true for Mupen64Plus. Project64 and 1964 do not deal with drawing context, it is plugin's duty.

**Comment by gonetz** [comment] 2021-08-29 04:09
> @gonetz Info related with borderless in Opengl can be found here, hope this helps:

Thanks! These topics have some useful info, but not the whole working scenario. I'll try to play with pixel flags, but it would be better to find some already working piece of code.

**Comment by LuismaSP89** [comment] 2021-08-29 09:11
@gonetz Sorry, I don't know much of programming, so I don't know what to look for. I'll try to do a deeper search, in that links there are code to do this in opengl, I thought that will be enough.

**Comment by LuismaSP89** [comment] 2021-08-29 10:56
Maybe here? 

https://ecode.dev/transparent-framebuffer-borderless-window-using-glfw/amp/

https://github.com/ands/borderless-window-opengl/blob/master/borderless-window-rendering.cpp

**Comment by gonetz** [comment] 2021-08-30 08:09
> Maybe here?
> 
> https://ecode.dev/transparent-framebuffer-borderless-window-using-glfw/amp/
> 
> https://github.com/ands/borderless-window-opengl/blob/master/borderless-window-rendering.cpp

These example use some high-level OpenGL libraries. All work is made under the hood. We use OpenGL directly.
However, both GLFW and ImGui are opensource libraries, so I should be able to extract the necessary code from them. Thanks!

**Comment by gonetz** [comment] 2022-02-20 07:24
I tried to implement that feature but failed. May be someone else can take this task.

**Comment by Jj0YzL5nvJ** [comment] 2022-02-20 07:44
If the plugin can't create a 480p **borderless window**, how is it supposed to do the rest?

**Comment by LuismaSP89** [comment] 2022-02-20 11:09
It's a shame, because the bug with HDR still persists even with a different OS "from W10 to W11" the colors are totally washed in fullscreen but looks fine on window mode.  I don't know how the other emulators or games do to this feature of borderless fullscreen, it's a hack or something?

**Comment by LuismaSP89** [comment] 2022-02-20 11:16
I'll try with this:https://www.pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed

Let's hope it can help with the issue.

**Comment by Jj0YzL5nvJ** [comment] 2022-02-21 10:00
>  I don't know how the other emulators or games do to this feature of borderless fullscreen, it's a hack or something?

It's literally a f***ing window without any properties (minimize, maximize, resize, border, move, close) that takes up the entire screen with the attribute always on top.
In the old days IDEs like Delphi used it as a template and it was the programmer who enabled those properties. Modern IDEs do exactly the opposite.
The one that has to program this function is the frontend. The window has its own graphics acceleration and "_simulates a monitor_" on top of it.

**Comment by LuismaSP89** [comment] 2022-02-21 11:08
> > I don't know how the other emulators or games do to this feature of borderless fullscreen, it's a hack or something?
> 
> It's literally a f***ing window without any properties (minimize, maximize, resize, border, move, close) that takes up the entire screen with the attribute always on top. In the old days IDEs like Delphi used it as a template and it was the programmer who enabled those properties. Modern IDEs do exactly the opposite. The one that has to program this function is the frontend. The window has its own graphics acceleration and "_simulates a monitor_" (video output signal) on top of it.

For me it's also just a window, and seems an easy task to do, since most emulators have this function. But since I'm not a programmer, it's only my point of view, it can be a nightmare to implement even if it looks easy from the outside.

Anyway, like Gonetz said (And some people in the project64 forums) this must be implemented by the plugin, not the project64.

**Comment by Jj0YzL5nvJ** [comment] 2022-02-22 02:13
> For me it's also just a window, and seems an easy task to do, since most emulators have this function. But since I'm not a programmer, it's only my point of view, it can be a nightmare to implement even if it looks easy from the outside.

It's as difficult as playing a video file in any arbitrary resolution and any aspect ratio in real time.
<img src="https://user-images.githubusercontent.com/1769603/36644935-bd55d0b6-1a61-11e8-8f87-a8407e69e6f2.gif" alt="" class="">

> Anyway, like Gonetz said (And some people in the project64 forums) this must be implemented by the plugin, not the project64.

That just proves that none of them have the faintest idea how **the fake fullscreen** (AKA _fullscreen_) works in video players.

**Comment by oddMLan** [comment] 2022-02-22 05:56
@LuismaSP89 @Jj0YzL5nvJ try this dll with Project64
[GLideN64_borderless_wtl.zip](https://github.com/gonetz/GLideN64/files/8113972/GLideN64_borderless_wtl.zip)
I don't have an HDR monitor to test so can you try it for me?

Explanation: Nothing fancy, I just commented out the winapi call `ChangeDisplaySettings` in windows_DiplayWindow.cpp. I believe it has that intended borderless window effect. For instance, this is what happens when I set a Full screen res of 800x600. When you set your resolution to match your current resolution it actually takes up the whole screen.
![gliden_borderless_test](https://user-images.githubusercontent.com/7278372/155071599-2e56049d-1377-462b-bc9a-0ea251b7c9ca.png)

**Comment by LuismaSP89** [comment] 2022-02-22 07:12
> > For me it's also just a window, and seems an easy task to do, since most emulators have this function. But since I'm not a programmer, it's only my point of view, it can be a nightmare to implement even if it looks easy from the outside.
> 
> It's as difficult as playing a video file in any arbitrary resolution and any aspect ratio in real time. ![](https://user-images.githubusercontent.com/1769603/36644935-bd55d0b6-1a61-11e8-8f87-a8407e69e6f2.gif)
> 
> > Anyway, like Gonetz said (And some people in the project64 forums) this must be implemented by the plugin, not the project64.
> 
> That just proves that none of them have the faintest idea how **THE FAKE FULLSCREEN** (AKA _fullscreen_) works in video players.

Yes, ok, ok, we know you're a god. But if is that easy, then perhaps your highness can implement the code for the Gliden64 instead of wasting time here.

**Comment by LuismaSP89** [comment] 2022-02-22 07:13
> @LuismaSP89 @Jj0YzL5nvJ try this dll with Project64 [GLideN64_borderless_wtl.zip](https://github.com/gonetz/GLideN64/files/8113972/GLideN64_borderless_wtl.zip) I don't have an HDR monitor to test so can you try it for me?
> 
> Explanation: Nothing fancy, I just commented out the winapi call `ChangeDisplaySettings` in windows_DiplayWindow.cpp. I believe it has that intended borderless window effect. For instance, this is what happens when I set a Full screen res of 800x600. When you set your resolution to match your current resolution it actually takes up the whole screen. ![gliden_borderless_test](https://user-images.githubusercontent.com/7278372/155071599-2e56049d-1377-462b-bc9a-0ea251b7c9ca.png)

I'll try that and let you know. Thanks a lot 👍

**Comment by Jj0YzL5nvJ** [comment] 2022-02-22 08:29
> Yes, ok, ok, we know you're a god. But if is that easy, then perhaps your highness can implement the code for the Gliden64 instead of wasting time here.

I'm not God, I'm not dead... yet. This highness uses his spare time as he pleases and only knows how to program in dead languages, thanks for your concern. /s

**Comment by LuismaSP89** [comment] 2022-02-22 10:30
> > Yes, ok, ok, we know you're a god. But if is that easy, then perhaps your highness can implement the code for the Gliden64 instead of wasting time here.
> 
> I'm not God, I'm not dead... yet. This highness uses his spare time as he pleases and only knows how to program in dead languages, thanks for your concern. /s

In that case, if you're not going to help with the development of this feature and you are only here to say that everybody knows nothing about programming this feature, (even the devs) I don't see the point of what are you doing here.

**Comment by Jj0YzL5nvJ** [comment] 2022-02-22 11:25
Now I understand your hostility, I never tried to convey that, I just paid very little attention to my translation from Spanish to English. I already corrected my bad translation, never trust 100% in Google Translate =P

Even so, I support my second sentence. Knowing how to code has absolutely nothing to do with understanding an API and all its behaviours.

**Comment by LuismaSP89** [comment] 2022-02-22 11:46
It's a shame we cannot speak in spanish, because this kind of forums are in english, I'm for spain. 

I didn't pretended to be hostile, but understand that even if we think this is an easy task to do, we don't know how to do it, and we cannot judge a dev if he cannot implement this feature.

**Comment by LuismaSP89** [comment] 2022-02-22 19:05
> @LuismaSP89 @Jj0YzL5nvJ try this dll with Project64 [GLideN64_borderless_wtl.zip](https://github.com/gonetz/GLideN64/files/8113972/GLideN64_borderless_wtl.zip) I don't have an HDR monitor to test so can you try it for me?
> 
> Explanation: Nothing fancy, I just commented out the winapi call `ChangeDisplaySettings` in windows_DiplayWindow.cpp. I believe it has that intended borderless window effect. For instance, this is what happens when I set a Full screen res of 800x600. When you set your resolution to match your current resolution it actually takes up the whole screen. ![gliden_borderless_test](https://user-images.githubusercontent.com/7278372/155071599-2e56049d-1377-462b-bc9a-0ea251b7c9ca.png)

This is awesome, this solves the issue! Is there any way to implement this into the plugin's code? It would be awesome.

**Comment by Jj0YzL5nvJ** [comment] 2022-02-22 21:30
> It's a shame we cannot speak in spanish, because this kind of forums are in english, I'm for spain.

Podemos hablar, pero no aportarimos nada con ello, yo soy de México, de la parte norte del pais. NADA que ver con los chilangos ¬¬

I've tested it @oddMLan, it works fine as "Non-exclusive Fullscreen Mode" if used at full resolution... but not good at "production level". But it is good enough for most user cases.

A real implementation would have the ability to re-render the image generated by the plugin at a higher resolution for a more retro feel (480p to 4K). Or 8K to 1080p for benchmarking, etc.

See #2410 for more examples.

**Comment by oddMLan** [comment] 2022-02-23 00:23
Ya cásense hombre 😄 

> A real implementation would have the ability to re-render the image generated by the plugin at a higher resolution for a more retro feel (480p to 4K). Or 8K to 1080p for benchmarking, etc.

Isn't that already possible by using "Native resolution factor"? set that to 1x and set the fullscreen res to match your current resolution, then it should render at 240p. Use 2x if you want 480p.

**Comment by LuismaSP89** [comment] 2022-02-23 17:08
Yes, maybe it can improved, but for least, it solves the HDR issue for everybody with an HDR screen, wich is becoming more frequently since all new monitors/TV's have HDR. And if the issue can be solved by only changing one line, maybe @gonetz agree with the "fix"

**Comment by Jj0YzL5nvJ** [comment] 2022-02-24 17:11
Personally, I would prefer a borderless window mode that can be manipulated like the [example with mpv](https://imgur.com/a/C4rbEM8). With such support, multi-monitor setups will be easier for the user to arrange and more convenient for streams.

<img src="https://i.imgur.com/moVEHTH.gif" alt="" class="">

**Comment by gonetz** [comment] 2022-02-27 05:52
> Yes, maybe it can be improved, but at least, it solves the HDR issue for everybody with an HDR screen, wich is becoming more frequently since all new monitors/TV's have HDR.

My monitor has HDR support, but I turned it off. I use it only for games with HDR support.

> And if the issue can be solved by only changing one line, maybe @gonetz agree with the "fix"

I don't mind, but I suppose it should be optional, which means new option to support in GUI and CLI. Could anybody make a PR with that?

**Comment by LuismaSP89** [comment] 2022-02-27 10:50
> > Yes, maybe it can be improved, but at least, it solves the HDR issue for everybody with an HDR screen, wich is becoming more frequently since all new monitors/TV's have HDR.
> 
> My monitor has HDR support, but I turned it off. I use it only for games with HDR support.
> 
> > And if the issue can be solved by only changing one line, maybe @gonetz agree with the "fix"
> 
> I don't mind, but I suppose it should be optional, which means new option to support in GUI and CLI. Could anybody make a PR with that?

I think nobody here "except you" has programming skills to do the PR 😅. Who is the person who usually do the PR's related with the QT5 GUI? Maybe we can ask him.

**Comment by LuismaSP89** [comment] 2022-02-27 11:06
Another think we can just do, is to add the feature "disabled by default" and the the ability to change it using the config file. At least until someone adds the feature to the GUI. This is the way others emulators do this, for example RPCS3, some things can be changed using the .ini file only "mostly experimental things" and after some time the main UI dev "megamouse is his name" adds it to the UI for everybody's use.

**Comment by LuismaSP89** [comment] 2022-04-24 22:53
Sorry to bother you @gonetz but since nobody is adding this option to the GUI, is there any posibility to implement this by changing a option in the gliden64 config file? at least to solve this problem until someone do a PR for adding this feature to the GUI.

Thank you so much,

**Comment by gonetz** [comment] 2022-05-15 17:45
Beta implementation:
Support Borderless windowed mode. #2686

Zilmar-spec only. Please test.

**Comment by oddMLan** [comment] 2022-05-15 18:57
Hey @gonetz! Nice to see you again.

On my 16:10 monitor (1440 x 900) the image is cropped with the Borderless Fullscreen option.
![image](https://user-images.githubusercontent.com/7278372/168489320-553f34f7-a875-4834-a6cc-e112f84603d4.png)

Exclusive fullscreen = Current screen resolution, it works correctly here.
![image](https://user-images.githubusercontent.com/7278372/168489312-453ff5be-eea9-4817-9907-5cf74c71f176.png)

**Comment by LuismaSP89** [comment] 2022-05-15 20:56
Excuse my ignorance, but how I can download this build in order to test? I don't know how to build from github, is there any way to download from the github jobs/PR or something?

**Comment by oddMLan** [comment] 2022-05-15 21:57
> Excuse my ignorance, but how I can download this build in order to test? I don't know how to build from github, is there any way to download from the github jobs/PR or something?

![image](https://user-images.githubusercontent.com/7278372/168495289-1c1f6ee8-1c72-4e03-937d-f553a5808a55.png)
![image](https://user-images.githubusercontent.com/7278372/168495543-97e21f99-1293-408b-ad88-c32865ce4663.png)

**Comment by LuismaSP89** [comment] 2022-05-16 10:12
> > Excuse my ignorance, but how I can download this build in order to test? I don't know how to build from github, is there any way to download from the github jobs/PR or something?
> 
> ![image](https://user-images.githubusercontent.com/7278372/168495289-1c1f6ee8-1c72-4e03-937d-f553a5808a55.png) ![image](https://user-images.githubusercontent.com/7278372/168495543-97e21f99-1293-408b-ad88-c32865ce4663.png)

Nice, thanks a lot!

**Comment by LuismaSP89** [comment] 2022-05-16 17:51
> Hey @gonetz! Nice to see you again.
> 
> On my 16:10 monitor (1440 x 900) the image is cropped with the Borderless Fullscreen option. ![image](https://user-images.githubusercontent.com/7278372/168489320-553f34f7-a875-4834-a6cc-e112f84603d4.png)
> 
> Exclusive fullscreen = Current screen resolution, it works correctly here. ![GLideN64_Diddy_Kong_Racing_000](https://user-images.githubusercontent.com/7278372/168489402-535c3de1-1b3f-4ec3-9753-a4688d9589b5.png)
> 
> EDIT: You're obtaining the maximum width and height supported by the display, not the current resolution. I set my screen resolution to 1280 x 1024, and borderless used 1440 x 1024 again.

Yes, same problem here, I have a 4k TV (But with 1920x1080 resolution set in windows 11 config) and the games are extremely zoom-in, if I set the windows desktop resolution to 4k in the w11 config, then it works without that huge zoom-in (But extremely slow since I'm forcing 4k resolution on my a bit-old-computer. Sure this is taking the maximum screen resolution instead of the selected in the windows 10/11 desktop settings.

**Comment by gonetz** [comment] 2022-05-22 08:54
Thanks for the feedback!

 >EDIT: You're obtaining the maximum width and height supported by the display, not the current resolution. I set my screen resolution to 1280 x 1024, and borderless used 1440 x 1024 again.
 
Yep, I did not expect that somebody will use non-native display resolution. 
The issue is fixed. Now the feature should work with any display mode without need to open config dialog.

**Comment by LuismaSP89** [comment] 2022-05-22 12:19
> Thanks for the feedback!
> 
> > EDIT: You're obtaining the maximum width and height supported by the display, not the current resolution. I set my screen resolution to 1280 x 1024, and borderless used 1440 x 1024 again.
> 
> Yep, I did not expect that somebody will use non-native display resolution. The issue is fixed. Now the feature should work with any display mode without need to open config dialog.

Now is working very nice Sir,  ; ) thank you so much for all your hard work.

**Comment by gonetz** [comment] 2022-05-22 15:40
New update: if you have several monitors, you may select to which one the borderless window should go.
I still don't know, how to select display for true fullscreen mode, but this option is a good workaround.

**Comment by gonetz** [comment] 2022-06-12 06:11
Fixed with PR #2686

**Closed by gonetz** 2022-06-12 06:11 UTC

**Comment by ImSpecial** [comment] 2022-06-17 21:30
So I downloaded the latest "a2f1660" (WTL) plugin, but where in the settings to I find the option to use Borderless Window?

**Comment by oddMLan** [comment] 2022-06-18 18:02
WTL hasnt been updated in quite a while, use the Qt version

**Comment by ImSpecial** [comment] 2022-06-18 23:25
This was it and solved it! :)

So what's the point of WTL? I've been using it all this time, because.... it was what I always have been using.

**Comment by oddMLan** [comment] 2022-06-19 18:32
It's the version that comes bundled with Project64 due to the Qt version being a lot bigger in filesize than Project64 itself, which can stress the bandwidth from their website. WTL is supposed to be 1:1 with Qt but it hasn't been updated in a while due to lack of maintainers (I was one of them, but I've been busy with life).

**Comment by daninthemix** [comment] 2023-02-24 05:21
Just to say this option doesn't work for me at all in Project64 Dev-4.0.0-6080 - I just get a normal window.
