### ISSUE TITLE
(Switch) Yoshi Story Background issue regression

### ISSUE THREAD

**Issue by HappehLemons** [gonetz/GLideN64#2304] opened 2020-07-10 18:16 UTC
Example here (https://github.com/libretro/mupen64plus-libretro-nx/issues/97)

Happening in 363c47a(https://github.com/libretro/mupen64plus-libretro-nx/commit/363c47aaa950b40a8d702518f4274ef83de4f3b5) on Nintendo Switch. bgMode set to OnePiece.

Doesn't happen with stripped, but game is unplayable with stripped as FPS drop to about 1 frame per second when moving.

Issue is not present in Lakkas May build on Switch with matching settings, but I can't find a build version on the core.

Also doesn't happen on PC.

**Comment by m4xw** [comment] 2020-07-14 09:21
This might've already been fixed between the time i made the release and current master.
Will confirm soon-ish

**Comment by m4xw** [comment] 2020-11-10 00:25
Still a issue for me

**Comment by fzurita** [comment] 2020-11-10 00:26
This is broken in Android too. It would probably be good to find it which commit broke it.
![yoshi_story-000](https://user-images.githubusercontent.com/11581687/98612100-6e548f00-22c1-11eb-8208-89e291f1034b.png)

**Comment by fzurita** [comment] 2020-11-12 01:12
@standard-two-simplex This is not specific to switch. It happens in Android as well. Issues with background in that game were initially introduced by the updated texture coordinate calculation: 4834359ec1ad031210fb6ade6c9d50e953b20d0e
In that commit, the background is completely blank. A follow up commit improved it slightly to what we see in the screenshots. I'm trying to find it.

**Comment by fzurita** [comment] 2020-11-12 02:05
@gonetz So you are aware, be2f2244a2a5d9238b6fa6f9cd03166dc2692454 Improved the situation but not fully fixed it. It leads to the screenshots above.

**Comment by gonetz** [comment] 2020-11-12 08:38
Ok

**Comment by standard-two-simplex** [comment] 2020-11-13 20:51
> Still a issue for me on Switch (aarch64) with Mesa + GL

The original issue happens when backgrounds are set to render in one piece. It seems we are clamping such textures in wrong boundaries. It is probably best to disable all clamping wrapping for special textures.

213b00cf503d8fadc06fbd7ca9cddf54d7f4a1d1 fixes the issue. I also initialized wrap bounds to 1024.0. Even if they are meant to be unused due to the flag wrapEn being 0, it is necessary to avoid divisions by 0.

So far I left the previous code for framebuffer textures, but perhaps it would be best to avoid clamping them too. @gonetz Should I PR as is or should I change the behaviour of framebuffer textures?

**Comment by standard-two-simplex** [comment] 2020-11-13 20:55
@fzurita Your issue seems different.

In the first pictures you can only see one Yoshi, which means a background is rendered in each frame, even if incorrectly. In yours there are lots of Yoshi's, which happens when the background isn't rendered in every frame, thus keeping the previous frame as background. 

Can you reproduce that behaviour consistently? I haven't managed to.

**Comment by fzurita** [comment] 2020-11-13 22:49
Yeah, I can reproduce that behavior consistently. It's also fixed by setting the background mode to stripped.

**Comment by fzurita** [comment] 2020-11-14 01:28
@standard-two-simplex I tested your fix and it works for Android as well. It gets rid of the duplicate yoshi's.

**Comment by gonetz** [comment] 2020-11-14 11:37
> So far I left the previous code for framebuffer textures, but perhaps it would be best to avoid clamping them too. @gonetz Should I PR as is or should I change the behaviour of framebuffer textures?

Frame buffer textures work the same as regular ones in most cases, since they are used instead of regular textures. I'm afraid that if we disable clamping for fb textures it may lead to regressions. So, please PR this change as it is, but we will keep in mind that clamping can be the source of issues with fb emulation.

**Closed** 2020-11-16 03:40 UTC

**Comment by m4xw** [comment] 2020-11-16 11:16
Looks good to me :)
Confirmed working on Switch as well, thanks for fixing it, for the longest time I thought its shenanigans in my GL state machine :P
