### ISSUE TITLE
Ogre Battle 64 rare failed assertion in battle scene

### ISSUE THREAD

**Issue by Aquatakat** [gonetz/GLideN64#107] opened 2014-11-06 20:14 UTC
![ss 2014-11-06 at 01 11 09](https://cloud.githubusercontent.com/assets/9537912/4943117/8743e314-65f1-11e4-83f2-51f7bbf02a6d.jpg)

I'm not sure what causes this. It seems to happen about one in every 30 scenes or so.

**Comment by oddMLan** [comment] 2016-05-13 22:15
I tested extensively all the games mentioned here (especially Ogre Battle 64) and I couldn't trigger a single time the Assertion error. Fixed?

But, I see you are using Mupen64plus. I just tested with the latest Project64 2.x

**Comment by olivieryuyu** [comment] 2016-07-17 17:23
I think sergei deactivate the displaying errors. Impossible to check.

**Comment by olivieryuyu** [comment] 2017-09-29 10:53
@gonetz 

how should we deal with this ticket?

**Comment by gonetz** [comment] 2017-09-29 11:55
Does the problem still exist?

**Comment by olivieryuyu** [comment] 2017-09-29 12:02
with a debug plugin, it seems so

![untitled](https://user-images.githubusercontent.com/8987490/31015132-d9109182-a51e-11e7-87bb-5548ba140634.jpg)

this is not the same message but I guess it is the same matter.

**Comment by gonetz** [comment] 2017-09-29 13:13
How to reproduce that?

**Comment by olivieryuyu** [comment] 2017-09-29 13:20
hmm I simply used the debug version of the plugin which has been posted in the fix sprite version, run the game and i get this screenshot.

**Comment by olivieryuyu** [comment] 2017-09-29 13:23
hmm i don't get this error in PJ64? Core bug?

**Comment by olivieryuyu** [comment] 2017-09-29 13:31
Ok so this screenshot is due to 1964. 

The problem does not seem to exist anymore.

Should I close?

**Comment by gonetz** [comment] 2017-09-29 13:33
Could you test with mupen64plus?
GL error can be caused by variety of reasons, it is not necessary  emu core issue. In most cases it is not emulator's issue at all.

**Comment by olivieryuyu** [comment] 2017-09-29 13:59
i would need a Mupenplus debug build for this

**Comment by gonetz** [comment] 2017-09-29 14:45
Debug build:
https://drive.google.com/file/d/0B0YqMPjGo3B2TWZkckpoVEFyZ0E/view?usp=sharing

**Comment by olivieryuyu** [comment] 2017-09-29 15:21
no, in Mupenplus I don't have this issue as well. Tested other games, seems to work. It seems I got a bug with 1964.

**Comment by gonetz** [comment] 2017-09-29 15:45
Thanks! Lets close it then.

**Closed by gonetz** 2017-09-29 15:45 UTC
