### ISSUE TITLE
"Rat attack flickers"

### ISSUE THREAD

**Issue by twarnercool2** [gonetz/GLideN64#845] opened 2016-01-28 18:41 UTC
When ever I try to play rat attack. The characters flickers.

**Comment by LegendOfDragoon** [comment] 2016-01-28 20:23
Wat emulator are you using?

**Comment by theboy181** [comment] 2016-01-28 20:43
Better question is "who actually plays Rat Attack?"  ;(

**Comment by twarnercool2** [comment] 2016-01-28 20:58
Emulator "Project 64". It works fine with Jabo plug in.

**Comment by twarnercool2** [comment] 2016-01-28 20:59
Well, I play "Rat attack" for testing. Got to make sure all games work well.

**Comment by LegendOfDragoon** [comment] 2016-01-28 21:18
CPU recompiler is bugged for that game on project 64. Try CPU interpreter, and see if that fixes the problem. If it doesn't fix it, then the issue really is GLideN64.

**Comment by twarnercool2** [comment] 2016-01-28 21:26
How do I change it to interpreter?

**Comment by purplemarshmallow** [comment] 2016-01-29 00:05
It's a problem with GLideN64's framebuffer emuation. See #600 
Disable framebuffer emulation as a workaround

**Comment by olivieryuyu** [comment] 2016-02-09 11:21
it is a duplicate of #600 

Can it be closed please?

**Closed** 2016-02-09 11:45 UTC
Labels: bug, duplicate
