### ISSUE TITLE
Add support for 64bit windows

### ISSUE THREAD

**Issue by AbiDrew** [gonetz/GLideN64#806] opened 2015-11-22 01:38 UTC
I was wondering if there were plans to add support for compiling a build for the newer 64bit versions of Project64 and mupen64plus on Windows based systems.  64bit should theoretically emulate the hardware of the n64 more efficiently netting a moderate performance increase over 32bit.  And since both major emulators for the Windows system now support 64bit builds on Windows I'd sure like to see some other options for graphics plugins that might have better support for certain games than the defaults while using the 64 bit builds.  Right now there are simply no other 64 bit Windows plugins.

**Comment by gonetz** [comment] 2015-11-22 06:13
Duplicate of #537 and #716 
Is it hard to use search before open new issue?

**Closed by gonetz** 2015-11-22 06:13 UTC
