### ISSUE TITLE
Other old glitch in GE...

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [gonetz/GLideN64#1136] opened 2016-09-24 23:22 UTC
Don't know if the mission of the Frigate ever been emulated properly, in any emulator or plugin with any setting.

http://imgur.com/a/COTd0
[GoldenEye 007 (U) [o1].zip](https://github.com/gonetz/GLideN64/files/491418/GoldenEye.007.U.o1.zip)

**Comment by SigmaVirus** [comment] 2016-09-25 06:16
Someone once said to me that the water is a low level triangle issue.

Apparently GoldenEye doesn't send the skies/water as display lists but rather directly to the RDP.
So they have to be handled separately, using code that translates them into visible polygons but it can be quite buggy.

@gonetz also once said and I quote 

> Issue with LLE triangle will not be fixed anytime soon.

So there you have it unless he's opinion have changed.

**Comment by gonetz** [comment] 2016-09-26 03:33
As I remember, it was already reported. And yes, it will not be fixed until somebody smart will fix LLE triangle code for hardware renders.

**Comment by gonetz** [comment] 2016-09-27 03:43
Duplicate of #459

**Closed by gonetz** 2016-09-27 03:43 UTC
Labels: duplicate
