### ISSUE TITLE
Tetrisphere "Lines"

### ISSUE THREAD

**Issue by thecoreyburton** [gonetz/GLideN64#450] opened 2015-05-01 16:10 UTC
This seems to occur on Tetrisphere (intro screen).
Emulator used: anything Zilmar spec. Unsure about other versions
![lines](https://cloud.githubusercontent.com/assets/12134368/7433002/5e278148-f070-11e4-8fcf-04d09565676d.jpg)

**Comment by thecoreyburton** [comment] 2015-05-08 16:22
Additionally, in the 1.1 release disabling frame buffer emulation makes these lines flicker.

**Comment by purplemarshmallow** [comment] 2015-05-11 08:06
there are no lines when rendering in 640x480 or lower
#290 same issue?

**Comment by standard-two-simplex** [comment] 2015-07-01 06:33
@gonetz I spotted this piece of code in gSP.cpp, constructor of ObjCoordinates:
``` lrs = uls + (lrx - ulx) * scaleW ```
``` lrx - ulx ``` is the size width of the frame -1, so ``` lrs - uls ``` will become ```(size-1)*scale```. Shouldn't it be ```size*scale - 1 ``` ?

**Comment by gonetz** [comment] 2015-07-03 08:32
May be you're right. Need to check it with game, which uses scaled sprites.

**Comment by olivieryuyu** [comment] 2015-07-09 05:37
megaman 64 seems to have the same issue

**Comment by AmbientMalice** [comment] 2016-03-17 04:49
Fixed by native. (Although @standard-two-simplex did mention a possible scaling problem.)

**Comment by olivieryuyu** [comment] 2016-04-09 15:47
ok fixed in native, can it be in non native? what about the suggestion of standard-two-simplex?

**Comment by gonetz** [comment] 2016-04-09 16:39
>can it be in non native?

I don't see how.

> what about the suggestion of standard-two-simplex?

His suggestion is about S2DEX microcode. This issue is in texrects.

**Comment by oddMLan** [comment] 2016-04-09 21:00
What about an approach like the PCSX2 team?
http://pcsx2.net/269-major-gsdx-progress-monthly-reports.html
http://pcsx2.net/developer-blog/267-explanation-hacks-needed-for-upscaling-glitches.html

**Comment by gonetz** [comment] 2016-04-10 06:36
Well, that " Align sprite hack" works the same, as Glide64 increase_texrect_edge option. The same hack. As I understand, the only important difference is that "The hack will detect rectangle primitives that are too small and then extend them". Glide64 has no small primitive detection. It would be useful to implement and apply the hack automatically. Could you point me on source code, where that " Align sprite hack" is implemented?

Note, the hack saves only black lines issue. Texture alignment issues, like in Mario Kart title screen, are caused by bilinear filtering and can be solved only with native resolution.

**Comment by AmbientMalice** [comment] 2016-04-10 07:11
This is all I could find. GSDX is structured so strangely. It makes finding things difficult. https://github.com/PCSX2/pcsx2/blob/master/plugins/GSdx/GSRendererHW.cpp#L523

>Note, the hack saves only black lines issue. Texture alignment issues, like in Mario Kart title screen, are caused by bilinear filtering and can be solved only with native resolution. 

There's also the 2D fix branch, but that has complications.

**Comment by gonetz** [comment] 2016-04-10 08:38
Thanks! I understand the idea. It is close to what I do in my 2DFix branch.
Ok, I'll make that hack, it's not hard.

**Comment by gonetz** [comment] 2016-04-10 09:03
Which games suffer from black lines issue? Beside Army Men - Air Combat

**Comment by olivieryuyu** [comment] 2016-04-10 09:13
40 winks, sf rush, california games, few others. Need to check later

**Comment by AmbientMalice** [comment] 2016-04-10 09:25
Mario Kart 64 portraits in character select develop vertical lines. Certain Rainbow 6 screens get thick lines.

**Comment by gonetz** [comment] 2016-04-10 10:08
40 winks, sf rush, california games - different issue. It is not a  gap between polygons, it is something wrong with texture mapping. Mario Kart 64 issue also has different origin.

Thus, the hack is useful for 3-4 games.

**Comment by olivieryuyu** [comment] 2016-04-10 10:35
you have also new tetris, megaman64, tetrisphere.

**Comment by AmbientMalice** [comment] 2016-04-10 10:36
>Thus, the hack is useful for 3-4 games.

That's a pity. But better than nothing, I suppose.

**Comment by olivieryuyu** [comment] 2016-04-10 10:42
also would it fix the error in quest64 texts?

**Comment by AmbientMalice** [comment] 2016-04-10 10:45
>also would it fix the error in quest64 texts?

That's an alpha issue, AFAIK. Very different.

**Comment by olivieryuyu** [comment] 2016-04-10 10:51
odd that native fix the matter :(

**Comment by gonetz** [comment] 2016-04-10 10:54
> also would it fix the error in quest64 texts?
No. Only gaps between polygons.

**Comment by gonetz** [comment] 2016-04-10 12:32
Black lines fix implemented in fix_black_lines branch.
Mupen64plus binary:
https://drive.google.com/file/d/0B0YqMPjGo3B2SW0tZWNtQkJEeFE/view?usp=sharing

I also made a fix 71e3475ccf7
which fixes logo in sf rush, california

The meaning of that fix is simple. The problem explained here:
http://pcsx2.net/developer-blog/267-explanation-hacks-needed-for-upscaling-glitches.html
in native - 2x scale pictures.
In native resolution pixel's texture coordinate points on the center of a texel. In high-res it points on texel's edge. Last row of pixels point to edge of last row of texels and eventually wrap to the first row of texels. That is last row of pixels take color from the beginning of the texture. Force texture clamp does not allow the texture coordinate to wrap. This is a hack to avoid that problem with upscaling.
It is not my invention, it was made yet by orkin. The hack did not work for situation when texture coordinates are upside-down, as in sf rush logo. I fixed it.

Unfortunately, that hack does not help for text in these games. The characters are taken from one large font texture, and pixels on the edge of the character may point to adjacent character in the font texture. Texture clamp can't help here. There is no good solution.

**Comment by olivieryuyu** [comment] 2016-04-10 17:51
well lines are still here in tetrisphere during intro:

![disuof](https://cloud.githubusercontent.com/assets/8987490/14411906/87a7f6e8-ff55-11e5-8171-10971ef357f1.jpg)

**Comment by gonetz** [comment] 2016-04-11 08:31
"small primitive detection" method is limited. It works only for 2D images rendered by "strips", that is line by line. This image is loaded by "tiles" and problem polygons not detected.

I'll add an option to force texrects alignment. It will work as Glide64 increase_texrect_edge option, for all texrects.

**Comment by olivieryuyu** [comment] 2016-04-11 08:33
I believe this increase_texrect_edge option will be the best.

btw how does it work in Lemmy plugin? there is not line and i cannot see hacks in it (but i may miss something?)

**Comment by AmbientMalice** [comment] 2016-04-11 09:01
>I'll add an option to force texrects alignment. It will work as Glide64 increase_texrect_edge option, for all texrects.

Maybe it should only be enabled when rendering above 1x?

**Comment by gonetz** [comment] 2016-04-11 09:42
>I believe this increase_texrect_edge option will be the best.

It will increase edges for all texrects, thus all texrects will be slightly incorrect.

> btw how does it work in Lemmy plugin?

It works because Lemmy plugin calculates texture coordinates incorrectly. As the result, images are slightly oblate.

> Maybe it should only be enabled when rendering above 1x?

Yes, it has no use for native resolution.

**Comment by gonetz** [comment] 2016-04-12 11:25
Added "Force" option

**Comment by olivieryuyu** [comment] 2016-05-17 19:05
that should be closed now, no?

**Closed** 2016-05-18 03:24 UTC
