### ISSUE TITLE
Top Gear Hyper Bike

### ISSUE THREAD

**Issue by schubertguilherme** [gonetz/GLideN64#2032] opened 2019-04-01 11:26 UTC
Hello community and friends. This issue really not fix in HLE (Gliden 64)... Angrylon's LLE, is very very hard, unplayable some computer's.

![dfgfgfdgd](https://user-images.githubusercontent.com/36903073/55324233-cf668080-5457-11e9-971e-3caaf2d1437d.jpg)

**Comment by gonetz** [comment] 2019-04-01 14:32
Duplicate of #257

**Closed by gonetz** 2019-04-01 14:32 UTC
Labels: duplicate
