### ISSUE TITLE
Killer Instinct Gold - Sky flashes in second arcade match

### ISSUE THREAD

**Issue by orbea** [gonetz/GLideN64#1146] opened 2016-09-29 22:49 UTC
OS: `Slackware64-current`
`mupen64plus-2016.09.13_5fa30ab-x86_64-1_SBo`
`GLideN64-d5412d3_2016.09.27_master-x86_64-1_git`

In the game `Killer Instinct Gold` the sky will frequently flash in the second arcade match. This does not happen with angrylion or real hardware as seen in the following video. This is also reproducible with GLupeN64.

https://youtube.com/watch?v=0-7sNrbvstk

apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/mupen64plus/gliden64_Killer_Instinct_Gold.trace.xz
apitrace log - http://pastebin.com/4weY4LMC

**Comment by gonetz** [comment] 2016-09-30 06:50
Duplicate of #406

**Closed by gonetz** 2016-09-30 06:50 UTC
Labels: duplicate
