### ISSUE TITLE
Enhancement Super Sprite?

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1473] opened 2017-04-23 17:11 UTC
Would it be possible to make super sprites in GLideN64 to help stop sprite looking like they are split? The inspiration is from http://www.cs.cmu.edu/~tom7/zelda/

MK64 menu items that rotate look like they have black seems. Maybe Super Sprites could help these annoyances?

**Comment by gonetz** [comment] 2017-04-28 08:16
I'm not sure what you mean by 'super sprite'. If 'super sprite' is aggregation of smaller sprites - yes, 'render 2D in native res' option works like this: combines 2D elements to one 'super sprite', which is then rendered do screen.

**Comment by theboy181** [comment] 2017-04-28 14:46
If this is the case why do we still get the black line on the MK64 character select sceen?

**Comment by Biofreak1987** [comment] 2017-04-28 15:14
I can't reproduce black lines on the MK64 character select screen when "Render 2D elements in N64 resolution" is checked.

![project64_2017-04-28_17-13-52](https://cloud.githubusercontent.com/assets/4711816/25535048/19521b2e-2c36-11e7-9dee-266ef6ae7fcb.png)

**Comment by tony971** [comment] 2017-04-29 00:57
@theboy181 It's [this issue](http://pcsx2.net/269-major-gsdx-progress-monthly-reports.html). GLideN64 might be able to add a similar hack.

**Comment by theboy181** [comment] 2017-04-29 03:37
Thanks for linking that. I read this before. I thought gonetz has examined this already.

**Comment by gonetz** [comment] 2017-04-29 10:08
Yes, I already examined the issue pointed by @tony971. This issues is fixed by "Fix black lines between 2D elements" option. It helps many games, where black lines caused by rounding. Mario Kart 2D issues are somehow different and can't be fixed by that option. Another example, where it does not work is Ogre Battle 64.

**Comment by theboy181** [comment] 2017-10-01 23:09
@gonetz is it possible to have something like the video above? 

Does GLideN64 take a sprite in its entirety (complete sprite, not one piece) then apply the biliner filtering they copy it to the screen? wouldn't something like this improve the quality, and git rid of the bad edges?

Here is the part of the video that could apply to N64 2d Sprites

https://youtu.be/xDxjbXAqTPg?t=561

**Comment by theboy181** [comment] 2017-10-01 23:24
@gonetz is it possible to have something like the video above? 

Does GLideN64 take a sprite in its entirety (complete sprite, not one piece) then apply the biliner filtering they copy it to the screen? wouldn't something like this improve the quality, and git rid of the bad edges?

Here is the part of the video that could apply to N64 2d Sprites

https://youtu.be/xDxjbXAqTPg?t=561  

reached out to the developer - 

http://radar.spacebar.org/f/a/weblog/docomment/1/1131

**Comment by AmbientMalice** [comment] 2017-10-01 23:54
>Does GLideN64 take a sprite in its entirety (complete sprite, not one piece) then apply the biliner filtering they copy it to the screen?

That's what Render 2D elements in N64 resolution does. IMO, it should ideally be enabled by default for certain games, such as Mario Kart 64 and Resident Evil 2, but it has some minor glitching and has a performance impact.

**Comment by theboy181** [comment] 2017-10-02 00:31
Does that make them get filtered when they are stitched as one super sprite, or after? 
![image](https://user-images.githubusercontent.com/9299743/31060792-404baeee-a6ce-11e7-8703-5fbce6d10616.png)

**Comment by theboy181** [comment] 2017-10-02 00:35
Is there a more accurate way to have the this way of filtering match AL RDP?

**Comment by theboy181** [comment] 2017-10-02 00:41
Is there a more accurate way to have the this way of filtering match AL RDP?

Using X2 in texture enhancement seems to break this function to. Is this to be expected?

**Comment by AmbientMalice** [comment] 2017-10-02 00:52
>Is there a more accurate way to have the this way of filtering match AL RDP?

Unlikely. This is the price of rendering above native resolution on the N64. You're never going to get 100% accuracy. However, GLideN64's texture handling is somewhat inaccurate, and if standard-two-simplex implements his planned fixes some of these texture problems might disappear or be alleviated.

![gliden64_mariokart64_004](https://user-images.githubusercontent.com/10704701/31060923-8e507184-a75e-11e7-8b27-e24b2a4eb3f1.jpg)
![gliden64_mariokart64_005](https://user-images.githubusercontent.com/10704701/31060924-8e554a1a-a75e-11e7-89f1-6666b3ec1f0c.jpg)

>Using X2 in texture enhancement seems to break this function to. Is this to be expected?
Yes. It kind of defeats the purpose of the function, and Gonetz should probably forcibly disable it.

Some information on the feature can be found here: http://gliden64.blogspot.com.au/2015/11/improved-2d-and-other-fixes.html

Another example of what the feature does:

![gliden64_resident_evil_ii_000](https://user-images.githubusercontent.com/10704701/31060984-7010801e-a75f-11e7-9979-50d68541a9a3.jpg)
![gliden64_resident_evil_ii_001](https://user-images.githubusercontent.com/10704701/31060985-7041d43e-a75f-11e7-9f53-db7463c314aa.jpg)

![image](https://user-images.githubusercontent.com/10704701/31060965-1b3ec14a-a75f-11e7-8969-9894a1ccb955.png)

Note the slight glitching along the edge of the portrait.

**Comment by theboy181** [comment] 2017-10-02 00:56
I would think integer scaling after the filter would work well to keep it looking as clean as possible. 

Thanks for the breakdown its helpful. 

Just to confirm this is using the super sprite concept as described in the video I linked?

**Comment by Frank-74** [comment] 2017-10-02 01:01
I'm going to try building GLideN64 again, now that it's fixed for VS2015.
@AmbientMalice Are you referring to this branch? https://github.com/gonetz/GLideN64/tree/fix_sprite_size

**Comment by AmbientMalice** [comment] 2017-10-02 01:12
@theboy181 GLideN64 is already using integer scaling. That's what 2x native does, for example.

>Just to confirm this is using the super sprite concept as described in the video I linked?

The concepts outlined in http://www.cs.cmu.edu/%7Etom7/zelda/zelda.pdf don't really translate to N64 games. NES games were all fairly simple and were programmed in a reasonably predictable way due to harsh hardware constraints. N64 games are nothing like that. What he's doing involves a heavily modified NES emulator running NES games that feature 2D sprites arranged into predictable grids.

@Frank-74 No, I'm referring to the changes proposed here: https://github.com/gonetz/GLideN64/issues/1603

**Closed** 2018-05-06 16:59 UTC
