### ISSUE TITLE
Missing option for vsync

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#1385] opened 2017-02-19 00:30 UTC
Can we please add this feature to the plugin?  Its would be nice that we don't have to go to our video driver for this function, and just use the app chooses option in our driver settings.

**Comment by fzurita** [comment] 2017-02-19 04:25
Mupen64Plus already has control for this using the "VerticalSync" config parameter.

**Comment by theboy181** [comment] 2017-02-19 04:37
Was hoping for zilmar spec support

**Comment by gonetz** [comment] 2017-02-19 14:22
Duplicate of #331

**Closed by gonetz** 2017-02-19 14:22 UTC
Labels: duplicate
