### ISSUE TITLE
Screenshots become invalid images

### ISSUE THREAD

**Issue by shinra358** [gonetz/GLideN64#409] opened 2015-04-15 20:25 UTC
When using project64 and trying to take a screenshot with f3, it creates an unreadable file with a diamond with a question mark inside of it at the beginning of the filename. It becomes readable when you remove that symbol in the filename. It also creates a folder with nothing in it with a filename of the 'diamond question mark' symbol.

**Comment by gonetz** [comment] 2015-04-16 08:04
What is the full path to Plugin folder?

**Comment by shinra358** [comment] 2015-04-16 11:38
E:\Users\*my name here*\My Documents\Games\CONSOLE\EMULATORS\NINTENDO\Nintendo64\Project64\Plugin

**Comment by gonetz** [comment] 2015-04-16 15:46
Does your name contain non-ASCII characters?

**Comment by shinra358** [comment] 2015-04-16 21:25
No, but it contains spaces.

**Comment by gonetz** [comment] 2015-04-17 09:47
Ok, I'll check it.

**Comment by gonetz** [comment] 2015-04-25 11:47
Confirmed. Do you have access to weekly beta builds?

**Comment by shinra358** [comment] 2015-04-25 21:19
I'm not sure. I don't think so. I dunno. I'm a $40 contributor. So whatever they get :P

**Comment by Predator82Germany** [comment] 2015-04-25 21:43
Then you haven´t

**Comment by gonetz** [comment] 2015-04-27 07:47
@shinra358 - I sent you link to latest weekly build. That issue should be fixed in it, please check.

**Comment by shinra358** [comment] 2015-04-27 11:16
Yes, it is fixed. However, could you make the pic file go into the screenshots folder now on PJ64 by default and that should be it. Currently it saves in the main directory.

**Comment by Predator82Germany** [comment] 2015-04-27 11:21
Good idea

**Comment by shinra358** [comment] 2015-04-27 11:26
Edited prev post.

**Comment by gonetz** [comment] 2015-04-27 11:42
So, it's the same problem as #425

**Comment by gonetz** [comment] 2015-04-27 11:45
Cite : "Screen shot path provided by emulator and it is simple non-unicode string. Latest build converts that string to QT string using your system locale. I also had problem with screen shots before if path to emulator contained non-ASCII characters. Now I can use local non-ASCII characters in path to Emulator folder and screen shots stored correctly."  It is how it works for me. Ok, lets make another attempt to fix it for you. I'll send you test build.

**Comment by gonetz** [comment] 2015-04-27 12:20
I sent you test build. It logs path to screnshot folder.
Run any game, make a screenshot. You should get file gliden64.log in the emulator's folder.
It contains the logged path, original and after conversion to QT string.
Please copy its content here.

Here the mine log:
SaveScreenshot.
  Path provided by emulator:'C:\Games\N64\Project64 2.2\Screenshots\'
  Path after QString::fromLocal8Bit:'C:\Games\N64\Project64 2.2\Screenshots\'
  Path after QString::fromLatin1:'C:\Games\N64\Project64 2.2\Screenshots\'
  Path after QString::sprintf:'C:\Games\N64\Project64 2.2\Screenshots\'

All converted strings are the same as original one, so screenshot save works for me.

**Comment by shinra358** [comment] 2015-04-27 12:23
Still same for me. Empty k folder. k is the first letter of the image's name in root dir. I'm gonna put pj64 at the root of the hdd to see if it has anything to do with directly character length.

**Comment by Predator82Germany** [comment] 2015-04-27 12:27
SaveScreenshot.
  Path provided by emulator:'k\Users\WC\Desktop\Project 64 2.2.0.3\Screenshots\'
  Path after QString::fromLocal8Bit:'k\Users\WC\Desktop\Project 64 2.2.0.3\Screenshots\'
  Path after QString::fromLatin1:'k\Users\WC\Desktop\Project 64 2.2.0.3\Screenshots\'
  Path after QString::sprintf:'k\Users\WC\Desktop\Project 64 2.2.0.3\Screenshots\'

**Comment by gonetz** [comment] 2015-04-27 12:34
Super! The first path, provided by the emulator is wrong.
How screenshot save works for you with other plugins?!

**Comment by Predator82Germany** [comment] 2015-04-27 12:37
With Glide64 it works

**Comment by gonetz** [comment] 2015-04-27 12:38
I wonder, how?
[Digging the code]

**Comment by Predator82Germany** [comment] 2015-04-27 12:39
Don´t know

**Comment by gonetz** [comment] 2015-04-27 12:52
Made another try. Please remove old log, check and give me the new log.

**Comment by Predator82Germany** [comment] 2015-04-27 12:56
SaveScreenshot.
  Path provided by emulator:'C:\Users\WC\Desktop\Project 64 2.2.0.3\Screenshots\'
  Path after QString::fromWCharArray:'C:\Users\WC\Desktop\Project 64 2.2.0.3\Screenshots\'
  Path after QString::sprintf:'C:\Users\WC\Desktop\Project 64 2.2.0.3\Screenshots\'
Seems fixed

**Comment by gonetz** [comment] 2015-04-27 12:58
Phew!!!
Thanks for help!

**Comment by shinra358** [comment] 2015-04-27 13:03
Yeah, all good here.

**Comment by Predator82Germany** [comment] 2015-04-27 13:03
Will be in next build?
Then close shinra

**Comment by gonetz** [comment] 2015-04-27 13:04
Sure

**Comment by gonetz** [comment] 2015-04-27 13:05
@Predator82Germany Please test #424 with that build. It includes necessary fix.

**Comment by gonetz** [comment] 2015-04-27 13:10
@shinra358 Please close.

**Comment by Predator82Germany** [comment] 2015-04-27 13:11
Done

**Closed** 2015-04-27 13:36 UTC

**Comment by shinra358** [comment] 2015-04-27 13:37
Calm down calm down, I got it. Thought anyone could close :P

**Comment by gonetz** [comment] 2015-04-29 16:49
Anyone can close. But we prefer the author check that everything is ok and close its bugreport.
