### ISSUE TITLE
Indiana Jones Wrong Z-level for Water Particles and Garbage Line

### ISSUE THREAD

**Issue by OtavioRaposo** [gonetz/GLideN64#1977] opened 2019-01-01 19:48 UTC
Just look the screenshot. Two problems I found:
1 - Water Particles in the waterfall (of the first level) are showing over the cliff.
### **EDIT: Disabling the N64-style depth compare solves the issue of the water particles. For some reason this was in the per-game setting, but I didn't notice. Sorry.**

2 - There's this flickering vertical line in the right corner of the screen which seems to be garbage.

I'm using GlideN64_d420737d in Project64 (but it has the same problem in m64p).

![untitled](https://user-images.githubusercontent.com/36393971/50575902-d98fc900-0ded-11e9-8704-f5d3e0b20205.png)

**Comment by gonetz** [comment] 2019-01-08 09:46
I set N64 depth compare enabled by default in commit d420737d.
This game works incorrect with N64 depth compare. This commit need to be reverted, N64 depth compare is not ready to be default mode yet.

Flickering vertical line of garbage is a known problem, which appears in several games.
Current solution - use crop feature to cut 1-2 pixels from the right.

**Comment by olivieryuyu** [comment] 2019-01-08 10:55
@gonetz 

Can be the flickering vertical line can be due to this?

https://sourceforge.net/p/angrylions-stuff/code/87/

**Comment by gonetz** [comment] 2019-01-08 11:03
Hmm, may be. I need to check it. Thanks!

**Comment by gonetz** [comment] 2019-01-09 12:06
@olivieryuyu you must be right. Check this screen shot, GLideN64 in LLE and native resolution:
![indi_gl](https://user-images.githubusercontent.com/8983092/50898090-a5955300-1440-11e9-8945-8aaf965b2a85.jpg)
Check cactus on the left.
Here the same picture with AL plugin, revision 112:
![indi_al](https://user-images.githubusercontent.com/8983092/50898179-f2792980-1440-11e9-8b1b-0a92eaa597fc.jpg)
The cactus is cut by black boarder on the left and the garbage is cut by black boarder on the right. I think this is an example of "the shocking truth" mentioned in commit message for revision 87.

**Comment by olivieryuyu** [comment] 2019-01-09 12:20
I guess we have most likely a complied version of this plugin before this revision 87. We should check if it matches with GlideN64. if so we clearly know that this is the root cause of the issue, otherwise it would be something else. Will try to find out this tonight.

**Comment by olivieryuyu** [comment] 2019-01-09 13:34
I will also check on real N64 if angrylion is correct.

**Comment by gonetz** [comment] 2019-01-09 13:40
> I will also check on real N64 if angrylion is correct with Indiana Jones.

I already checked. It seems that angrylion is correct.

**Comment by gonetz** [comment] 2019-01-16 10:54
@OtavioRaposo both reported issue should be fixed now. Please test.

**Comment by OtavioRaposo** [comment] 2019-01-16 16:36
Yes, it's working like a charm.

**Comment by olivieryuyu** [comment] 2019-01-16 16:44
pls close then :)

**Closed** 2019-01-16 16:51 UTC
