### ISSUE TITLE
Superbowling: black screen in menu and game

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#116] opened 2014-11-10 12:07 UTC
![sdhhhhhhhh](https://cloud.githubusercontent.com/assets/8987490/4975548/46de8c8e-68da-11e4-993b-3ce14bfbc845.jpg)

![fffffffffffffffff](https://cloud.githubusercontent.com/assets/8987490/4975551/51766e64-68da-11e4-95ac-a8519854819f.jpg)

Rice emulates the game with the hack. May be a kind of fb effect (?)

**Comment by gonetz** [comment] 2015-02-28 11:22
The game uses weird way to render the scene. Disable FB emulation and you will see a 3D model in top left corner. That model must be in center of the screen. I guess the programmers were lazy to calculate offsets to put the model on its place. They just opened new frame buffer with origin inside the main frame buffer. That origin corresponds to the top left corner of gray rectangle on the screen. 3D model is drawn in that new frame buffer, no offsets. My frame buffer emulation can't do such a trick. Special coding is required.

**Comment by olivieryuyu** [comment] 2015-03-07 17:08
then the Rice hack may be the right thing to do

**Comment by purplemarshmallow** [comment] 2016-01-24 13:28
I am working on a concept how games like this one can be emulated. My first idea was to always select the correct buffer and then calculate rendering offsets based on the start address. I did some tests and had very little success with this method. I don't think this can work in general I want to find a general solution that can also work in other games like NASCAR.

So I came up with a different idea. Render everything in different buffers and then the VI must combine them. The problem is they must be blended with each other in the correct order. @gonetz what do you think?
![vi](https://cloud.githubusercontent.com/assets/7283660/12536462/879e7c30-c2a6-11e5-8917-eec13b1c9e8e.jpg)

**Comment by purplemarshmallow** [comment] 2016-05-29 16:18
Working now with z64gl
https://github.com/purplemarshmallow/z64/blob/master/src/rgl.cpp#L630

I tried to fix it with GLideN64 as well but it's more difficult. GLideN64 removes overlapping buffers, z64gl does not do that.

cite from #342

>When plugin's frame buffer emulation algorithm detects that new buffer intersects with previously allocated buffer, old buffer considered as invalid and removed. This is correct behavior

**Comment by weinerschnitzel** [comment] 2016-05-29 18:45
What if you remove previously allocated buffers that intersect with new ones after a full VI? 

Would that solve flickering issues and allow these programming tricks to work, or does this break things?

**Comment by gonetz** [comment] 2016-05-30 02:23
It needs investigations, can't say for sure.

**Comment by purplemarshmallow** [comment] 2016-05-30 05:51
https://github.com/gonetz/GLideN64/blob/master/src/FrameBuffer.cpp#L595
This causes the slowdown ingame
Maybe it would be better to use erased flags instead like z64gl

**Comment by gonetz** [comment] 2016-05-30 06:24
> This causes the slowdown ingame

In this particular game?

**Comment by purplemarshmallow** [comment] 2016-05-30 08:11
Yes, in this particular game
Buffers are removed and created over and over again. This causes the slowdown

**Comment by gonetz** [comment] 2016-05-30 08:17
Marking buffers as erased will not fix the scene rendering, right?

**Comment by purplemarshmallow** [comment] 2016-05-30 08:54
right but I think it's the first step to support the scene rendering

With z64gl I check if buffers are overlapping and then I calculate the offset and copy from one buffer to the other one. https://github.com/purplemarshmallow/z64/blob/master/src/rgl.cpp#L630
But GLideN64 removes overlapping buffers

**Comment by gonetz** [comment] 2016-05-30 09:16
This step is useless by itself. As a part of the solution - why not. Do you want to take this task and complete it?

**Comment by purplemarshmallow** [comment] 2016-05-30 10:09
I had no luck so far. I can try my idea and introduce erased flags and see if it helps

**Comment by gonetz** [comment] 2016-05-30 10:39
If you will take it, don't forget that buffers marked as erased must be eventually removed to free resources.

**Comment by purplemarshmallow** [comment] 2018-10-02 18:56
This solution seems better than the one I implemented in z64gl, Super Bowling has depth issues in z64gl
NASCAR is also fixed!

**Comment by gonetz** [comment] 2018-10-21 05:35
@olivieryuyu Fixed in current WIP. Please test.

**Closed as completed** 2018-10-21 06:21 UTC
