### ISSUE TITLE
Goldeneye 64 Cliping issue

### ISSUE THREAD

**Issue by theboy181** [gonetz/GLideN64#652] opened 2015-08-11 00:28 UTC
In these pictures I took screenshots with different plugins to show that the gun, or soldier disappears when he gets close to the camera. I tested this on the actual HW and it doesn't happen.

I find it uneasy that AL's plugin shows this glitch too. I wonder if its the RSP, or RDP or a mixture of both.

GLIDE64 FINAL works as expected
![capture](https://cloud.githubusercontent.com/assets/9299743/9187360/73c28b34-3f84-11e5-9b5a-77e4286dfa3b.PNG)
GLIDEN64 HLE soldier disappears
![capture2](https://cloud.githubusercontent.com/assets/9299743/9187362/76b3396a-3f84-11e5-8e1d-9d93e37cc26f.PNG)
GLIDEN64 LLE just the gun
![capture3 gliden64 lle](https://cloud.githubusercontent.com/assets/9299743/9187369/79ad4070-3f84-11e5-901e-1e733663959a.PNG)
ANGRYLIONS RDP gun disappears
![capture al](https://cloud.githubusercontent.com/assets/9299743/9187371/7b37e1ca-3f84-11e5-9b80-4a30e6a71718.PNG)

**Comment by AmbientMalice** [comment] 2015-08-11 00:54
This is a duplicate of https://github.com/gonetz/GLideN64/issues/634 for the record.

**Comment by olivieryuyu** [comment] 2015-08-11 05:10
though the screeenshots are interesting. may be it would be good to move this report to #634

**Closed** 2015-08-11 05:51 UTC
