### ISSUE TITLE
Android: Multisampling causes black screen.

### ISSUE THREAD

**Issue by retrobenny** [gonetz/GLideN64#869] opened 2016-02-16 19:01 UTC
Such a shame too,I really wanted to see just how good 6xBRZ could look (than it already does) by combining 16x multisampling with it,but it just gives me a black screen with only audio on the 3.1 variant,even by itself as the only enhancement.
I wanted to see it despite the slideshow speeds as a result of it,due to 3.1's performance impact.
I noticed it is only usable on the 3.1 variant.
Banjo-Tooie is the tested game,I also would like to note that hardware/per-pixel lighting no longer crashes it.

**Comment by gonetz** [comment] 2016-02-17 04:24
As I remember, multisampling does not work on Android indeed. At least it did not work the last time I tried to run it on my NVidia Shield. I did not have time to investigate it. Probably, I select wrong texture format for MS textures. Do you know an open-source demo, which uses multisampling on Android?

**Comment by retrobenny** [comment] 2016-02-17 19:04
Found something,but it is for Mali specifically.

http://malideveloper.arm.com/resources/sample-code/anti-aliasing-example/

http://malideveloper.arm.com/resources/sample-code/selecting-the-correct-eglconfig/

Hope these help you solve the issues,some statements mention a similar case to the actual issue,like slowdown and heavy CPU cycles contributing to the slowness.
Something is likely wrong with GLideN64 in the EGL portion for multisampling,it seems.

**Comment by fivefeet8** [comment] 2016-02-18 17:20
MSAA will work on Android only if you disable Framebuffers.  I've confirmed it worked on my Shield Tablet and TV once that was done.  However, you lose many effects and widescreen.

**Comment by retrobenny** [comment] 2016-02-18 18:43
...ouch

Maybe there is a cause-and-effect issue that framebuffer does normally,and something changed in it could fix it.
Rice's multisampling works,as it does not have a framebuffer in use,and even allows ES2.0 usage.

What do you think about Vulkan?
How does "VLideN64" sound as a name if you decide normally (or by donation incentive) to make a Vulkan version with full OpenGL 4.5 feature-set support on Android via Shield TV?
It could definitely benefit with greater performance including the lower overhead,and LLE may even be possible at great speeds either with GLideN64 or another LLE plugin like Angrylion (original and/or modded version) if one is ported to Android.

**Comment by ADormant** [comment] 2016-02-19 02:43
It's even possible to do hybrid Vulkan/OpenGL 4.5 renderer with this extension GL_NV_draw_vulkan_image

**Comment by gonetz** [comment] 2016-02-19 03:27
>> MSAA will work on Android only if you disable Framebuffers.

GLideN64 uses MSAA for frame buffers only. You probably may force MSAA in drivers and get AA without framebuffers emulation, but normally you need fb emulation enabled to get AA with GLideN64

**Comment by gonetz** [comment] 2016-02-19 03:32
> What do you think about Vulkan?

Vulkan version with full OpenGL 4.5 feature-set support would be great.
However, I have plenty of open issues not related to graphics API.
Thus, I'll not take that task anytime soon.

**Comment by fivefeet8** [comment] 2016-02-19 06:57
@gonetz 
I didn't force MSAA in drivers.  I set the MSAA option in the GlideN64 ES3.1 config to 2, then unchecked the framebuffer option.

**Comment by gonetz** [comment] 2016-02-19 08:54
> Doing that seemed to allow MSAA to work on my Shield devices.

Nope. GLideN64 does not use MSAA if framebuffer option is off. It does not matter, is the MSAA  option checked in that case.

**Comment by fivefeet8** [comment] 2016-02-19 16:40
@gonetz 
Is it possible it's using another form of AA?  I don't see how since I haven't changed anything in the device developer menu.

**Comment by gonetz** [comment] 2016-02-19 16:44
GLIDEN64 supports only MSAA

**Comment by fivefeet8** [comment] 2016-02-20 20:55
Then is there an explanation why I'm able to enable it?

**Comment by gonetz** [comment] 2016-02-21 04:48
It is question to authors of emulator's GUI frontend. For the plugin it is an option, which is ignored when  fb emulation is off.

**Comment by purplemarshmallow** [comment] 2016-02-21 16:16
https://github.com/gonetz/GLideN64/blob/master/src/mupenplus/OpenGL_mupenplus.cpp#L67
What does this code do? I think it allows AA if framebuffer emulation is off.

**Comment by gonetz** [comment] 2016-02-21 16:58
Ops! I totally forgot about it. Yes, mupen64plus API allows to set AA for created graphics context. I'm not sure that it actually works,  but at least it does not break things.

**Comment by fzurita** [comment] 2016-05-27 10:09
Another hint, multisampling works correctly with the full OpenGL version of the plugin on the NVidia Shield TV.

**Comment by fzurita** [comment] 2019-04-23 11:50
This should be closed. It has since been resolved.

**Closed** 2019-04-23 18:20 UTC
