### ISSUE TITLE
Performance regression with Copy To RDRAM

### ISSUE THREAD

**Issue by Enker** [gonetz/GLideN64#1312] opened 2016-12-25 21:44 UTC
I found some games (Mario Party 1-3/Paper Mario) that run at 10 to 20 VI/s in recent builds. The first build with the issue is GLideN64_236902b (Release Candidate 1) from Nov 27, 2016.

Disabling "Copy video card frame buffer to N64 memory" makes them run at normal speed.

Tested with intel HD Graphics 4600.

**Edit**: I rechecked this and it affects all games if the setting is "Synchronous".

**Comment by LegendOfDragoon** [comment] 2017-01-09 05:23
yup i got this issue on Intel HD 530..

**Comment by fzurita** [comment] 2017-01-11 21:18
It sounds like Intel has problems with this change: 313741d8276f0e018ba0c137892d67794468cc28

Is async mode any faster?

**Comment by Enker** [comment] 2017-01-11 22:03
Async mode is ~5 to 10 VI/s faster than Sync with the games I listed.

**Comment by LegendOfDragoon** [comment] 2017-01-11 22:08
>Is async mode any faster?

On my end, async mode is fine.

**Comment by fzurita** [comment] 2017-01-11 23:10
I wonder if Async mode suffered a similar slow down.

**Comment by Enker** [comment] 2017-01-11 23:20
I did a quick test with two games and Async mode runs at the same VI/s as older builds when you unlimit the speed.

**Comment by loganmc10** [comment] 2017-01-12 00:12
So it just affects sync mode?

**Comment by Enker** [comment] 2017-01-12 00:36
No, Mario Party & Paper Mario run slow with Async mode.
I noticed that Doubutsu no Mori runs fine with Sync mode, so not all games are affected.

**Comment by LegendOfDragoon** [comment] 2017-01-12 03:54
>So it just affects sync mode?

On my end, yes. I guess Enker's issue is different.

**Comment by loganmc10** [comment] 2017-01-12 05:54
TBH I'm not surprised that Intel has issues. Intel OpenGL drivers for Windows are terrible. I have a user that gets the wrong colours in Mario 64 with GLupeN64 because it uses ARB_buffer_storage for VBO's

https://github.com/GLupeN64/GLupeN64/issues/140

It could be that Intel's ARB_buffer_storage implementation is a bit shaky

**Comment by weinerschnitzel** [comment] 2017-01-12 23:44
I mostly use my Intel lappy but I test GlideN64 on my AMD HTPC. If I'm not mistaken gonetz has been only focusing on AMD and Nvidia. Im not expecting any support for Intel as of yet. If there is strong interest in fixing up Intel, I will start submitting issues for it.

**Comment by LegendOfDragoon** [comment] 2017-01-13 00:56
I think a good solution might be to allow the user to choose which method to use. I also wonder if the GLES2 version is faster on my Intel HD 530.

>Im not expecting any support for Intel as of yet.

It should honestly just work :smile: . Btw I got code for you to test. When can you get on IRC?

>I will start submitting issues for it

I think it's good to submit issues just so others can be aware of them.

**Comment by loganmc10** [comment] 2017-01-13 00:59
> I also wonder if the GLES2 version is faster on my Intel HD 530.

Well the GLES2 version would disable these buffer copies anyway since it only works on Android for GLES2

**Comment by LegendOfDragoon** [comment] 2017-01-13 01:05
>Well the GLES2 version would disable these buffer copies anyway since it only works on Android for GLES2

Oh I see. I wonder why the performance for async mode hasn't changed on my end. Seems odd to me.

**Comment by fzurita** [comment] 2017-01-13 03:07
Different driver version? Different Intel chipset?

**Comment by LegendOfDragoon** [comment] 2017-01-20 02:50
>Different Intel chipset?

likely that I guess.

Are there any plans to resolve this issue? I think z64gl's method is pretty fast.

**Comment by fzurita** [comment] 2017-01-20 03:10
Maybe the dolphin method should be used. They have checks for different hardware and will do alternate methods depending on the current hardware.

**Comment by LegendOfDragoon** [comment] 2017-01-20 06:52
Not a bad idea.

**Comment by loganmc10** [comment] 2017-03-30 03:05
This should be fixed now: https://github.com/gonetz/GLideN64/commit/ebcf46e5adc0fe8717143a8e31949bc09247a149

I tested Linux + Intel and Windows + Nvidia and I saw no performance regression, so it seems that this is probably related to some Intel Windows driver bug 

In any case, the code has been disabled for Intel GPUs so it should work as it used to for you guys

**Comment by Enker** [comment] 2017-04-03 20:18
Thanks for working on this! I tested the latest Mupen64Plus + Zilmar builds and the issue is fixed for me.

The performance seems to be the same as the old working builds as well.

**Comment by gonetz** [comment] 2017-04-04 01:57
@Enker Please close, if issue is fixed.

**Closed** 2017-04-04 02:36 UTC
