### ISSUE TITLE
nushi zueri 64 : fb in game not handled (regression)

### ISSUE THREAD

**Issue by olivieryuyu** [gonetz/GLideN64#1435] opened 2017-03-20 11:54 UTC
![26985bee-0a86-11e7-89a3-d39a7cc79aec](https://cloud.githubusercontent.com/assets/8987490/24098746/671ca470-0d6c-11e7-8d28-730f655b9dce.jpg)

**Comment by gonetz** [comment] 2017-03-20 15:18
Caused by 27cdae1e33044

**Comment by loganmc10** [comment] 2017-03-20 15:37
@gonetz do you think this could be related to https://github.com/gonetz/GLideN64/issues/1434? It seems to also be some kind of depth buffer issue.

**Comment by gonetz** [comment] 2017-03-21 02:42
I did not analyse it yet. I just found the regression commit.

**Comment by gonetz** [comment] 2017-03-21 14:17
The issues is duplicate of #1115

The game needs the following settings:
* Color buffer copy: sync
* Depth buffer copy: off

**Closed by gonetz** 2017-03-21 14:17 UTC
Labels: duplicate
