### ISSUE TITLE
Anti-Aliasing settings not saving properly

### ISSUE THREAD

**Issue by dercuspercus** [gonetz/GLideN64#2524] opened 2021-06-26 18:18 UTC
I'm having a strange issue with the MSAA setting, where no matter what I do, even returning to default settings, it will max out the MSAA setting to 16x. Setting it to 0, or turning it off completely, and saving causes it to just jump straight back to 16x, and it's causing noticeable lag in the games that I play

**Comment by Squall-Leonhart** [comment] 2021-06-29 07:53
i suspect you're talking about anistropic filtering. since glide64 doesn't support 16x msaa

**Comment by Rosalie241** [comment] 2021-06-29 20:20
should be resolved with https://github.com/gonetz/GLideN64/pull/2526

**Comment by Squall-Leonhart** [comment] 2021-06-30 09:14
Confirmed fixed.

**Closed** 2021-07-21 12:55 UTC
