### ISSUE TITLE
Mischief Makers Missing Polygons

### ISSUE THREAD

**Issue by GameRecover** [gonetz/GLideN64#719] opened 2015-09-21 13:54 UTC
If you start the rom (I believe any, but I was testing on U!) and hit no buttons you see a brief intro movie after some of the logos. The last part of this movie is Marina on a blue background, throwing a clancer. When he hits the background, all you see is blue. This is incorrect; there should be many 3d rocks.

![clipboard02](https://cloud.githubusercontent.com/assets/13943509/9993570/da39d072-60bb-11e5-9c79-0b80be9f5718.jpg)

Here's the console version for comparison. https://www.youtube.com/watch?v=K4VxOr31kzI

This isn't exclusive to this cutscene. Level 4-1 is missing a rock (which the main objective of the level is to avoid). It still moves as though it was there, however, it is just invisible. I actually have a feeling it might be behind the background or something. The could be various other instances of this happening in this game too, whilst it is playable if you know the game well, this makes it very difficult.

**Comment by purplemarshmallow** [comment] 2015-09-21 14:09
#141 duplicate

**Comment by GameRecover** [comment] 2015-09-21 14:42
I did see that but it lacked certain details and I thought it might be worth splitting this and that into separate issues as the texture bug is a completely different story that from what I can tell is only working in the plugin thecoreyburton provided. 

If you want me to close this, then that's alright.

**Comment by purplemarshmallow** [comment] 2015-09-21 15:06
I'm not sure I thought you have not seen it. It's probably bad to have two different problems in one issue better leave it open then

**Comment by purplemarshmallow** [comment] 2015-09-21 19:21
correct with glN64 0.3.1
![1](https://cloud.githubusercontent.com/assets/7283660/10002127/aff91112-60a5-11e5-9cf7-865128bf525f.jpg)

**Comment by purplemarshmallow** [comment] 2015-09-24 00:58
I noticed angrylion's plugin has this bug as well. I've reported it to angrylion and he's working on it:
http://sourceforge.net/p/angrylions-stuff/tickets/7/

**Comment by GameRecover** [comment] 2015-09-24 03:15
It's fixed, as of half an hour ago (and should be available in an upcoming revision).

**Comment by purplemarshmallow** [comment] 2015-09-24 04:10
http://sourceforge.net/p/angrylions-stuff/code/96/
>rdp: alpha compare should happen after the 1st cycle of a two-cycle combiner (confirmed by hardware tests, this fixes the rocks at the end of Mischief Makers 

GLideN64 likely has the same problem

**Comment by thecoreyburton** [comment] 2016-02-05 13:38
I tested this in the hopes that it was resolved with the recent changes but this is still an issue with the current builds.

**Comment by gonetz** [comment] 2016-02-05 16:06
@thecoreyburton "alpha compare should happen after the 1st cycle of a two-cycle combiner " is very easy to implement. Solution looks strange though, so I put it to separate branch to test for possible regressions:
https://github.com/gonetz/GLideN64/commit/6faff6cc18e003f78f8d20b715ae55b4222b07bf

Binary to test:
https://drive.google.com/file/d/0B0YqMPjGo3B2Wjk5MG9USEFtcm8/view?usp=sharing

pass: test

**Comment by AmbientMalice** [comment] 2016-02-06 00:19
This is a rather odd situation because the rocks differ in appearance depending on whether save states are used, from what I see. Angrylion's is affected, too. Sometimes they're smooth, other times they have coloured specks on them.

**Comment by purplemarshmallow** [comment] 2016-02-06 02:02
If some values are inherited then results can be wrong when loading a savestate

angrylion's plugin looks correct but GLideN64 seems to show wrong textures. But the missing rocks are fixed
![1](https://cloud.githubusercontent.com/assets/7283660/12863899/de50267e-cc7d-11e5-9d03-8acd09129789.jpg)
![gliden64_mischief_makers_000](https://cloud.githubusercontent.com/assets/7283660/12863900/e0bd5fee-cc7d-11e5-8501-a8c7b73d351b.jpg)

**Comment by AmbientMalice** [comment] 2016-02-06 03:29
>But the missing rocks are fixed

And they also look somewhat more accurate than Glide64's.

**Comment by gonetz** [comment] 2016-02-07 08:10
The random noise on the rocks is cause by an error in mipmap shader. It is really random noise, not a texture. Sometimes it even may look correct. I have fixed the issue in the shader. Texture loaded correctly now, but rocks now suffer from the same error with texture coordinates, which plagues all 3D objects in that game.

**Comment by gonetz** [comment] 2016-02-07 08:27
I also found that "alpha compare should happen after the 1st cycle of a two-cycle combiner" is the only way to make the rocks visible. The second cycle of the combiner combiner multiplies pixel alpha by shade (vertex) alpha. Vertex alpha is zero for all vertices. Thus, resulting pixel alpha is zero and all pixels discarded by alpha compare. If alpha compare applied after the 1st cycle, pixel's alpha is not zero yet and pixels are not discarded..

**Comment by gonetz** [comment] 2016-02-07 14:54
Hmm, I just found that angrylion's plugin also works incorrect with 3D in that game, at least all builds I have work incorrect. Is it fixed in any revision of angrylion's plugin?

**Comment by purplemarshmallow** [comment] 2016-02-07 15:11
angrylion's plugin works correctly. The problem is values are inherited and it will not look correct if you load a savestate.

**Comment by gonetz** [comment] 2016-02-07 15:29
Please give me correct save/savestate for this game

**Comment by purplemarshmallow** [comment] 2016-02-07 15:36
https://drive.google.com/file/d/0B7Y6r4SpC_QQNkozaTJjejg1MlU/view?usp=sharing

**Comment by gonetz** [comment] 2016-02-07 17:17
Thanks! 
angrylion's plugin does not work correct from savestate even if state was made with it. Hard to debug issue. The problem is with texture wrapping flag. angrylion's texture clamp/wrap calculation works the same as GLideN64's one. I don't see, where the plugins start to work differently.

**Comment by purplemarshmallow** [comment] 2016-02-07 17:26
>angrylion's plugin does not work correct from savestate even if state was made with it.

I think it makes sense. Not every value is stored in the savestate.

My guess is that angrylion's plugin uses an inherited texture wrapping flag. With GLideN64 it's not inherited correctly or it's reseted at some point. But I can be wrong of course.

**Comment by gonetz** [comment] 2016-02-08 02:16
> Not every value is stored in the savestate.

Savestate is a memory dump. Raw state of the whole RDRAM. May be some RDP registers are restored incorrectly after savestate.

Analisys of the difference in behaviour of angrylion's plugin before and after the savestate load would help to understand, what is going on. But the code is very compex and hard to analyze.

**Comment by angrylion7** [comment] 2016-02-08 14:13
Yeah, this game writes to tile descriptors once, not on every display list. This information cannot be stored in a savestate courtesy of Zilmar's plugin architecture.

**Comment by gonetz** [comment] 2016-02-08 14:39
@angrylion7 Sergey, could you explain what is going on in that game? 

I see that settile and settilesize always called for tile 0, but only settile is called for tile 7, which is used for tile load. It does not matter, tile is loaded via loadblock. As I can see, the problem with texture mapping is because texture coordinates are out of texture size and texture must be wrapped. However, texture mask_s and mask_t are zero, thus clampens and clampent are enabled.

Which tile information makes the game look correct?

**Comment by angrylion7** [comment] 2016-02-08 15:12
These rocks are rendered in two-cycle mode, and the 1st cycle combiner equations use "texel1", so it needs data for tile 1 to be initialized. These are the commands that are executed once and skipped on subsequent display list calls (raw RDP commands straight from the game):
0xf5, 0x48, 0x09, 0x00, 0x01, 0x01, 0x40, 0x50,//set_tile for tile no. 1
0xf2, 0x00, 0x00, 0x00, 0x01, 0x03, 0xc0, 0x3c,//set_tile_size for tile no. 1

**Comment by gonetz** [comment] 2016-02-08 15:44
I don't understand, how it works
tile 1 tmem addr is 256, that is points to upper half of TMEM, where palette for CI texture is stored

max_tile is 0.

tile 1 no way can be used as valid texture.

The only clue is that texture clamp is disabled for tile 1. But I still don't understand how it helps rendering, because tile 0 is obviously used as texture source.

**Comment by angrylion7** [comment] 2016-02-08 16:00
>tile 1 tmem addr is 256, that is points to upper half of TMEM, where palette for CI texture is stored

When en_tlut is set, as we see can here, the address is masked to point to the lower half of TMEM, then a palette lookup is performed (fetch_texel_entlut() function in my plugin).

>max_tile is 0

That's irrelevant, max_tile is used only when calculating lod fraction and when redefining tiles currently in use if tex_lod_en is set. tex_lod_en is clear here. Search for the uses of max_level variable in my code.

**Comment by gonetz** [comment] 2016-02-08 16:56
> When en_tlut is set, as we see can here, the address is masked to point to the lower half of TMEM,

It was the key information. Masked tile 1 address is 0, thus it points to the same place as tile 0, but it is wrapped. With that information I have fixed the issue in one line. Thanks a lot!

Please clarify the moment with lod calculation. The first stage of the combiner is 
`(tile1-tile0)*lod_frac+tile0`
tex_lod_en is not set, but lod_frac should be
![gliden64_mischief_makers_000](https://cloud.githubusercontent.com/assets/8983092/12892597/1faaee66-ceb7-11e5-966d-bd4003e0998d.jpg)
 calculated anyway. lod_frac must be 1, otherwise it will be blended with tile 0 and result will be bad. Is lod_frac forced to be 1 in that case?

**Comment by gonetz** [comment] 2016-02-08 17:22
New binary to test:
https://drive.google.com/file/d/0B0YqMPjGo3B2WXRhSHdqZnFBREU/view?usp=sharing

pass: test

**Comment by angrylion7** [comment] 2016-02-08 17:24
If you're still talking about the rocks in the intro, then, according to my lodfrac_lodtile_signals() function, lod_fraction should equal 0xff. That's because shapen_tex_en and detail_tex_en are both clear, and the dis variable (from "distant") is set, since any element of log2table[] array is greater than or equal to max_level of zero.

**Comment by gonetz** [comment] 2016-02-08 17:29
@angrylion7 
Спасибо, круто! Но
http://risovach.ru/upload/2013/05/mem/dzheki-chan_18035904_big_.jpg

**Comment by AmbientMalice** [comment] 2016-02-09 02:20
>Yeah, this game writes to tile descriptors once, not on every display list. This information cannot be stored in a savestate courtesy of Zilmar's plugin architecture.

This is probably a redundant question, but could the Zilmar plugin spec be updated to work around this issue?

**Comment by gonetz** [comment] 2016-02-09 03:39
@AmbientMalice Nothing is impossible. RDP structure must be described in specs, maintained by emulator and provided to plugins. All plugins must keep that structure in actual state, and that state must be saved - restored along with RDRAM dump. Huge number of changes just to solve one particular issue. Almost all games do not have that problem because they update necessary RDP registers and descriptors per frame. Mischief Makers uses an uber optimization, which in conjunction with non-standard use of mip-mapping technique makes that trouble. Much easier solution would be a force tile 1 initialization with a simple hack.

**Comment by AmbientMalice** [comment] 2016-02-09 05:03
The reason I asked is because this issue reminds me of the Starcraft save state issue that apparently affects all plugins. https://code.google.com/archive/p/glidehqplusglitch64/issues/289

>Much easier solution would be a force tile 1 initialization with a simple hack.

Sure. Not ideal from a "keep the hacks to a minimum" perspective, but better that nothing.

**Comment by gonetz** [comment] 2016-02-09 08:57
Nothing is not bad either. The game works ok with regular saves.

**Comment by olivieryuyu** [comment] 2016-02-09 09:42
tested the new binary, so far no regression :)

**Comment by gonetz** [comment] 2016-02-09 09:49
I think it can go to master.

**Comment by purplemarshmallow** [comment] 2016-02-09 13:55
I noticed no regressions. Very good fix.
And I don't think there needs to be a workaround for the savestate issue

**Comment by gonetz** [comment] 2016-02-09 15:54
> And I don't think there needs to be a workaround for the savestate issue

At least it can wait.

**Comment by gonetz** [comment] 2016-02-09 16:04
Fixed with commits
https://github.com/gonetz/GLideN64/commit/1d1f4bdbb4b065aae92fabbb3aa60434f7bf81bb
https://github.com/gonetz/GLideN64/commit/232800a8238f918e066fa9cc1a217e0e4020679b

**Closed by gonetz** 2016-02-09 16:04 UTC
