### ISSUE TITLE
Problem with Project64 1.6.1 when close emulator

### ISSUE THREAD

**Issue by Anths2016** [gonetz/GLideN64#2126] opened 2019-11-05 16:08 UTC
"An unhandled win32 exception occured in Project64 v1.6.exe [5448]"

**Comment by oddMLan** [comment] 2019-11-05 18:33
Probably an emulator specific issue.

**Comment by gonetz** [comment] 2019-11-06 06:13
I've got similar error with latest nightly build of Project64 :(
Several month old builds work ok with the same build of GLideN64.
The problem somehow related to OpenGL initialization. Project64 2.2 and earlier called plugin initialization from one thread and plugin shutdown from another one. That is not allowed in case of OpenGL.

**Comment by oddMLan** [comment] 2019-11-06 06:25
Weird. Could be related to the GUI crashing issues too. Very system configuration dependant. I've never encountered this issue myself. I just downloaded the latest nightly from the Project64 website, and the latest WIP from WIP Builds 4. No error message at exit. Using Windows 10 x64 LTSC

**Comment by fzurita** [comment] 2019-11-06 11:33
The threaded opengl setting may be protecting against this by moving all opengl calls to one thread.

**Comment by oddMLan** [comment] 2019-11-06 19:01
That was using default settings, which means threaded OpenGL disabled

**Comment by Anths2016** [comment] 2019-11-06 19:27
> That was using default settings, which means threaded OpenGL disabled

Yes!

**Comment by oddMLan** [comment] 2019-11-06 19:42
> Yes! Maybe if it's activated doesn't crash.
Could you try enabling it then, and see if it stops crashing on your computer?

**Comment by Anths2016** [comment] 2019-11-06 20:54
don't crash.

**Comment by gonetz** [comment] 2019-11-07 08:18
Solution found. Can t be closed?

**Comment by oddMLan** [comment] 2019-11-07 08:31
IMO that's feels like a workaround since the default config is threaded video is disabled. Unless you feel that's something that should be fixed on the emulator side? Since you said it's doing an illegal operation (plugin initialization from one thread and plugin shutdown from another).

Maybe threaded video should be enabled by default, since it provides many upsides and virtually no downsides. Allegedly some extremely minor input lag. On my desktop I dont notice any improvement in speed but nor any lag introduced. On my laptop, it is a significant speed boost (about 30+%).

**Comment by gonetz** [comment] 2019-11-07 11:16
> Maybe threaded video should be enabled by default

It requires careful testing. I had Project64 freeze with threaded enabled.

**Comment by fzurita** [comment] 2019-11-07 12:10
If there are any issues with freezing with the threading, I would be interested in knowing reproducible scenarios so that they can be addressed.

The only one I knew of so far was with debug mode enabled, which could have affected non debug mode as well. And that was fixed.

**Comment by gonetz** [comment] 2019-11-09 06:43
I'll try threading mode again and report if the problem is reproducible.

**Comment by gonetz** [comment] 2019-11-23 05:56
I can't reproduce freezing with threaded enabled. I made it enabled by default, a8f2304

**Closed** 2019-11-23 05:55 UTC

**Comment by oddMLan** [comment] 2019-11-23 06:29
@gonetz could you restart the appveyor build? there was an error uploading the artifact.
