### ISSUE TITLE
widescreen pop-ins removable?

### ISSUE THREAD

**Issue by naddel81** [gonetz/GLideN64#1464] opened 2017-04-08 17:33 UTC
hi @ all,

I really love GlideN64, but is there a way to reproduce this here?

https://youtu.be/z--PzeQKfr8?t=16

I mean there is no pop-up/pop-in of trees or anything that is in the widescreen area. I noticed the widescreen hack that GlideN64 provides to produce many pop-up effects. 

Best wishes!

**Comment by AmbientMalice** [comment] 2017-04-09 01:44
They're tampering with the game rom. And using gameshark hacks on top of it. So it is extremely unlikely GLideN64 can replicate this.

**Comment by gonetz** [comment] 2017-04-09 02:51
Objects pop up in widescreen mode caused by optimizations in game's program code. To my knowledge,  it can't be fixed on graphics plugin side.

**Comment by i30817** [comment] 2017-04-09 11:42
You'd need something like the bundled PCSX2 widescreen hacks that work in conjunction and/or override of the plugin widescreen hack.

It would be actually a useful feature because emulation specific techniques for widescreen are usually more general and less fragile than game hacks, but often more buggy because of culling.

**Closed** 2017-05-16 08:19 UTC
Labels: wontfix

**Comment by theboy181** [comment] 2017-05-16 14:35
Working on this with zilmar. Hopefully the community will have some good codes for us all.
